// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCryptoService creates a new instance of MockCryptoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptoService {
	mock := &MockCryptoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCryptoService is an autogenerated mock type for the Service type
type MockCryptoService struct {
	mock.Mock
}

type MockCryptoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptoService) EXPECT() *MockCryptoService_Expecter {
	return &MockCryptoService_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCryptoService
func (_mock *MockCryptoService) Decrypt(ciphertext64 string) (string, error) {
	ret := _mock.Called(ciphertext64)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(ciphertext64)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(ciphertext64)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ciphertext64)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptoService_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCryptoService_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext64 string
func (_e *MockCryptoService_Expecter) Decrypt(ciphertext64 any) *MockCryptoService_Decrypt_Call {
	return &MockCryptoService_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext64)}
}

func (_c *MockCryptoService_Decrypt_Call) Run(run func(ciphertext64 string)) *MockCryptoService_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCryptoService_Decrypt_Call) Return(s string, err error) *MockCryptoService_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCryptoService_Decrypt_Call) RunAndReturn(run func(ciphertext64 string) (string, error)) *MockCryptoService_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCryptoService
func (_mock *MockCryptoService) Encrypt(plaintext string) (string, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptoService_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCryptoService_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *MockCryptoService_Expecter) Encrypt(plaintext any) *MockCryptoService_Encrypt_Call {
	return &MockCryptoService_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *MockCryptoService_Encrypt_Call) Run(run func(plaintext string)) *MockCryptoService_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCryptoService_Encrypt_Call) Return(s string, err error) *MockCryptoService_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCryptoService_Encrypt_Call) RunAndReturn(run func(plaintext string) (string, error)) *MockCryptoService_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
