// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/CTFBoard/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHintUnlockRepository creates a new instance of MockHintUnlockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHintUnlockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHintUnlockRepository {
	mock := &MockHintUnlockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHintUnlockRepository is an autogenerated mock type for the HintUnlockRepository type
type MockHintUnlockRepository struct {
	mock.Mock
}

type MockHintUnlockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHintUnlockRepository) EXPECT() *MockHintUnlockRepository_Expecter {
	return &MockHintUnlockRepository_Expecter{mock: &_m.Mock}
}

// GetByTeamAndHint provides a mock function for the type MockHintUnlockRepository
func (_mock *MockHintUnlockRepository) GetByTeamAndHint(ctx context.Context, teamId uuid.UUID, hintId uuid.UUID) (*entity.HintUnlock, error) {
	ret := _mock.Called(ctx, teamId, hintId)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamAndHint")
	}

	var r0 *entity.HintUnlock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.HintUnlock, error)); ok {
		return returnFunc(ctx, teamId, hintId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.HintUnlock); ok {
		r0 = returnFunc(ctx, teamId, hintId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.HintUnlock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamId, hintId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHintUnlockRepository_GetByTeamAndHint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamAndHint'
type MockHintUnlockRepository_GetByTeamAndHint_Call struct {
	*mock.Call
}

// GetByTeamAndHint is a helper method to define mock.On call
//   - ctx context.Context
//   - teamId uuid.UUID
//   - hintId uuid.UUID
func (_e *MockHintUnlockRepository_Expecter) GetByTeamAndHint(ctx any, teamId any, hintId any) *MockHintUnlockRepository_GetByTeamAndHint_Call {
	return &MockHintUnlockRepository_GetByTeamAndHint_Call{Call: _e.mock.On("GetByTeamAndHint", ctx, teamId, hintId)}
}

func (_c *MockHintUnlockRepository_GetByTeamAndHint_Call) Run(run func(ctx context.Context, teamId uuid.UUID, hintId uuid.UUID)) *MockHintUnlockRepository_GetByTeamAndHint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHintUnlockRepository_GetByTeamAndHint_Call) Return(hintUnlock *entity.HintUnlock, err error) *MockHintUnlockRepository_GetByTeamAndHint_Call {
	_c.Call.Return(hintUnlock, err)
	return _c
}

func (_c *MockHintUnlockRepository_GetByTeamAndHint_Call) RunAndReturn(run func(ctx context.Context, teamId uuid.UUID, hintId uuid.UUID) (*entity.HintUnlock, error)) *MockHintUnlockRepository_GetByTeamAndHint_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnlockedHintIDs provides a mock function for the type MockHintUnlockRepository
func (_mock *MockHintUnlockRepository) GetUnlockedHintIDs(ctx context.Context, teamId uuid.UUID, challengeId uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, teamId, challengeId)

	if len(ret) == 0 {
		panic("no return value specified for GetUnlockedHintIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, teamId, challengeId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, teamId, challengeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamId, challengeId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHintUnlockRepository_GetUnlockedHintIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnlockedHintIDs'
type MockHintUnlockRepository_GetUnlockedHintIDs_Call struct {
	*mock.Call
}

// GetUnlockedHintIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - teamId uuid.UUID
//   - challengeId uuid.UUID
func (_e *MockHintUnlockRepository_Expecter) GetUnlockedHintIDs(ctx any, teamId any, challengeId any) *MockHintUnlockRepository_GetUnlockedHintIDs_Call {
	return &MockHintUnlockRepository_GetUnlockedHintIDs_Call{Call: _e.mock.On("GetUnlockedHintIDs", ctx, teamId, challengeId)}
}

func (_c *MockHintUnlockRepository_GetUnlockedHintIDs_Call) Run(run func(ctx context.Context, teamId uuid.UUID, challengeId uuid.UUID)) *MockHintUnlockRepository_GetUnlockedHintIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHintUnlockRepository_GetUnlockedHintIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockHintUnlockRepository_GetUnlockedHintIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockHintUnlockRepository_GetUnlockedHintIDs_Call) RunAndReturn(run func(ctx context.Context, teamId uuid.UUID, challengeId uuid.UUID) ([]uuid.UUID, error)) *MockHintUnlockRepository_GetUnlockedHintIDs_Call {
	_c.Call.Return(run)
	return _c
}
