BearerAuth:
  description: 'JWT access token. Format: "Bearer {token}"'
  in: header
  name: Authorization
  type: apiKey

ApiTokenAuth:
  type: apiKey
  in: header
  name: Authorization
  description: 'API Token authentication. Format: Token {plaintext_token}'
