version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - gocyclo
    - gomodguard
    - goprintffuncname
    - govet
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - noctx
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    # Disabled overly strict/cosmetic linters
    - wsl
    - dupl
    - err113
    - mnd
    - paralleltest
    # Disabled stylistic linters - focus on real bugs and complexity
    - gocritic # Too many style suggestions
    - revive # Overlaps with other linters, too opinionated
    - nlreturn # Blank line before return - cosmetic
    - godot # Comment punctuation - cosmetic
    - godox # TODO comments are fine
    - nestif # Nested if complexity - covered by gocognit
    - forbidigo # fmt.Print in config/tests is acceptable
    - gochecknoglobals # Global vars in tests/metrics are fine
    - goconst # Repeated strings in tests are acceptable
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 12
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$
