// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/TakuyaYagam1/AstroCTFb/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Create(ctx context.Context, file *domain.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - file *domain.File
func (_e *MockFileRepository_Expecter) Create(ctx interface{}, file interface{}) *MockFileRepository_Create_Call {
	return &MockFileRepository_Create_Call{Call: _e.mock.On("Create", ctx, file)}
}

func (_c *MockFileRepository_Create_Call) Run(run func(ctx context.Context, file *domain.File)) *MockFileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.File
		if args[1] != nil {
			arg1 = args[1].(*domain.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Create_Call) Return(err error) *MockFileRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_Create_Call) RunAndReturn(run func(ctx context.Context, file *domain.File) error) *MockFileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockFileRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockFileRepository_Delete_Call {
	return &MockFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockFileRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Delete_Call) Return(err error) *MockFileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetAll(ctx context.Context) ([]*domain.File, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.File, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.File); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockFileRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileRepository_Expecter) GetAll(ctx interface{}) *MockFileRepository_GetAll_Call {
	return &MockFileRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockFileRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockFileRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetAll_Call) Return(files []*domain.File, err error) *MockFileRepository_GetAll_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.File, error)) *MockFileRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByChallengeID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetAllByChallengeID(ctx context.Context, challengeID uuid.UUID) ([]*domain.File, error) {
	ret := _mock.Called(ctx, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByChallengeID")
	}

	var r0 []*domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.File, error)); ok {
		return returnFunc(ctx, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.File); ok {
		r0 = returnFunc(ctx, challengeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetAllByChallengeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByChallengeID'
type MockFileRepository_GetAllByChallengeID_Call struct {
	*mock.Call
}

// GetAllByChallengeID is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
func (_e *MockFileRepository_Expecter) GetAllByChallengeID(ctx interface{}, challengeID interface{}) *MockFileRepository_GetAllByChallengeID_Call {
	return &MockFileRepository_GetAllByChallengeID_Call{Call: _e.mock.On("GetAllByChallengeID", ctx, challengeID)}
}

func (_c *MockFileRepository_GetAllByChallengeID_Call) Run(run func(ctx context.Context, challengeID uuid.UUID)) *MockFileRepository_GetAllByChallengeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetAllByChallengeID_Call) Return(files []*domain.File, err error) *MockFileRepository_GetAllByChallengeID_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_GetAllByChallengeID_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID) ([]*domain.File, error)) *MockFileRepository_GetAllByChallengeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChallengeID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByChallengeID(ctx context.Context, challengeID uuid.UUID, fileType domain.FileType) ([]*domain.File, error) {
	ret := _mock.Called(ctx, challengeID, fileType)

	if len(ret) == 0 {
		panic("no return value specified for GetByChallengeID")
	}

	var r0 []*domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.FileType) ([]*domain.File, error)); ok {
		return returnFunc(ctx, challengeID, fileType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.FileType) []*domain.File); ok {
		r0 = returnFunc(ctx, challengeID, fileType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.FileType) error); ok {
		r1 = returnFunc(ctx, challengeID, fileType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByChallengeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChallengeID'
type MockFileRepository_GetByChallengeID_Call struct {
	*mock.Call
}

// GetByChallengeID is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - fileType domain.FileType
func (_e *MockFileRepository_Expecter) GetByChallengeID(ctx interface{}, challengeID interface{}, fileType interface{}) *MockFileRepository_GetByChallengeID_Call {
	return &MockFileRepository_GetByChallengeID_Call{Call: _e.mock.On("GetByChallengeID", ctx, challengeID, fileType)}
}

func (_c *MockFileRepository_GetByChallengeID_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, fileType domain.FileType)) *MockFileRepository_GetByChallengeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.FileType
		if args[2] != nil {
			arg2 = args[2].(domain.FileType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByChallengeID_Call) Return(files []*domain.File, err error) *MockFileRepository_GetByChallengeID_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_GetByChallengeID_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, fileType domain.FileType) ([]*domain.File, error)) *MockFileRepository_GetByChallengeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChallengeIDs provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByChallengeIDs(ctx context.Context, challengeIDs []uuid.UUID) (map[uuid.UUID][]*domain.File, error) {
	ret := _mock.Called(ctx, challengeIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByChallengeIDs")
	}

	var r0 map[uuid.UUID][]*domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]*domain.File, error)); ok {
		return returnFunc(ctx, challengeIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]*domain.File); ok {
		r0 = returnFunc(ctx, challengeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, challengeIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByChallengeIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChallengeIDs'
type MockFileRepository_GetByChallengeIDs_Call struct {
	*mock.Call
}

// GetByChallengeIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeIDs []uuid.UUID
func (_e *MockFileRepository_Expecter) GetByChallengeIDs(ctx interface{}, challengeIDs interface{}) *MockFileRepository_GetByChallengeIDs_Call {
	return &MockFileRepository_GetByChallengeIDs_Call{Call: _e.mock.On("GetByChallengeIDs", ctx, challengeIDs)}
}

func (_c *MockFileRepository_GetByChallengeIDs_Call) Run(run func(ctx context.Context, challengeIDs []uuid.UUID)) *MockFileRepository_GetByChallengeIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByChallengeIDs_Call) Return(uUIDToFiles map[uuid.UUID][]*domain.File, err error) *MockFileRepository_GetByChallengeIDs_Call {
	_c.Call.Return(uUIDToFiles, err)
	return _c
}

func (_c *MockFileRepository_GetByChallengeIDs_Call) RunAndReturn(run func(ctx context.Context, challengeIDs []uuid.UUID) (map[uuid.UUID][]*domain.File, error)) *MockFileRepository_GetByChallengeIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByID(ctx context.Context, ID uuid.UUID) (*domain.File, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.File, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.File); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFileRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockFileRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockFileRepository_GetByID_Call {
	return &MockFileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockFileRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockFileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByID_Call) Return(file *domain.File, err error) *MockFileRepository_GetByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*domain.File, error)) *MockFileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLocation provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByLocation(ctx context.Context, location string) (*domain.File, error) {
	ret := _mock.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for GetByLocation")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.File, error)); ok {
		return returnFunc(ctx, location)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.File); ok {
		r0 = returnFunc(ctx, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLocation'
type MockFileRepository_GetByLocation_Call struct {
	*mock.Call
}

// GetByLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
func (_e *MockFileRepository_Expecter) GetByLocation(ctx interface{}, location interface{}) *MockFileRepository_GetByLocation_Call {
	return &MockFileRepository_GetByLocation_Call{Call: _e.mock.On("GetByLocation", ctx, location)}
}

func (_c *MockFileRepository_GetByLocation_Call) Run(run func(ctx context.Context, location string)) *MockFileRepository_GetByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByLocation_Call) Return(file *domain.File, err error) *MockFileRepository_GetByLocation_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetByLocation_Call) RunAndReturn(run func(ctx context.Context, location string) (*domain.File, error)) *MockFileRepository_GetByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPageID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByPageID(ctx context.Context, pageID uuid.UUID) ([]*domain.File, error) {
	ret := _mock.Called(ctx, pageID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPageID")
	}

	var r0 []*domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.File, error)); ok {
		return returnFunc(ctx, pageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.File); ok {
		r0 = returnFunc(ctx, pageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, pageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByPageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPageID'
type MockFileRepository_GetByPageID_Call struct {
	*mock.Call
}

// GetByPageID is a helper method to define mock.On call
//   - ctx context.Context
//   - pageID uuid.UUID
func (_e *MockFileRepository_Expecter) GetByPageID(ctx interface{}, pageID interface{}) *MockFileRepository_GetByPageID_Call {
	return &MockFileRepository_GetByPageID_Call{Call: _e.mock.On("GetByPageID", ctx, pageID)}
}

func (_c *MockFileRepository_GetByPageID_Call) Run(run func(ctx context.Context, pageID uuid.UUID)) *MockFileRepository_GetByPageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByPageID_Call) Return(files []*domain.File, err error) *MockFileRepository_GetByPageID_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_GetByPageID_Call) RunAndReturn(run func(ctx context.Context, pageID uuid.UUID) ([]*domain.File, error)) *MockFileRepository_GetByPageID_Call {
	_c.Call.Return(run)
	return _c
}

// ListLocations provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListLocations(ctx context.Context, limit int, offset int) ([]string, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListLocations")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]string, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []string); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_ListLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLocations'
type MockFileRepository_ListLocations_Call struct {
	*mock.Call
}

// ListLocations is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockFileRepository_Expecter) ListLocations(ctx interface{}, limit interface{}, offset interface{}) *MockFileRepository_ListLocations_Call {
	return &MockFileRepository_ListLocations_Call{Call: _e.mock.On("ListLocations", ctx, limit, offset)}
}

func (_c *MockFileRepository_ListLocations_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockFileRepository_ListLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListLocations_Call) Return(strings []string, err error) *MockFileRepository_ListLocations_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileRepository_ListLocations_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]string, error)) *MockFileRepository_ListLocations_Call {
	_c.Call.Return(run)
	return _c
}
