package challenge

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"sync"
	"time"

	"github.com/google/uuid"
	"golang.org/x/sync/errgroup"

	"github.com/TakuyaYagam1/AstroCTFb/internal/apperr"
	"github.com/TakuyaYagam1/AstroCTFb/internal/domain"
	"github.com/TakuyaYagam1/AstroCTFb/internal/usecase/guard"
)

const buildDownloadURLsConcurrency = 10

// GetByChallengeIDWithAccess returns files for a challenge filtered by fileType, enforcing
// access control for non-admin callers. It checks that the challenge is not hidden and
// that all prerequisite challenges are satisfied by the team. For writeup files it
// additionally requires that the team has an existing solve record for the challenge
// missing either condition returns ErrWriteupAccessDenied. Admin callers bypass all checks.
func (uc *FileUseCase) GetByChallengeIDWithAccess(ctx context.Context, challengeID uuid.UUID, fileType domain.FileType, teamID *uuid.UUID, isAdmin bool) ([]*domain.File, error) {
	if err := uc.ensureChallengeFileAccess(ctx, challengeID, fileType, teamID, isAdmin); err != nil {
		return nil, fmt.Errorf("FileUseCase - GetByChallengeIDWithAccess - ensureChallengeFileAccess: %w", err)
	}

	files, err := uc.deps.FileRepo.GetByChallengeID(ctx, challengeID, fileType)
	if err != nil {
		return nil, fmt.Errorf("FileUseCase - GetByChallengeIDWithAccess - FileRepo.GetByChallengeID: %w", err)
	}

	return files, nil
}

// GetDownloadURLWithAccess verifies that the caller may access the requested file, then
// returns an HMAC-signed short-lived download token embedded in a full download URL
// For non-admin callers it enforces: challenge visibility (not hidden), prerequisite
// satisfaction, and - for writeup files - that the team has a solve record. The token is
// generated by GenerateDownloadToken with an expiry of FileDeps.Expiry from now and bound
// to the caller's teamID so it cannot be reused by a different team.
func (uc *FileUseCase) GetDownloadURLWithAccess(ctx context.Context, fileID uuid.UUID, teamID *uuid.UUID, isAdmin bool) (string, error) {
	file, err := uc.deps.FileRepo.GetByID(ctx, fileID)
	if err != nil {
		return "", fmt.Errorf("FileUseCase - GetDownloadURLWithAccess - FileRepo.GetByID: %w", err)
	}

	if !isAdmin && file.ChallengeID != nil {
		if err := uc.ensureChallengeFileAccess(ctx, *file.ChallengeID, file.Type, teamID, isAdmin); err != nil {
			return "", fmt.Errorf("FileUseCase - GetDownloadURLWithAccess - ensureChallengeFileAccess: %w", err)
		}
	}

	expiry := time.Now().Add(uc.deps.Expiry)
	token := uc.GenerateDownloadToken(fileID, teamID, expiry)
	downloadURL := fmt.Sprintf("%s/api/v1/files/download/%s?token=%s", uc.deps.BaseURL, escapeLocationPath(file.Location), url.QueryEscape(token))

	return downloadURL, nil
}

func (uc *FileUseCase) ensureChallengeFileAccess(ctx context.Context, challengeID uuid.UUID, fileType domain.FileType, teamID *uuid.UUID, isAdmin bool) error {
	if isAdmin {
		return nil
	}

	challenge, err := uc.deps.ChallengeRepo.GetByID(ctx, challengeID)
	if err != nil {
		return fmt.Errorf("ChallengeRepo.GetByID: %w", err)
	}

	if err := guard.EnsureChallengeVisible(challenge); err != nil {
		return err
	}

	if err := uc.ensureRequirementsMet(ctx, challengeID, teamID); err != nil {
		return err
	}

	if fileType == domain.FileTypeWriteup {
		return uc.ensureWriteupSolveAccess(ctx, challengeID, teamID)
	}

	return nil
}

func (uc *FileUseCase) ensureRequirementsMet(ctx context.Context, challengeID uuid.UUID, teamID *uuid.UUID) error {
	reqs, err := uc.deps.ChallengeRepo.GetRequirements(ctx, challengeID)
	if err != nil {
		return fmt.Errorf("GetRequirements: %w", err)
	}

	if len(reqs) == 0 {
		return nil
	}

	if teamID == nil || uc.deps.SolveRepo == nil {
		return apperr.ErrChallengeNotFound
	}

	met, err := requirementsMet(ctx, challengeID, *teamID, uc.deps.ChallengeRepo, uc.deps.SolveRepo)
	if err != nil {
		return fmt.Errorf("requirementsMet: %w", err)
	}

	if !met {
		return apperr.ErrChallengeNotFound
	}

	return nil
}

func (uc *FileUseCase) ensureWriteupSolveAccess(ctx context.Context, challengeID uuid.UUID, teamID *uuid.UUID) error {
	if teamID == nil || uc.deps.SolveRepo == nil {
		return apperr.ErrWriteupAccessDenied
	}

	if _, err := uc.deps.SolveRepo.GetByTeamAndChallenge(ctx, *teamID, challengeID); err != nil {
		if errors.Is(err, apperr.ErrSolveNotFound) {
			return apperr.ErrWriteupAccessDenied
		}

		return fmt.Errorf("SolveRepo.GetByTeamAndChallenge: %w", err)
	}

	return nil
}

func (uc *FileUseCase) BuildDownloadURLs(ctx context.Context, files []*domain.File, teamID *uuid.UUID, isAdmin bool) (map[string]string, error) {
	if len(files) == 0 {
		return nil, nil
	}

	urls := make(map[string]string, len(files))

	var mu sync.Mutex

	g, gCtx := errgroup.WithContext(ctx)
	g.SetLimit(buildDownloadURLsConcurrency)

	for _, f := range files {
		file := f
		if file == nil {
			continue
		}

		g.Go(func() error {
			u, err := uc.GetDownloadURLWithAccess(gCtx, file.ID, teamID, isAdmin)
			if err != nil {
				return err
			}

			mu.Lock()
			urls[file.ID.String()] = u
			mu.Unlock()

			return nil
		})
	}

	err := g.Wait()
	if err != nil {
		return nil, fmt.Errorf("FileUseCase - BuildDownloadURLs - GetDownloadURLWithAccess: %w", err)
	}

	return urls, nil
}
