// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"github.com/skr1ms/CTFBoard/config"
	"github.com/skr1ms/CTFBoard/internal/storage"
	"github.com/skr1ms/CTFBoard/pkg/jwt"
	"github.com/skr1ms/CTFBoard/pkg/logger"
	"github.com/skr1ms/CTFBoard/pkg/mailer"
	"github.com/skr1ms/CTFBoard/pkg/websocket"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, l logger.Logger, pool *pgxpool.Pool, redisClient *redis.Client, storageProvider storage.Provider, jwtService *jwt.JWTService, wsHub *websocket.Hub, mailer2 mailer.Mailer) (*App, error) {
	userRepo := ProvideUserRepo(pool)
	teamRepo := ProvideTeamRepo(pool)
	solveRepo := ProvideSolveRepo(pool)
	txRepo := ProvideTxRepo(pool)
	fieldRepo := ProvideFieldRepo(pool)
	fieldValidator := ProvideFieldValidator(fieldRepo)
	fieldValueRepo := ProvideFieldValueRepo(pool)
	userUseCase := ProvideUserUseCase(userRepo, teamRepo, solveRepo, txRepo, jwtService, fieldValidator, fieldValueRepo)
	challengeRepo := ProvideChallengeRepo(pool)
	tagRepo := ProvideTagRepo(pool)
	competitionRepo := ProvideCompetitionRepo(pool)
	cache := ProvideCache(redisClient)
	scoreboardCacheService := ProvideScoreboardCacheService(cache, teamRepo)
	broadcaster := ProvideBroadcaster(wsHub)
	auditLogRepo := ProvideAuditLogRepo(pool)
	service, err := ProvideCrypto(cfg)
	if err != nil {
		return nil, err
	}
	challengeUseCase := ProvideChallengeUseCase(challengeRepo, tagRepo, solveRepo, txRepo, competitionRepo, teamRepo, redisClient, scoreboardCacheService, broadcaster, auditLogRepo, service)
	solveUseCase := ProvideSolveUseCase(solveRepo, challengeRepo, competitionRepo, userRepo, teamRepo, txRepo, cache, scoreboardCacheService, broadcaster)
	teamUseCase := ProvideTeamUseCase(teamRepo, userRepo, competitionRepo, txRepo, scoreboardCacheService)
	competitionUseCase := ProvideCompetitionUseCase(competitionRepo, auditLogRepo, redisClient)
	hintRepo := ProvideHintRepo(pool)
	hintUnlockRepo := ProvideHintUnlockRepo(pool)
	awardRepo := ProvideAwardRepo(pool)
	hintUseCase := ProvideHintUseCase(hintRepo, hintUnlockRepo, awardRepo, txRepo, solveRepo, scoreboardCacheService)
	verificationTokenRepo := ProvideVerificationTokenRepo(pool)
	emailUseCase := ProvideEmailUseCase(userRepo, verificationTokenRepo, mailer2, cfg)
	fileRepository := ProvideFileRepo(pool)
	fileUseCase := ProvideFileUseCase(fileRepository, storageProvider, cfg)
	awardUseCase := ProvideAwardUseCase(awardRepo, txRepo, scoreboardCacheService)
	statisticsRepository := ProvideStatisticsRepo(pool)
	statisticsUseCase := ProvideStatisticsUseCase(statisticsRepository, cache)
	submissionRepo := ProvideSubmissionRepo(pool)
	submissionUseCase := ProvideSubmissionUseCase(submissionRepo)
	tagUseCase := ProvideTagUseCase(tagRepo)
	fieldUseCase := ProvideFieldUseCase(fieldRepo)
	pageRepo := ProvidePageRepo(pool)
	pageUseCase := ProvidePageUseCase(pageRepo)
	bracketRepo := ProvideBracketRepo(pool)
	bracketUseCase := ProvideBracketUseCase(bracketRepo)
	ratingRepo := ProvideRatingRepo(pool)
	ratingUseCase := ProvideRatingUseCase(ratingRepo, solveRepo, teamRepo)
	notificationRepo := ProvideNotificationRepo(pool)
	notificationUseCase := ProvideNotificationUseCase(notificationRepo)
	apiTokenRepo := ProvideAPITokenRepo(pool)
	apiTokenUseCase := ProvideAPITokenUseCase(apiTokenRepo)
	backupRepo := ProvideBackupRepo(pool)
	backupUseCase := ProvideBackupUseCase(competitionRepo, challengeRepo, hintRepo, teamRepo, userRepo, awardRepo, solveRepo, fileRepository, backupRepo, storageProvider, txRepo, l)
	appSettingsRepo := ProvideAppSettingsRepo(pool)
	settingsUseCase := ProvideSettingsUseCase(appSettingsRepo, auditLogRepo, redisClient)
	configRepo := ProvideConfigRepo(pool)
	dynamicConfigUseCase := ProvideDynamicConfigUseCase(configRepo, auditLogRepo)
	commentRepo := ProvideCommentRepo(pool)
	commentUseCase := ProvideCommentUseCase(commentRepo, challengeRepo)
	controller := ProvideWsController(wsHub, l, cfg)
	validator := ProvideValidator()
	serverDeps := ProvideServerDeps(userUseCase, challengeUseCase, solveUseCase, teamUseCase, competitionUseCase, hintUseCase, emailUseCase, fileUseCase, awardUseCase, statisticsUseCase, submissionUseCase, tagUseCase, fieldUseCase, pageUseCase, bracketUseCase, ratingUseCase, notificationUseCase, apiTokenUseCase, backupUseCase, settingsUseCase, dynamicConfigUseCase, commentUseCase, jwtService, redisClient, controller, validator, l)
	router := ProvideRouter(cfg, l, serverDeps)
	server := ProvideServer(router, cfg)
	app := ProvideApp(server, userRepo)
	return app, nil
}
