// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAwardRepository creates a new instance of MockAwardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAwardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAwardRepository {
	mock := &MockAwardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAwardRepository is an autogenerated mock type for the AwardRepository type
type MockAwardRepository struct {
	mock.Mock
}

type MockAwardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAwardRepository) EXPECT() *MockAwardRepository_Expecter {
	return &MockAwardRepository_Expecter{mock: &_m.Mock}
}

// GetTeamTotalAwards provides a mock function for the type MockAwardRepository
func (_mock *MockAwardRepository) GetTeamTotalAwards(ctx context.Context, teamId string) (int, error) {
	ret := _mock.Called(ctx, teamId)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamTotalAwards")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, teamId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, teamId)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAwardRepository_GetTeamTotalAwards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamTotalAwards'
type MockAwardRepository_GetTeamTotalAwards_Call struct {
	*mock.Call
}

// GetTeamTotalAwards is a helper method to define mock.On call
//   - ctx context.Context
//   - teamId string
func (_e *MockAwardRepository_Expecter) GetTeamTotalAwards(ctx interface{}, teamId interface{}) *MockAwardRepository_GetTeamTotalAwards_Call {
	return &MockAwardRepository_GetTeamTotalAwards_Call{Call: _e.mock.On("GetTeamTotalAwards", ctx, teamId)}
}

func (_c *MockAwardRepository_GetTeamTotalAwards_Call) Run(run func(ctx context.Context, teamId string)) *MockAwardRepository_GetTeamTotalAwards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAwardRepository_GetTeamTotalAwards_Call) Return(n int, err error) *MockAwardRepository_GetTeamTotalAwards_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAwardRepository_GetTeamTotalAwards_Call) RunAndReturn(run func(ctx context.Context, teamId string) (int, error)) *MockAwardRepository_GetTeamTotalAwards_Call {
	_c.Call.Return(run)
	return _c
}
