package apperr

import "errors"

var (
	ErrTeamNotFound            = errors.New("team not found")
	ErrTeamAlreadyExists       = errors.New("team already exists")
	ErrUserAlreadyInTeam       = errors.New("user already in team")
	ErrTeamFull                = errors.New("team is full")
	ErrMaxTeamsReached         = errors.New("maximum number of teams reached")
	ErrNotCaptain              = errors.New("only captain can perform this action")
	ErrCaptainCannotLeave      = errors.New("captain must transfer captainship before leaving the team")
	ErrCannotLeaveAsOnlyMember = errors.New("cannot leave team as only member, delete team instead")
	ErrTeamBelowMinSize        = errors.New("team does not meet minimum size requirement")
	ErrNewCaptainNotInTeam     = errors.New("new captain must be a member of the team")
	ErrCannotTransferToSelf    = errors.New("cannot transfer captainship to yourself")
	ErrNoTeamSelected          = errors.New("user has not selected a participation mode")
	ErrSoloModeNotAllowed      = errors.New("solo mode is not allowed for this competition")
	ErrTeamsNotAllowed         = errors.New("team mode is not allowed for this competition")
	ErrTeamModeRequired        = errors.New("this competition requires team participation")
	ErrSoloModeRequired        = errors.New("this competition requires solo participation")
	ErrConfirmationRequired    = errors.New("confirmation required for this action")
	ErrRosterFrozen            = errors.New("team roster is frozen")
	ErrEmailNotVerified        = errors.New("email verification required")
	ErrTeamBanned              = errors.New("team is banned")
	ErrUserWasInBannedTeam     = errors.New("user was member of a banned team and cannot create or join a team")
	ErrInviteExpired           = errors.New("invite token has expired")
	ErrTeamConflict            = errors.New("team conflict")
	ErrCannotAddToSoloTeam     = errors.New("cannot add members to a solo team")
	ErrTeamMemberNotFound      = errors.New("team member not found")
	ErrCannotKickSelf          = errors.New("cannot kick yourself from the team")
	ErrCannotKickCaptain       = errors.New("cannot kick the team captain")
	ErrUserNotInTeam           = errors.New("user must be in a team")
	ErrCannotLeaveSoloTeam     = errors.New("cannot leave solo team in solo-only competition")
	ErrCannotDisbandSoloTeam   = errors.New("cannot disband solo team in solo-only competition")
)
