all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/cache:
    interfaces:
      TeamBracketIDGetter:
        config:
          dir: "internal/cache/mock"
          filename: "TeamBracketIDGetter.go"
          pkgname: "mock"
          structname: "MockTeamBracketIDGetter"
