all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      FieldRepository:
        config:
          dir: "internal/usecase/settings/mocks"
          filename: "FieldRepository.go"
          pkgname: "mocks"
          structname: "MockFieldRepository"
      
      SettingsRepository:
        config:
          dir: "internal/usecase/competition/mocks"
          filename: "SettingsRepository.go"
          pkgname: "mocks"
          structname: "MockSettingsRepository"
