all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      FieldRepository:
        config:
          dir: "internal/usecase/settings/mock"
          filename: "FieldRepository.go"
          pkgname: "mock"
          structname: "MockFieldRepository"

      SettingsRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "SettingsRepository.go"
          pkgname: "mock"
          structname: "MockSettingsRepository"
