all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/controller/restapi/middleware:
    interfaces:
      APITokenAuther:
        config:
          dir: "internal/controller/restapi/middleware/mock"
          filename: "APITokenAuther.go"
          pkgname: "mock"
          structname: "MockAPITokenAuther"

      UserByIDGetter:
        config:
          dir: "internal/controller/restapi/middleware/mock"
          filename: "UserByIDGetter.go"
          pkgname: "mock"
          structname: "MockUserByIDGetter"

  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      TrackingRepository:
        config:
          dir: "internal/controller/restapi/middleware/mock"
          filename: "TrackingRepository.go"
          pkgname: "mock"
          structname: "MockTrackingRepository"
