all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/skr1ms/CTFBoard/pkg/mailer:
    interfaces:
      Mailer:
        config:
          dir: "pkg/mailer/mocks"
          filename: "Mailer.go"
          pkgname: "mocks"
          structname: "MockMailer"
