all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/pkg/cache:
    interfaces:
      TeamBracketIDGetter:
        config:
          dir: "pkg/cache/mocks"
          filename: "TeamBracketIDGetter.go"
          pkgname: "mocks"
          structname: "MockTeamBracketIDGetter"
      PubSubStore:
        config:
          dir: "pkg/cache/mocks"
          filename: "PubSubStore.go"
          pkgname: "mocks"
          structname: "MockPubSubStore"
