all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      TeamRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "TeamRepository.go"
          pkgname: "mock"
          structname: "MockTeamRepository"

      UserRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "UserRepository.go"
          pkgname: "mock"
          structname: "MockUserRepository"

      CompetitionRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "CompetitionRepository.go"
          pkgname: "mock"
          structname: "MockCompetitionRepository"

      AwardRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "AwardRepository.go"
          pkgname: "mock"
          structname: "MockAwardRepository"

      SettingsRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "SettingsRepository.go"
          pkgname: "mock"
          structname: "MockSettingsRepository"

      SolveRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "SolveRepository.go"
          pkgname: "mock"
          structname: "MockSolveRepository"

      ChallengeRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "ChallengeRepository.go"
          pkgname: "mock"
          structname: "MockChallengeRepository"

      SubmissionRepository:
        config:
          dir: "internal/usecase/team/mock"
          filename: "SubmissionRepository.go"
          pkgname: "mock"
          structname: "MockSubmissionRepository"

      TransactionManager:
        config:
          dir: "internal/usecase/team/mock"
          filename: "TransactionManager.go"
          pkgname: "mock"
          structname: "MockTransactionManager"
