all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      UserRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "UserRepository.go"
          pkgname: "mock"
          structname: "MockUserRepository"

      TeamRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "TeamRepository.go"
          pkgname: "mock"
          structname: "MockTeamRepository"

      SolveRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "SolveRepository.go"
          pkgname: "mock"
          structname: "MockSolveRepository"

      VerificationTokenRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "VerificationTokenRepository.go"
          pkgname: "mock"
          structname: "MockVerificationTokenRepository"

      APITokenRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "APITokenRepository.go"
          pkgname: "mock"
          structname: "MockAPITokenRepository"

      OAuthAccountRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "OAuthAccountRepository.go"
          pkgname: "mock"
          structname: "MockOAuthAccountRepository"

      SettingsRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "SettingsRepository.go"
          pkgname: "mock"
          structname: "MockSettingsRepository"

      TransactionManager:
        config:
          dir: "internal/usecase/user/mock"
          filename: "TransactionManager.go"
          pkgname: "mock"
          structname: "MockTransactionManager"

      TrackingRepository:
        config:
          dir: "internal/usecase/user/mock"
          filename: "TrackingRepository.go"
          pkgname: "mock"
          structname: "MockTrackingRepository"

  github.com/TakuyaYagam1/AstroCTFb/internal/repo/webapi:
    interfaces:
      OAuthProviderAPI:
        config:
          dir: "internal/usecase/user/mock"
          filename: "OAuthProviderAPI.go"
          pkgname: "mock"
          structname: "MockOAuthProviderAPI"
