all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      CompetitionRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "CompetitionRepository.go"
          pkgname: "mock"
          structname: "MockCompetitionRepository"

      AuditLogRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "AuditLogRepository.go"
          pkgname: "mock"
          structname: "MockAuditLogRepository"

      SolveRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "SolveRepository.go"
          pkgname: "mock"
          structname: "MockSolveRepository"

      ChallengeRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "ChallengeRepository.go"
          pkgname: "mock"
          structname: "MockChallengeRepository"

      UserRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "UserRepository.go"
          pkgname: "mock"
          structname: "MockUserRepository"

      StatisticsRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "StatisticsRepository.go"
          pkgname: "mock"
          structname: "MockStatisticsRepository"

      BracketRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "BracketRepository.go"
          pkgname: "mock"
          structname: "MockBracketRepository"

      CompetitionParamRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "CompetitionParamRepo.go"
          pkgname: "mock"
          structname: "MockCompetitionParamRepo"

      SubmissionRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "SubmissionRepository.go"
          pkgname: "mock"
          structname: "MockSubmissionRepository"

      TeamRepository:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "TeamRepository.go"
          pkgname: "mock"
          structname: "MockTeamRepository"

      TransactionManager:
        config:
          dir: "internal/usecase/competition/mock"
          filename: "TransactionManager.go"
          pkgname: "mock"
          structname: "MockTransactionManager"
