all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      UserRepository:
        config:
          dir: "pkg/seed/mocks"
          filename: "UserRepository.go"
          pkgname: "mocks"
          structname: "MockUserRepository"