all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      ChallengeRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "ChallengeRepository.go"
          pkgname: "mock"
          structname: "MockChallengeRepository"

      SolveRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "SolveRepository.go"
          pkgname: "mock"
          structname: "MockSolveRepository"

      TeamRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "TeamRepository.go"
          pkgname: "mock"
          structname: "MockTeamRepository"

      FileRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "FileRepository.go"
          pkgname: "mock"
          structname: "MockFileRepository"

      HintRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "HintRepository.go"
          pkgname: "mock"
          structname: "MockHintRepository"

      AwardRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "AwardRepository.go"
          pkgname: "mock"
          structname: "MockAwardRepository"

      CompetitionRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "CompetitionRepository.go"
          pkgname: "mock"
          structname: "MockCompetitionRepository"

      AuditLogRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "AuditLogRepository.go"
          pkgname: "mock"
          structname: "MockAuditLogRepository"

      TagRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "TagRepository.go"
          pkgname: "mock"
          structname: "MockTagRepository"

      TopicRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "TopicRepository.go"
          pkgname: "mock"
          structname: "MockTopicRepository"

      CommentRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "CommentRepository.go"
          pkgname: "mock"
          structname: "MockCommentRepository"

      TransactionManager:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "TransactionManager.go"
          pkgname: "mock"
          structname: "MockTransactionManager"
      
      RatingRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "RatingRepository.go"
          pkgname: "mock"
          structname: "MockRatingRepository"

      UserRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "UserRepository.go"
          pkgname: "mock"
          structname: "MockUserRepository"

      SubmissionRepository:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "SubmissionRepository.go"
          pkgname: "mock"
          structname: "MockSubmissionRepository"

  github.com/TakuyaYagam1/AstroCTFb/internal/usecase/challenge:
    interfaces:
      FileStorage:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "FileStorage.go"
          pkgname: "mock"
          structname: "MockFileStorage"

  github.com/TakuyaYagam1/AstroCTFb/pkg/crypto:
    interfaces:
      Service:
        config:
          dir: "internal/usecase/challenge/mock"
          filename: "CryptoService.go"
          pkgname: "mock"
          structname: "MockCryptoService"
