all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      CompetitionRepository:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "CompetitionRepository.go"
          pkgname: "mock"
          structname: "MockCompetitionRepository"

      ChallengeRepository:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "ChallengeRepository.go"
          pkgname: "mock"
          structname: "MockChallengeRepository"

      UserRepository:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "UserRepository.go"
          pkgname: "mock"
          structname: "MockUserRepository"

      BackupRepository:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "BackupRepository.go"
          pkgname: "mock"
          structname: "MockBackupRepository"

      TransactionManager:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "TransactionManager.go"
          pkgname: "mock"
          structname: "MockTransactionManager"

  github.com/TakuyaYagam1/AstroCTFb/internal/usecase/backup:
    interfaces:
      BackupStorage:
        config:
          dir: "internal/usecase/backup/mock"
          filename: "BackupStorage.go"
          pkgname: "mock"
          structname: "MockBackupStorage"
          
