all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/TakuyaYagam1/AstroCTFb/internal/repo:
    interfaces:
      NotificationRepository:
        config:
          dir: "internal/usecase/notification/mock"
          filename: "NotificationRepository.go"
          pkgname: "mock"
          structname: "MockNotificationRepository"
