// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create award
	// (POST /admin/awards)
	PostAdminAwards(w http.ResponseWriter, r *http.Request)
	// Get awards by team
	// (GET /admin/awards/team/{teamID})
	GetAdminAwardsTeamTeamID(w http.ResponseWriter, r *http.Request, teamID string)
	// Create challenge
	// (POST /admin/challenges)
	PostAdminChallenges(w http.ResponseWriter, r *http.Request)
	// Delete challenge
	// (DELETE /admin/challenges/{ID})
	DeleteAdminChallengesID(w http.ResponseWriter, r *http.Request, id string)
	// Update challenge
	// (PUT /admin/challenges/{ID})
	PutAdminChallengesID(w http.ResponseWriter, r *http.Request, id string)
	// Upload file to challenge
	// (POST /admin/challenges/{challengeID}/files)
	PostAdminChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request, challengeID string)
	// Create hint
	// (POST /admin/challenges/{challengeID}/hints)
	PostAdminChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request, challengeID string)
	// Delete file
	// (DELETE /admin/files/{ID})
	DeleteAdminFilesID(w http.ResponseWriter, r *http.Request, id string)
	// Delete hint
	// (DELETE /admin/hints/{ID})
	DeleteAdminHintsID(w http.ResponseWriter, r *http.Request, id string)
	// Update hint
	// (PUT /admin/hints/{ID})
	PutAdminHintsID(w http.ResponseWriter, r *http.Request, id string)
	// Request password reset
	// (POST /auth/forgot-password)
	PostAuthForgotPassword(w http.ResponseWriter, r *http.Request)
	// User login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Get current user info
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Register new user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Resend verification email
	// (POST /auth/resend-verification)
	PostAuthResendVerification(w http.ResponseWriter, r *http.Request)
	// Reset password
	// (POST /auth/reset-password)
	PostAuthResetPassword(w http.ResponseWriter, r *http.Request)
	// Verify email
	// (GET /auth/verify-email)
	GetAuthVerifyEmail(w http.ResponseWriter, r *http.Request, params GetAuthVerifyEmailParams)
	// Get challenges list
	// (GET /challenges)
	GetChallenges(w http.ResponseWriter, r *http.Request)
	// Get first blood
	// (GET /challenges/{ID}/first-blood)
	GetChallengesIDFirstBlood(w http.ResponseWriter, r *http.Request, id string)
	// Submit flag
	// (POST /challenges/{ID}/submit)
	PostChallengesIDSubmit(w http.ResponseWriter, r *http.Request, id string)
	// Get challenge files
	// (GET /challenges/{challengeID}/files)
	GetChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request, challengeID string, params GetChallengesChallengeIDFilesParams)
	// Get hints for challenge
	// (GET /challenges/{challengeID}/hints)
	GetChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request, challengeID string)
	// Unlock hint
	// (POST /challenges/{challengeID}/hints/{hintID}/unlock)
	PostChallengesChallengeIDHintsHintIDUnlock(w http.ResponseWriter, r *http.Request, challengeID string, hintID string)
	// Get download URL
	// (GET /files/{ID}/download)
	GetFilesIDDownload(w http.ResponseWriter, r *http.Request, id string)
	// Get scoreboard
	// (GET /scoreboard)
	GetScoreboard(w http.ResponseWriter, r *http.Request)
	// Get challenge statistics
	// (GET /statistics/challenges)
	GetStatisticsChallenges(w http.ResponseWriter, r *http.Request)
	// Get general statistics
	// (GET /statistics/general)
	GetStatisticsGeneral(w http.ResponseWriter, r *http.Request)
	// Get scoreboard history
	// (GET /statistics/scoreboard)
	GetStatisticsScoreboard(w http.ResponseWriter, r *http.Request)
	// Create team
	// (POST /teams)
	PostTeams(w http.ResponseWriter, r *http.Request)
	// Join team
	// (POST /teams/join)
	PostTeamsJoin(w http.ResponseWriter, r *http.Request)
	// Leave team
	// (POST /teams/leave)
	PostTeamsLeave(w http.ResponseWriter, r *http.Request)
	// Disband team
	// (DELETE /teams/me)
	DeleteTeamsMe(w http.ResponseWriter, r *http.Request)
	// Kick member
	// (DELETE /teams/members/{ID})
	DeleteTeamsMembersID(w http.ResponseWriter, r *http.Request, id string)
	// Get my team
	// (GET /teams/my)
	GetTeamsMy(w http.ResponseWriter, r *http.Request)
	// Create solo team
	// (POST /teams/solo)
	PostTeamsSolo(w http.ResponseWriter, r *http.Request)
	// Transfer captainship
	// (POST /teams/transfer-captain)
	PostTeamsTransferCaptain(w http.ResponseWriter, r *http.Request)
	// Get team by ID
	// (GET /teams/{ID})
	GetTeamsID(w http.ResponseWriter, r *http.Request, id string)
	// Get user profile
	// (GET /users/{ID})
	GetUsersID(w http.ResponseWriter, r *http.Request, id string)
	// WebSocket connection
	// (GET /ws)
	GetWs(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create award
// (POST /admin/awards)
func (_ Unimplemented) PostAdminAwards(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get awards by team
// (GET /admin/awards/team/{teamID})
func (_ Unimplemented) GetAdminAwardsTeamTeamID(w http.ResponseWriter, r *http.Request, teamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create challenge
// (POST /admin/challenges)
func (_ Unimplemented) PostAdminChallenges(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete challenge
// (DELETE /admin/challenges/{ID})
func (_ Unimplemented) DeleteAdminChallengesID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update challenge
// (PUT /admin/challenges/{ID})
func (_ Unimplemented) PutAdminChallengesID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload file to challenge
// (POST /admin/challenges/{challengeID}/files)
func (_ Unimplemented) PostAdminChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request, challengeID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create hint
// (POST /admin/challenges/{challengeID}/hints)
func (_ Unimplemented) PostAdminChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request, challengeID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete file
// (DELETE /admin/files/{ID})
func (_ Unimplemented) DeleteAdminFilesID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete hint
// (DELETE /admin/hints/{ID})
func (_ Unimplemented) DeleteAdminHintsID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update hint
// (PUT /admin/hints/{ID})
func (_ Unimplemented) PutAdminHintsID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request password reset
// (POST /auth/forgot-password)
func (_ Unimplemented) PostAuthForgotPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user info
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register new user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resend verification email
// (POST /auth/resend-verification)
func (_ Unimplemented) PostAuthResendVerification(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset password
// (POST /auth/reset-password)
func (_ Unimplemented) PostAuthResetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify email
// (GET /auth/verify-email)
func (_ Unimplemented) GetAuthVerifyEmail(w http.ResponseWriter, r *http.Request, params GetAuthVerifyEmailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get challenges list
// (GET /challenges)
func (_ Unimplemented) GetChallenges(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get first blood
// (GET /challenges/{ID}/first-blood)
func (_ Unimplemented) GetChallengesIDFirstBlood(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit flag
// (POST /challenges/{ID}/submit)
func (_ Unimplemented) PostChallengesIDSubmit(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get challenge files
// (GET /challenges/{challengeID}/files)
func (_ Unimplemented) GetChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request, challengeID string, params GetChallengesChallengeIDFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get hints for challenge
// (GET /challenges/{challengeID}/hints)
func (_ Unimplemented) GetChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request, challengeID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unlock hint
// (POST /challenges/{challengeID}/hints/{hintID}/unlock)
func (_ Unimplemented) PostChallengesChallengeIDHintsHintIDUnlock(w http.ResponseWriter, r *http.Request, challengeID string, hintID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get download URL
// (GET /files/{ID}/download)
func (_ Unimplemented) GetFilesIDDownload(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get scoreboard
// (GET /scoreboard)
func (_ Unimplemented) GetScoreboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get challenge statistics
// (GET /statistics/challenges)
func (_ Unimplemented) GetStatisticsChallenges(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get general statistics
// (GET /statistics/general)
func (_ Unimplemented) GetStatisticsGeneral(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get scoreboard history
// (GET /statistics/scoreboard)
func (_ Unimplemented) GetStatisticsScoreboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create team
// (POST /teams)
func (_ Unimplemented) PostTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join team
// (POST /teams/join)
func (_ Unimplemented) PostTeamsJoin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Leave team
// (POST /teams/leave)
func (_ Unimplemented) PostTeamsLeave(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disband team
// (DELETE /teams/me)
func (_ Unimplemented) DeleteTeamsMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Kick member
// (DELETE /teams/members/{ID})
func (_ Unimplemented) DeleteTeamsMembersID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get my team
// (GET /teams/my)
func (_ Unimplemented) GetTeamsMy(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create solo team
// (POST /teams/solo)
func (_ Unimplemented) PostTeamsSolo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transfer captainship
// (POST /teams/transfer-captain)
func (_ Unimplemented) PostTeamsTransferCaptain(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get team by ID
// (GET /teams/{ID})
func (_ Unimplemented) GetTeamsID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user profile
// (GET /users/{ID})
func (_ Unimplemented) GetUsersID(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WebSocket connection
// (GET /ws)
func (_ Unimplemented) GetWs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminAwards operation middleware
func (siw *ServerInterfaceWrapper) PostAdminAwards(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminAwards(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminAwardsTeamTeamID operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAwardsTeamTeamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "teamID" -------------
	var teamID string

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", chi.URLParam(r, "teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "teamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminAwardsTeamTeamID(w, r, teamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminChallenges operation middleware
func (siw *ServerInterfaceWrapper) PostAdminChallenges(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminChallenges(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminChallengesID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminChallengesID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminChallengesID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAdminChallengesID operation middleware
func (siw *ServerInterfaceWrapper) PutAdminChallengesID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminChallengesID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminChallengesChallengeIDFiles operation middleware
func (siw *ServerInterfaceWrapper) PostAdminChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "challengeID" -------------
	var challengeID string

	err = runtime.BindStyledParameterWithOptions("simple", "challengeID", chi.URLParam(r, "challengeID"), &challengeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminChallengesChallengeIDFiles(w, r, challengeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminChallengesChallengeIDHints operation middleware
func (siw *ServerInterfaceWrapper) PostAdminChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "challengeID" -------------
	var challengeID string

	err = runtime.BindStyledParameterWithOptions("simple", "challengeID", chi.URLParam(r, "challengeID"), &challengeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminChallengesChallengeIDHints(w, r, challengeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminFilesID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminFilesID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminFilesID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminHintsID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminHintsID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminHintsID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAdminHintsID operation middleware
func (siw *ServerInterfaceWrapper) PutAdminHintsID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminHintsID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) PostAuthForgotPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthForgotPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthResendVerification operation middleware
func (siw *ServerInterfaceWrapper) PostAuthResendVerification(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthResendVerification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthResetPassword operation middleware
func (siw *ServerInterfaceWrapper) PostAuthResetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthResetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthVerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) GetAuthVerifyEmail(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthVerifyEmailParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthVerifyEmail(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallenges operation middleware
func (siw *ServerInterfaceWrapper) GetChallenges(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallenges(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallengesIDFirstBlood operation middleware
func (siw *ServerInterfaceWrapper) GetChallengesIDFirstBlood(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallengesIDFirstBlood(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChallengesIDSubmit operation middleware
func (siw *ServerInterfaceWrapper) PostChallengesIDSubmit(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChallengesIDSubmit(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallengesChallengeIDFiles operation middleware
func (siw *ServerInterfaceWrapper) GetChallengesChallengeIDFiles(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "challengeID" -------------
	var challengeID string

	err = runtime.BindStyledParameterWithOptions("simple", "challengeID", chi.URLParam(r, "challengeID"), &challengeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChallengesChallengeIDFilesParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallengesChallengeIDFiles(w, r, challengeID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallengesChallengeIDHints operation middleware
func (siw *ServerInterfaceWrapper) GetChallengesChallengeIDHints(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "challengeID" -------------
	var challengeID string

	err = runtime.BindStyledParameterWithOptions("simple", "challengeID", chi.URLParam(r, "challengeID"), &challengeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallengesChallengeIDHints(w, r, challengeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChallengesChallengeIDHintsHintIDUnlock operation middleware
func (siw *ServerInterfaceWrapper) PostChallengesChallengeIDHintsHintIDUnlock(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "challengeID" -------------
	var challengeID string

	err = runtime.BindStyledParameterWithOptions("simple", "challengeID", chi.URLParam(r, "challengeID"), &challengeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeID", Err: err})
		return
	}

	// ------------- Path parameter "hintID" -------------
	var hintID string

	err = runtime.BindStyledParameterWithOptions("simple", "hintID", chi.URLParam(r, "hintID"), &hintID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hintID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChallengesChallengeIDHintsHintIDUnlock(w, r, challengeID, hintID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFilesIDDownload operation middleware
func (siw *ServerInterfaceWrapper) GetFilesIDDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFilesIDDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScoreboard operation middleware
func (siw *ServerInterfaceWrapper) GetScoreboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScoreboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatisticsChallenges operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsChallenges(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatisticsChallenges(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatisticsGeneral operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsGeneral(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatisticsGeneral(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatisticsScoreboard operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsScoreboard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatisticsScoreboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeams operation middleware
func (siw *ServerInterfaceWrapper) PostTeams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamsJoin operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsJoin(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamsJoin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamsLeave operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsLeave(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamsLeave(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeamsMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamsMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeamsMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeamsMembersID operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamsMembersID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeamsMembersID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamsMy operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsMy(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamsMy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamsSolo operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsSolo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamsSolo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamsTransferCaptain operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsTransferCaptain(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamsTransferCaptain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamsID operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamsID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersID operation middleware
func (siw *ServerInterfaceWrapper) GetUsersID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ID" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "ID", chi.URLParam(r, "ID"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWs operation middleware
func (siw *ServerInterfaceWrapper) GetWs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/awards", wrapper.PostAdminAwards)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/awards/team/{teamID}", wrapper.GetAdminAwardsTeamTeamID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/challenges", wrapper.PostAdminChallenges)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/challenges/{ID}", wrapper.DeleteAdminChallengesID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/challenges/{ID}", wrapper.PutAdminChallengesID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/challenges/{challengeID}/files", wrapper.PostAdminChallengesChallengeIDFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/challenges/{challengeID}/hints", wrapper.PostAdminChallengesChallengeIDHints)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/files/{ID}", wrapper.DeleteAdminFilesID)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/hints/{ID}", wrapper.DeleteAdminHintsID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/hints/{ID}", wrapper.PutAdminHintsID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/forgot-password", wrapper.PostAuthForgotPassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/resend-verification", wrapper.PostAuthResendVerification)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/reset-password", wrapper.PostAuthResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/verify-email", wrapper.GetAuthVerifyEmail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/challenges", wrapper.GetChallenges)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/challenges/{ID}/first-blood", wrapper.GetChallengesIDFirstBlood)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/challenges/{ID}/submit", wrapper.PostChallengesIDSubmit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/challenges/{challengeID}/files", wrapper.GetChallengesChallengeIDFiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/challenges/{challengeID}/hints", wrapper.GetChallengesChallengeIDHints)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/challenges/{challengeID}/hints/{hintID}/unlock", wrapper.PostChallengesChallengeIDHintsHintIDUnlock)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{ID}/download", wrapper.GetFilesIDDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scoreboard", wrapper.GetScoreboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/statistics/challenges", wrapper.GetStatisticsChallenges)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/statistics/general", wrapper.GetStatisticsGeneral)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/statistics/scoreboard", wrapper.GetStatisticsScoreboard)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams", wrapper.PostTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams/join", wrapper.PostTeamsJoin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams/leave", wrapper.PostTeamsLeave)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/teams/me", wrapper.DeleteTeamsMe)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/teams/members/{ID}", wrapper.DeleteTeamsMembersID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams/my", wrapper.GetTeamsMy)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams/solo", wrapper.PostTeamsSolo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams/transfer-captain", wrapper.PostTeamsTransferCaptain)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams/{ID}", wrapper.GetTeamsID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{ID}", wrapper.GetUsersID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ws", wrapper.GetWs)
	})

	return r
}
