// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9e3PbuN0w+lVw1HfmsZ9XtmVvst16p3NO4tzc5uLHdrpn2uTVQiQkoaYAFgBtazM5",
	"n/0MfgBJUOJVomTZ4T/txgJx/d2v33oen4WcEaZk7/RbT3pTMsPwny8uzq/5DWFngmBF/EsiQ84k0T+F",
	"godEKEpgoGcGDLHS/1LzkPROe1IJyia97/2eT6QnaKgoZ7m/k/uQCiLt52MuZvq/ej5W5EDRGen1l7+h",
	"fu5USu9X/5JZs3cRYMoUuVcIBqA9OeV3DHHmkf3l2b/3e4L8J6KC+L3Tf9k5vybD+OjfxFN6tfiCHsPN",
	"BFiqYSSTvdSZ7Hvemf0ZZS98/wOZjYi4JP+JiFTLB48kEUOzlWSlKKL+0iL93v0BxyE98LhPJoQdkHsl",
	"8IHCE5jnFgdU77B3mrxJH+b5vvhM8YpfizZtwPgqGs2olJSzwr17UxwEhE1IrQPoKw9zr5zKoceF0HtI",
	"fx5xHhDM9O9Sb0Vp8BgHeKLHzPD9e8Imato7PRkMWriqGb7/68lgYJ6S4FndE9V+vqJX6Gdvcemwmdup",
	"eLLPsgTQyAzTAP7jHs/CQE+i9/D/2H8eenzWBsx5kVR8NjSr6UOHWMo7Lvzs0vFfj09+amNVqQRnk2Gy",
	"Ftw2D8jyeddYjc+oIrNQzfucET7+q54OYX39sJ7+J8OzhTUZuVtz2cWrTdbJxWz4pW9f27n9QtC5JJKo",
	"QqjBnscjy/GyrAK+Q3pJiTDzkcYamR7TQd8EwAtnSUf00ZQyJftoTAOSPx3jio6ph/UMhTNmB+VNE+KS",
	"DZkf+0W0CMhi4cfOELgZyYPb3NkK2cY1wbP3VKpifuljhfX/a4iEP/wvQca9096fjlIp5ciKKEfJnMl8",
	"6cpYCDzX/54RM2PZRBd4Qhnc6Qc9uvwAxZvHt1hhMYxEkMsORpixRuw3+UQQLAskhJHA3g1RwwKu7+FQ",
	"YcoKf86IJ2vJF1QOzW7zeR2Vwyn1fcIKf5Y84Pk/zkDUGALGOiO0RDchAnDH0qe68svn0K8nCvhUetgQ",
	"+SxKfMDixsEIhCWyY4mP9oB6Ik8fIAr3D9GnWyIE9YlEKdc7zMXDcplhgTDWYaHmqAZwCw6ZhaFK2SAL",
	"U9XCUfnLx083oywWfY7b4GUg7aT8pOxy6skX629pSYagcnhLBB3TIqxxhYz11y+TJrYgPLR2gVlJoehl",
	"JRHqigeRKhX1OVPEUJVl/Pa1jngnqCJRiOKRfVdIf37y7OSXX1qS081ky+JPvHIxiksi2marBie2xFYz",
	"i+0EW12FMRZQinVYZjl1yMfdrKaXq9k1YZfjMfEU8V9ZCFp4mjssfDlUXOEgnzNrsXcYsYB7N2UMPOTU",
	"SuPLv4GcWfxx7q7D8IooRdlElsBVGA4LbqLf87iQQy7ohDKZP0DeDsl9yIUazvD9UPC7gu37ZIyjQA1D",
	"IoZa/s4fNRaA5X4hmOtFyqfQI4y2kkPN7uksmiEWaUkK8bFRaxAOAn6nBZYB+iuKWEA1qfUdk5gzPceR",
	"mg4nVE2j0ZAwPApIjlz0Qs9o1SfFkaQThihDtxSjt1S9i0bo04tITXNlH7sC55OArLYCfFqygsCKDOGU",
	"Q4/PZoSZZ5lRFqmCW3U+GXMx4Srhn00+nRBGBA6GNGzyVcAnlDX8gEeNzmTu3MNBMMLeTfMvBfGpFkCb",
	"fCnIWBA5bfbJhEqlwb/JN5Ks9lrS44KMOG72FRDruRHvqr+DAwngjkMeFknH+gzMd5GhcMxYJLJlHv1w",
	"RxVSPXNlSgXDKY9EET1Ob+eWSjoqYELG4Gfvxo/sUbVgmD+rO1zfHpiXcodGILUXGtXdd5D5V2aHVBzU",
	"in7FpOi3KVFTImIZUR5JK29KhAVBxsmgeExsx4oIsJpQNkE4tQ7VNaGAHPQ5DDgu8cWMoyCImciCE0QQ",
	"TSyJjz5fvkdjLpAeeyDpHwQZGQvtPT8+uX9+fIJ+I6MLzQZS7U7QPJlHTaPZqO5yMJhhGiTLHZ/8cn98",
	"8kvN5Rbk4uSk7jZyhWQtpdT10dST9eJvRnP9DYuCAAMeKBGRfnM/T5E3q0SOu8VBROrKQy+xdxOFZTJc",
	"fe0gc5k5mkHWLFprzrP4k9cgUOXOymchUTS+wdLZnKHGh8ZFCbkwFtm6W31Dg9xTW2No3Wmu9PC8eRIB",
	"rtY01wTPiu8MZKTac2klrHiuWyJkPvTmwxt7EYYEB+VqKYYx9beYTLsNzXR5seX9a+VVyxnJ7xWKZA5h",
	"8Gh8r1nyGRLmUzbpI0EAtvw+4gIJ8m9QxxoYZmdEyqzO4PL7W0ruirfnuAHrvfqVwiqSOSZGV0nPsSiy",
	"oYGFfHY9xXJo76N0XIVCXajvFxym3GiK2dAYpq2+BVpe73SMA0kWKH7vfIyAM6ARZohgbwoiATLfIywR",
	"BoUG7akpmSMPM8YVMqBz9G9OmZUguEAhFop6NMSKaK1H8oDv51uS09OmXrt/UB4A2GsVUETGFeXaswaD",
	"fkuW2NS0Rdlfj42BCxzRC1zcbvNr/hOUmmZXPuGDnkl50yuizjgb08m5IrMcgQQrMuFivkwUOPwHDlA8",
	"BOQqxtmB1Sfm6IbMZa9aBGnrSlLjbHob/d4Nma9j8U3u8rsr6DhbPh4MWguPgLnSlYZmUgej0/kJi2b6",
	"fZM/UDAIa6Tr9Xv/zr752qZ0MwGiTCG9AoL5l2BNX3V8SdUAV2YIH9NJE1a8BMfGBHVuvn4+WODMa2JZ",
	"36e3JNc2DtvOPblxa7Ur+K8oyVM5TOCpzAtWgzGdXf3jfKbFtEsi7XwLHish+ILct6xZLAhNdGaF5BIb",
	"rbyhYVgxJPI8ImWB63L5KLHc/4ooTEsELZci5phqGSMeWBcoG/OVAu2aKwExyC/e5JgKqYajgHO/ehoh",
	"1Us90pVnp7ElvNZW3lGmirZSJBDi+yFWQGpksSU5HjG8o8znd83N9iGXdOG+6xv17QCtYA8zmOGGrChs",
	"rGsxWY6tUfoOweHc7wXcuyH+MlXWt4UbkLtrPCnTORRVQW38zQK9lphlQ4hvAGPJaqBxvmZKlIFGSIRH",
	"mMITMjT374wyvoM1nTWNFeWC/dd9gH4PfFOpX6SOtWTRHPEA5CjAk+EUy2nur80pRKvUYQ2kXxNjV8Gy",
	"NwEucwLCTRvWPxRkQu6XJM2TZ/2CB0rG5/6c44Z7h+WUSK2ZJEYyBEPRnlb4wjhKff9XrQ76INybUCLj",
	"CDZxf1rurM/Y5dDDkgwpk4Tpt7klhbrz4nnq8e5LI47NCCsTtZJg4HLcWYi8LhmwEjA8oITxBJjx02TD",
	"cYyQ4S0PCLl9NxppYxJqrbuog8hF59yBM8SCwtLurVDZROEr88GkMYbNYe6WXCTCVkNyVCm85UptlUi+",
	"GRlqFfm26IDryJ2NaIOJDdkQFrQYdJ31hNebqtim3zg47CzrlFswQzB/CHvIpQSCkD9I8e+Z/TmvSOUw",
	"xFo2KogU537+fIURD1JhoYr2UXHmEsdQEPA7QJihvKPKm+Zvt/yKKkTMzdyg/jkaBdTL//mGkNANjxkL",
	"/gdhQwhtGBJW9Cw2Mm0o6R9FwWuUVQ5p/LjmoEVep9KnN3JNJJtDhXGBFcPGWnix4v3vyM25aUZDG3tY",
	"W98AS++ZZRsFjpNVMkRcc7LNMjPzfC3cxQVgiPvE2Pepcc1cODsy0SALYTHwLTKGa4SlVgAVuiHzA7Dh",
	"oxkOf0XwnyaISG/BR3tmw30bwdlH9q5c39/iLldUdqoUmVzfzoq8aDGIZeGXxBdT/mquCyTzZeEL6r3Z",
	"tAAzyRIBt2HPwzhyvjQkxo2RrvAz13QTmsTXNL+8KD2p0Kl38vx5W069k+fPYevNk9G/F5/MRlYUnKsw",
	"ZmFVL9IgzoTO8dbGi5W8g4l5avwIz1tzUj5fzuFuK43e9bBSRmdaiR8sBYDXn1/fd84txztPEdW9t+K7",
	"T7x42739fL921o23GPNRkty2ubz+PA5WfJsZq12+I9jhDWlYxW9k1Eqq97Ix5Xu+fS3LNM+SAUgPQHvk",
	"cHKIrq7e9dHny/f7NrqUZEJq083n+3E9nD3jiQl9WR8BHNCxqLDEVNO9JQ+C3CGtXrU78XerWCxs4vrN",
	"N+NyIIJ8b3d1WC1edsnSnn3mT3F4C/xuQpQDPEHmK2QX0lBgHpzK9MV/RTxJsnWCRVGMpC5A/J+z6zdf",
	"vnz7Fz7448XBPwcHfxl+/d9fvnz/X9lQoTzT/6oERM9lKAijiuJgmNDcZFdx7NVmALDAD5CsXkjCXL9A",
	"9ehFc/ZSGlImZ9oORCERJiBuOQ8pWXKTl1NgYl8ogsCDgLIJMr9D8B3xOPMlAKM7BfI4DyB5FM4TEjHD",
	"WmJEAfdueKS2dy7KcgDteKOAlhrpNrCgu0zq0Mi+0ysqwwDPERc+EWhPK5kC/RWBz3xrN584RRb4WELt",
	"wUlCA6rmppYGZL+gkAfUmzuRZqW+lJSgpcPaCj6zMyKzLLKLfjcOmyH1c7D7Gk/Q+SuZy4zrOywTO20e",
	"jzxulzeZtZaDymLZJMu3LedMQDzea4m0FduRq7PPsxJiGyIi42roKHG5qk9Zark5whtKgmLVhzBF1TxR",
	"02OojSsDETxbJyAyOYpTWgDmBHFCb2xpZUXuNau3Xo9+T5JAH6ef8Kj2tgPl5GxCrVkGuQasHNH/uM2Y",
	"VVjExAPLIknK4KLdHCzsYGK5ppQJ5nQ33jSac1EOMpGcGa0KKPWQMj+WCa1aNejnJk6mNpsqBSzfuudA",
	"Tj8DwcVY8I7Ww+KUZl1r4ZRKhKHwUxtkCzLp47WM1iTVggS5QY628Ehb4aI5vKAyK7CapH10amg1JM3P",
	"B21adBLJPKRx0kq1SSG5k83WClwKggfFPBVM7D/vsGBmuTj0t2/ij9sMhAeV366E7DrIrLJsZoLr6dcA",
	"gwtcZgUpfP42bUqOVUngcdamlMkkdYskNCGWMogmeUwo1KqK0Izi/2gleHDwl6//e+//Pj1I/rH/3/+r",
	"1x6v6ocQUao3831LIFwAFrCHYpi44gEvzfryjPfA1Bao7bqCuSF2qXDagIssvv3p59GfT34ZtCLST8n9",
	"0CxRIJk8b4+qNTZJrnff6XEc3kvwDL1oA34Xiog1ONVnScSOMZqOc6zNOV7rT0v8qkV+9uIc3CXpxdd7",
	"KHNJvcE0aLHal1sEcfNJ1VadbDMjaxUdtEX9sTg4qzC4wtHa6ttFFvh+uWJUhytBJYMVItvKE9rHNCCF",
	"By8qTc5tYHtuxMgUnzz/Of+nwlCh4riB3Gt4xe9YwLH/+fJ9MWzmF+ZaLFVcUIIkiWVtBeRXueSV7rGi",
	"sItv7w0qvOxxFsxRCHWGFLqbEobIfRhQj6pgjkwBrGxxsfJnWcqNK4/mbS1wt9UIyTdQMuzC1qBqUsQ8",
	"DPCciOMN1zFfAF/z5zwAfmsKmBVF86Z+3YokgtIQXf0qJb/DuzSqA/iO4EBNqwO1UgbAb4rlkEU/rp0e",
	"eVPi3SAB6bi/QgI+RG4lLBJpgJHWae2P+kgQn8o+kooLPCH7fTfe60uP33zpIS7QF7OPL73cGC+zNixd",
	"LgmMsGwhwPEd+AGKynsUF/hdADA78GvuCky1HWltLWQ5UbD5k1Uy2SZR5PpAcSn6jcSRP/jpiqIwd2HP",
	"/Z6pOlpfIDJG3mLZ/vGe6jN806LSkE66DaUhZ7XmmGTN50UPBT8XFW9oXp0tfqU1gyXbL/TQfhGHv3HK",
	"1rXhUHZLFRkm3ZtSMQgfj068n/xnB+T5+OeDP//yl8EBHnn+ARkfn/z07PnP+i+b6ymU2Vce03rPJ5Tt",
	"nlhX1J7miniRIBdpk5r/q4XFi8TIii4tH8g6Jb+HqfRSUTHOyizVqmtx7VSoP+ZcaFYKVCIiRt9RU4Js",
	"Zxk0hapeWrUNUPwtkkShPXDtgGcWChUfgN4UN6TZz+8KkU9l4gLg2f2An1z/ZPtQ9KG22H7T5MaGms4H",
	"Y7IqftPaNrAy41fWpLoSry4HguL6PamTrsQpV0B/a90gQMPre2+KS+NzrY1xwd/PDFtBxH6P9Dg0FnwG",
	"UAlzo7jMM/pPRMQchVjgGVE5XZxyzZJfi/Z8Ifgt9YkoSXoyZcPzL88U/K6hPNhJki/yNnSBJ0QLOlo0",
	"Ld7OqmJZ7E9bqzTFRSmabClz1PU5VjoZW7iIVfKDCi7PlReXrq+4PH558fySFgYm+znpq1XH7nARqTTS",
	"HivKJiVFDG8puSuNhdYDkLVMtxYntpDjk6mBlxP8CocwdgpryDg+eL5vNmSCP547gSDHawSC5JV/WxYx",
	"igvexfe9us7dHpalj9uM9bac1t2oVvSlLbVfzIGMrAkOFFlmU6uwnp3BPAjmiS1ge8YtQ3108CUaDH4i",
	"5of9PAvYjyFd53Ztyu/JaE+/lZ6MsYjv9GYslfZTqFqxVW7j7joN5ddLpyHDNZ2RC55vjyzWm30b8p3B",
	"13pc7RKaM/zDKfL0cv56BiURH63HAJpGVno+GLkb5mPTR3K3PYRKLA91WkH3s7vOP7wm/BVZrlXlw9dm",
	"5m518djBEZcT7+mT2WLi7QVFx7OnhcqXICbZVN69XXlckFcaEekIKhG9jLwbkld+O/l7jjW2gYcIFizA",
	"daizUGSfnRGp8CysSV2ukpINUJmomApCm+6lclv1auCASGFNJ0mvjUIjSpuFjdLjvRU4nOZIuVonrazu",
	"RWfkEgau1AhBfx5QRurVi0q3/I5KxcW8oGRU5YWv5GJuDD9E5RXckyVqRTIoP1tHK8nZSoTnryRSU6zQ",
	"LJIKjQiyqDwiYy7IQrplg5yeovNUFKR+9EXQu8LlpYXLizW4K6KMu7kQONrwN18RpalGVX2B8ua4FZ1/",
	"CkA/Cs+4lnJUiR2oSCIxgm2dZi6pa65AioGJvhZtsap3+jBNYXTlC1s9qt8LBb01AnCSuggCj2xR3DCL",
	"IbtUnKxol9HHNiLW2j18izVBs4ArwTrY/ueTbDeNk7ZaT5zkCrFmL2203C3RA91Klo8BAjw1HpaS/VYT",
	"OpIlt5L+Z1oNurWBh2VRoNmCczVDDbMFyep9tFTvbXMZ7tYbksbv4pkcchbMexBwxuP/HgfkHlKk20wA",
	"jddCyUooWef7YpPHmsiyKdQwaela6F0dbeP/MJe6HSRG7pLfl4rP1SziSmfkD86WMPLkl9YKfJzkde6O",
	"CYEF1ALamfMu/TwuWwxQS7Q/y/mW2FQh068qXuhZuaWG6JUMzV0M+t81t80XBTevHAncrMMZbPsDVoLe",
	"X5oaIa0Ui16UKlcqHl1ao7uy7nFlC0vnEiu329h8oLe3hsemDlSs6nCEvf1G1dS065DbrHFfZnuoAxJt",
	"3cuOBNNfmXjp8jhGM7xBJ04z6Sf4rLS4fJGHuGSrC7PmW/tm3E+a/Nd7jRCraWkmRzINZernZznt3HP3",
	"nGSCPdr0spzVHrag/2rBRmFRyIbHhdBHzSfyaW3dgqijuMu23lJcBW5HUT05C2SclAkkizfiRl+z0p+b",
	"YXSyo2s6I1dExPbh+tup6SCs2HfdzZVEP8WI2xCDnYMX0cdh9YUPVzudehOUJNDXqGnYetbzUo3Dxf7k",
	"+q9fK85TH67dKnv104nNLOUZxdflG7GlCdZMe817WKd9dY79P1SYsoYiX0UHYNNwN3aI1I+ab3imcwgb",
	"L0HAhXD3mtO2yJZNwP7mGXJmnaZh3hUgsCJzXbj7SsWn4dsnXshli/5a3sJ4zno0O/Vq13LH6Y1rHeeD",
	"aWi9TmB+SZtv+2thefRdefFKIkKUHM4oS8ybC3UQRUQQHUPcNVQ1hVQAhQKCpUKZRhe2A7hEe1zoXxCV",
	"iHGFJFEFXb2dluO1u/qXIvpi342Fiq3GcGvOATuO2QtSPK5aaVvYDdCMYGYOQNiYC4/4cIoS629D/EoC",
	"BPK6ahS3qqg7vYaQC0xFrs+LSDnMlsBfPosd1oiwC+zdUDYpCD9opiIocFauEDiKJ0Ux580MZPFp2mRV",
	"mQvaJK8SmMkxEWeGCJWGrGUJ1a6kqy3sLE/W+wyhxS/C8IooRdmkOIIEh2HrXqylYpC2kKGQQy7ohDK5",
	"VJ/o2S/txbg/+8WsJ281JnOhhjN8PxT8TmacVMetOamObRgeBGQM3QyEJGz+eJCpjtzi2kmQiKmXKiCx",
	"xI95t+sEXccxveADPT5JKmo/6HFjF2R+FXLgabZ2Kx8Dd5PINiTKKUK+uaKaOFLToclrGhKmpZKcBMMX",
	"emOQxCeB69IJQ5ShW4rRW6reRSOT3pUrL9gVIGFqtRXg05IVBFZkCJc19Ey9Y3j5GWWRWn77TT++uVdn",
	"T2OowJK4vnZqb6YoTjCk4U5tK+ATynZtRzzaLbgyiBVnVO7g1gTxqSDebt2aIGNB5HTH9mRSU3ZsU5Ls",
	"KNVy2g/u0rYgDGpuIh52YGNupAYP84NV9TCpZTKHMReOGYsk8HDjrd7cJbejAxh4VyoYTnkkZPbVfv5l",
	"k2/28y9pbJQB67idRl501EJM1NqhUIvB0zYWKhMD5QQ/gcXFQrwfWfiaUbZRBSazqkatOAR5Yyu6yCzz",
	"0cIOeUiQuRNUkSgslqt/mxI1JQLZgfJI2gbrptabnPI7pgVuq4CMFRGQdUHZBOFMskWdSjxGt9/hhnk7",
	"3SDP3F7XIG/HGuSZZ/Efuj0eI3fg5v3eSkH2rj1e1x6va4/XtcczCz7v2uN17fFWb48Xc8i4gcEDNsir",
	"0RnPilkpCyp2QAUBv7PO6TuqvGm+COkFBIuhm9lUNGYhl6mV9CjNtRMG0E72FJXDEEeyyBygfzbKaO7P",
	"N4SErolmLPgfhA1BtxhmveQLjGlLGVuLAQcbzw2r35iheWpRM+WivJli19GwoDfGznYqbNyEo7wbYTHg",
	"NO8/GDOFKWUKxSO20oVws/JTURvC40fUhtC8zS63IXzotoNPoVeUeeXd7DK4RsXPrpVgVStB+/CCj2lQ",
	"8vaREBArUVw6oh0I+PNJWiugnRpjpeUQ15++quBhawfIVjcseMdabRufbItGewdl5f1bqzWySrPFz2HA",
	"sf8GEK0o2nRD3bLq5Fhmegn4Padzl50nWSn3cJKIovSYxuUw41rxm6wBrzfcYuRvZex6S4G/y706t1pY",
	"XhC8ybLy+nQJM1o1E2els0GeeYNEw0wVgDzbV7uQuvJtPCCG/SPx8UAr0vwGTKBSrteH1ExRnja4sJfq",
	"tqip+vSPF+/PX724Pv/0cfj68vLTZW5fz+XuNmXQk3czuTSjvU6sUK+3ok5vkgqSNQa7pX4RjEF70KwB",
	"6DoKKLtBXCCPh/ODEEtF9jfSqKWosY1GXuJFgqr5lb5fc5YXIYUUGQgFXo4hvjhH8DPCkZoSpuzxDtEb",
	"4JSn9tdvYYA1j7xXJk/mO5Qj7J32pgT7oKsbfOjpZbigf+CszxeH9O8E3vIlwYKI/N387bdrZLJxzPWm",
	"u/hiv0PfzPJfeituwPgrjTdeMwZs0nXjjy/O0VUUAvdeKn1++frqGukRxjfGNJOaoLPrN65v9vAL+8Iu",
	"sJqmjTokiiRBF1h6ODjDkqC981f91JOg/6GJjf5/TVj0/08pU+evTASAx5mkUhHmzdEdVdO0Kye0C4EF",
	"z/hsxplRfFFcmxh+lmhvxP05ohJlEF4DagEtMKtAKxLMfGSR6VfYzLPBwHVZG3QHzwisMsNzRJkXRPBt",
	"3AxRfukhwGXEx+ibqR3fj+dF3/dPv7ADmPkl9pFFytOlZfqIMvhberM2YuL8I5Cm4Zv3L94O33y6/PDi",
	"uo8WqZU5ld0w7Gb/0Kx7jD4zbKGG+KcIXLlsom8oXlH/bBf7/PHF5+t3ny7P//laPxxgh8kw8+MJf9Jg",
	"OwIn0ymiTEbjMfUoYQoJOpmquKnk56vXl8OPn66H5x+H169ffOijy9f/8/n88vWH1x+vr+CXD6+vDXAc",
	"QX8gk+AYL/MMfeQKveER80/1o/NIePCu4HZmXKGx/q1gNdP8iJkwJnjbIwhoOpqRo/+Ol/gLOuNsHFBP",
	"nSJw/2lohH/bWdNCtDjQItHc1p81oKyx6sgQR4VvCLPTHg/QW86Is2nGUcDZhAiEbzGFRE+7gMkDzb3n",
	"k7+ga87RB8zmMdTIU6QxA4GzHZF7jxCf+IdfwMdIPWI5ncX2D+fXPdsutzdVKpSnR0c8JMxs6pCLyZH9",
	"SB7psalw19NYfxFgpfUJTRN6ENpmynb3jg8HhwPTM5owHNLeae8n+JMpAgNk+QiCBI8wFBs33XZMZewF",
	"mkNUJBikuejXR3a8bRKFOAvm+4foDQ00NozmKK7TjUynrcMebMJEHJ77vdPeW2LaW76wC+stxXSqd/qv",
	"b4aoQquhlKYm1b/7PcO5M0GWhPmGtdWqUv79ez9/Ecg6chdIYtCO89S0gkni9KXciU5yclm/f4WNA+WD",
	"dzgZDBa0BhyGgeWLR/+2WdDp7BWdzMxFZxSs70uxU71Pf9fw8mxw3NrSWfEuZ0mX6JnFf9re4gmBzIgt",
	"AICugPCvr/qhsyLMv77qJ5PRbIbFPK6JrfEjixsge4FY9a8eQHzvq14qi3dH385ffTcdiKyrehH9oI0P",
	"dnBvAfWuiEqRTnGU1NLfw5HiBxEbYbaPgCsbjFhGyQu9touU568K0BJKSCWwDsNSwdDkxafvs4h2X81g",
	"ItVL7s9be+q8pgkLIqve2fdtYFkdDBtsD8gdceaHxW698rPtrZxIROvTlWLcryAtd1j41Rw9sKX8gXLB",
	"J4foRUJZShi3mX6JQCy8QCIRgHgHpCKPX8ZWjhLCoVXWCT+wH0ClnFe9tblmLfMAnLXYuNSx0Y2w0RjA",
	"FkEcAhRzIPoM7IwSYcQ0vujPtdLJIqn5nhaBAzU3uiwGcCwH9AsuFyB9E2zLbNoCmMO1FswjcBiwf1cz",
	"tPaAbgHul/dldu93HO0RIpp5O4MnNRgJaOVH34yF6Ht9tgIf10a6LHeBkliG0Ffwmessd8kKqCqeoqGQ",
	"urNspcO0H0J2RHsgNPmc2LpY91Sq/fUx/y1RMV5awawO/scqqk/iGu4LuQHwd4m0lKq/KEd0M9rB9Woc",
	"N0ywCMnXRvBny0f6yNFZHK3Ywf4j05sMhBXyt36FoRPJkHh0TD0rSY7m6PxVE+b14AA92J4c+APrO48X",
	"QRI2YGC7lAfYRma2qWG19mXH19SwXsazb1LHWkhtr2UbbA+ek9U7ZWpXsfgv21s59ma2psVZfKuFw/Ul",
	"uXpo7IhyMSJv0HPQyWxPX2YrhuYKqc1+2ERY2zbIDrbJUjq57JHKZRlAzreBRzl4YCLua1Pui2hrONC+",
	"VJdbsGjbHt/6KNgJdD8I+j9aUdIgVC1RMgm3q6EQanUwGe/So2J98CydfpMa4VK5ri3rhM76nVb4hF1s",
	"mVJ8NXDqSBAPB95BWu4nH8MuYVgUAJpBuBeCtq8S4qX9OcMz6iEzi/HABUH85wPpcWi0ny57iN5B3Bpl",
	"Sai3stG2JgbWzsS4QpGtEGCqDvpUjjDz92uae1L0Nie4iAu/VGt36ZEpZyjpEvvjcrnn26QJ50wRwXCA",
	"roi4JcJE8rcR4ZTAcQK1aUB3WhaoDurUtW3U40iOaSMF2s640el1axg3yrhBhVqXIoWPFS6XpSK1PbDd",
	"lHK3moA22K6A1il4HR1YRc9qLBV+c1L1vh+NaVCmfZnaBhLpYQgrhb3pTMtziru1oRsLbGfpFt7ABuqQ",
	"FGff7dGWWRQoGmKhjsZczA7i2gDpbMt1HJZvSZ9BX0kEt9Xrp3UZRpRhCFAuzJ7Pm2keErRn03ygGU5y",
	"9H2n8KT78ra4d25+0kJSdW5NxO1qrDkVMzqV9UmprOaFDdlw4XdFIhXYhPJSr41pAWlCRGuSpth7k0+Z",
	"YNWK4Ju0XGxRAM5aZGvTEgmcsXP9PEHXTyrkjy0cr4B403LLUTZYB8o8NkK/csngnVXYH0gyWNcs7NbL",
	"3DJ/1UvDvXbs9UlbhDXGrYbYFha1LG/wO89ecEWURKEgMFhSV9mQSE2xQrNIKjQitkoCGpExF2Sh60M9",
	"33EuBbh0d/mwjLh9KnFFVMYwER+0Ec2oYdzrULuTGmoRlauM1CCyuLcCjYn7TDWyo6P4qyOr0tYOGsyl",
	"IFfxHjYuRnQ29x1OgErBK6kjtN++JT6B3RWyjbmwztAyXIiLqK8jVW8PI9pnmXCqz6EkQsXHeGiTfrqP",
	"zrTfkZvWTPsaxOsRFocRp2X7qm1lURBkerB5nI3ppKa1zFlokzjm9ufpLFQbUCMhdQse3Ms8aVN/slMv",
	"sp6ytwBAG3P8Lnd42jKf+GCqQnbc4Ql6OIz7tRRxXOKs6Wu9yohJ8JL5pi5RNgtso+KEWaurZLQ9Ig3c",
	"On7gSig7GsX1/4rseqm+gYwHPCDxAghAzRgAiFR1KTp8+xLW3QxJh7mviIqBb1fpub2KOLa1beJeVPG8",
	"nMyjvcX6w79mqhtnCgl3qLqOBc0+/8iiQjWy2k6WNsKkVjkk8ylKvzTloG/I3IRuQ7veuENmI/5xlm5m",
	"e5zELjrPL5jfcZOWuckS9DQB0/nRt/i/qst3xcgQ95ud0FvC1gLMeT27VTp4x4p1daLTgwA7lKhyoKIa",
	"3L/dkHmNFIBahhPXS2Gm/zupB8g3ZN65IjrbYI7TAeCoeWkDS/tHcy0sNCLA2wPZNk2IWWrbUdenE9/m",
	"AnJ9m2VW961DvBdU3I2iwWaiTB6Fwrwpfbkzhm5V8S2VrUjSSDKXR5k+kxl/AmSoISzR364+fUQj7N1U",
	"RYTEXMs2razVEMZaQaAZq8wrHu/0Ty+fAXoOrTWDbVi4zhTQHz1iAfdu1psoqZ1eMsVm+83o936FoWlm",
	"DuLqX0058y5z+zFnbhtczeC9QfUa1OTIk7eVFAWoiII+XFiis6t/NKEhZ/K2sm44TK2xBymOSEx6cltU",
	"6KGlkkGc3xVTo5imeG45ExmNoLEbZ/CvmGhYjM1JA6vGU0Xuk9ssllOW2ffVPyDPp9e3zQtheqtgHryi",
	"MuQyCUpwTpk04kzTCn9FcW/iv34xxz/05C00R1zaRicmPD4xweK5i4h1MPwPGq4kM/zz/AJh4U3prW0C",
	"CcmuTVD/nzRsJkGMbTZrawzTnj2drzK1dPkFnXtoG0kNmT44GZz8PDgZHF8f/zQYDAb/PPyDhiVo2zHq",
	"p8aoLbqVYjM0Sq2VTeZFUvGZ6axaM9b1jZl8kwldsMQDZXTZtbtsrieczRX3O6/CoAaFl+sjkuOiMKjU",
	"lSfqbLNr+CeKgLmy4mwD2h+p7cDrpsJTmzOUwfYYSheW2iH+KgGxdbhY0KDCHpQQGQs+Q1JxgetX2oPC",
	"Qh0X64B5LS4WlJesgQIZtWFZj64thkH5iw5+O/hdA34LCkRUCGFQyGWxNGSx/LVpQN2U+NW4QMtguwVa",
	"OgmsQ/pVJLDKqjB0Frvh8w1x57MCmzqIYf88v6jliE9Mc2a6XotVGD3brGA4434Ou33H75DiaIqZb9Na",
	"9GDplE6cEQG16PgtEZBb3+v35A3Nq5/Y7xGBJRlC11T9l2UXhP4dxb+bm7KVcGh89EUvQL+gkmR6ubHs",
	"UaOUZCiIJOKWDOF5h4Lbkp7ZqS/sKJvxCaMgMDvZOXjckB9BQfeSrdtUktjbsbSSTVEx4hPypsS7kRG4",
	"MJcDENoqTtkekTTgeklkFOQ2UTe/I2EHdBT60dlb7Qs2DDcwCBE7yMspZ0otY+94I1ppIg42XLTW8dvX",
	"KVcLYQuny4EPYkJijy7IeP0NxS/kUIp4Vw9NMc6u/tERjR+EaGisAXwrIxWMKzq2R6rl8JwEfIQD5H5X",
	"k2B8zCy1Sfenu9IDeUGzW+icoU/YGZqDEfVR7kiznqNv+n+tZa4KAUMiJGcLC9pitnqaVbDxsyTiM2yh",
	"lmkkiofuSP1avfUdwPnlbXR4/4TxPhcRG2B+/diI+szWMcpnELwzznd2ujWM8xUQXhkp0UBajNRWoXdT",
	"FvuV2dFg6yJoZ7zviMIqxvvabC/EkwYFY3AQIPiiXvT7BZ5sqQDMRSY5tKuGsYVCYqF93KYlik2XjxDX",
	"7uqRQtGmdBQDPQ+il1zgruHyLnOBR9k7PVaCcEWnLEDhBrpONdI6Og6gbafbdGLMGrpNAQRXFKfRX6HR",
	"HJ2/aiCmbAtSB1tjHV1NmkdakyaF31X0+RqSVbQduN+U/t5YXNs+znWS2g+C749WRrSGgkoZURBJSoL8",
	"rkhAPEVvSTBHMHQ53q+mmncJC22w4wss0BXw70hHq+YQgKolmC9FKUmUoqxOFf8wRPHgeqLsVTz1BmH5",
	"RRjGy3Ti54Ybqsj0PZsKgrVhJxYHM7CzKdktAzwdKe5Icfu9VCoxx6HECisqFfXkEcSOHsywEvS+kjDD",
	"YGQGIznld5RN0N2UelMEYapxJ1vzpzRiNYOI6LcpYWgs+B+E9VEkCQroLfmrhn8IGdL/MgJUMblP9n+l",
	"F/xgdl9RZex8jEB9QwJOk64Tx+yPBSF/ELSHk73uHxaUIQtMMaANFvar5f5xTn/J7zoH0A9QQ0jzSBcN",
	"HTxPsWIB2SHxuxC531NpPFsm/Bs62NhvTN0vzBCHwThAoSBjeo/GNFBVYX0pspr1a1UCM/P3Hsq2aPeq",
	"r6ST8VZhVhlYBciKQclCVwVfgrFH30KspqXOmQsiZlifIpgjMwbhvGIHifeVIRz5VKGATxBhqqp9huPQ",
	"sTBxYeyC1SZD+6+W3TpmQw/qEEV7lEHyGtJH7Poc1UGBVzFsZtGgHAuc5J4qiSzEE8qwIn4mVmUc4Aly",
	"pqlJqDNJRXWItSHrS5BNmSITIoorJIdEDGt9XCDBxaIuMR3/nJOiPTphXBBppbn9Q/SJBXNExmNjrzNR",
	"6fr7h5PtSjlQcpaOCW08liebRrdaRE86B5phFuEgmNe0/GbxbWP2X7PddLEHivhxN9DF/TzhHIQUIepy",
	"uaPEUnD0zemZ/30F7ueyApN/lEzYmAkmXerPMn38N9f3v9+x2d1lsx0xenQs3gXY0TylBOvSJbCfVsvm",
	"jmSQGlw3QpWuYD8bJk3VRAIsqnA3T4g+wN12BOKJEwgLtitRCUXw7Oib/t/1ZZbRHGHwpTSmC9cEz65h",
	"D7UIgYqHduJJJ5501GcHxBONkbVpzlKJhnVpTnWZhhyas/kaDR3N6WhOR3M2RnM0RtamOfUTptKv6nvZ",
	"0oW65Kkuh2SN5KlS+2NFChVGkrJJ4E7SJKPqAYB4sGUDfZdd9UizqxYhOt/hhZU3LcuyqkvZL/REW8SJ",
	"DfnOzMFX9J09FGp2YllHFpoEDtd02JlfvtVyiis8qekEv8aTzRa5uMaTB/J4w8qdq/sJu7oVnlSiTAO1",
	"qRJrHH1J402nKHV0fw1FKR96KxPtq2l7pLYBoptK1WrKMAbbYhidfNfh+SryXSWXgg4DTWrhmWSvuCm8",
	"Ihot61lIrm03g9JMrSuChTdFYB1He3oxaI6wX2A2/0+vDQ+CT8Y4ClTv9Li/njchmej5IGemTVpwkhvu",
	"Qoc3Jvkl2VIGB0yy4H41fjURAyvd/64cqCfvBMGOQawjCGoKWwzJlWZB+L5GyZPEJrhpoN2oNVBv/oEE",
	"xOTyOjGxowKti4nlVCCPnx3hW6ywqGZrZnIzOpNgX4O1vTBrtEArkkZdUUT95TZd9Rie2Y5NOvWRjDyP",
	"SDmOgmD+g8I+2mPcFm7Z3zoeXIN2wBUat88SM/C638RWEnDsIy5Q5KBWHehPTCcPAvobbZhn8YbO8MS2",
	"ttz728Xrt3108fFtH/1GRhd99Pb8za9ohu/R8w8vf0X6mo4Hg/vjwaBv/joYDO71/+zX6bq3i90xzSUY",
	"+CiDantZEQzMpTIdd/9RKVy/9+x4i5dwgedAza45R++xmJA2BA6YsR6NzZU7RpiVCR2f2QizVVXpl5h1",
	"2nQnR68A1hrqisK4i5LJX9YF1NRjvnkwbV9/fonZA+rNXe27DtvbxvaXxbiez7IE9m5sSeF8c9oVUdaW",
	"ZseiPQ8rMuFivt/QsvbSLvZ4CMQVUXrvduMP5YDtTGsdkWiTSFwRlcHousRiak5eh1aYoZC/GsmGZOKd",
	"WeZRUQmz5wciEGbxK7jrjkB0BKI9ApFB47pkYkZmI8DZitgNOw7CNxpkl1sq8cGusoP5LLWq5BrfnSSi",
	"65T4A+S5ADbFAF9qus/Vx1/4vrTp0EjxlTTzTePLhrzbL3zf7LxT0jv2+kQIwgvft7RAI/MqHm5LSTK1",
	"ForMzpdkxm9JQj6gEvFqNmhLQhrUVlixrsLaBRo6s/ZTxyED1TEaAVCvhEhUSsomB2lXiNohx+knSE2x",
	"QmpqXepTLMEzZttOzIlqJtiaLZ2lO3qsIm5yhE7E/WFEXAO8LnLUwciIBdy7WbWw+JQyhewU9VDts11v",
	"FwqKf92oZYgpc9Yu+H7jdbtdMCyHdlnHPOJCOHyxUmrLZ5mr9JWltujFNAQjLtD5BaJjNKYk8P9Kw5Vz",
	"XXKXg1mzyxUvAYPzM1p68Qy9fo+waKYv3fkTDZ0Aqx82AUfDQUcDNpuAY7C0uXUnW6WguuZdYtqJkXvD",
	"VfqNlfJBqhXkWEm7mgW7JrM+ypbLtlgC2ERqiagSDC618+Wq0dgxsAAi71C+3EO1ciKHk0MkSTA+sO2z",
	"IMI1CPgd8fc7vfCxpvJVIFllKh983ySVb9P4tNFUvsbsdrBddtv5OzoqsEoq3wqstn4qH0zeMJXPUoku",
	"la9LdCm5Ag1Y7afyLcPrOql8taE/TuV7GNDvUvm6VL6Ou+86hXsyqXz1aGyu3FE3lW8VLb9L5evk6DVS",
	"+Qq6I1Sk8jW1Kj/CVL4H1Ju7KMEO2zeRylfZCcVhWS2HMgHzXDWUyZKQLpSpQ7vHGMoEsL9qKFOKkUpg",
	"70YDaV08PL9A2PcFkVJjIiTn+bY1a/1OaBb3ruPFNxin+wMET8TX2MVOPGVcjzG1CsPDkOCgst8EwkgL",
	"6mb0IbrUfwrojCriI8URZwSFRKA/Ix/PZYEgblfaZA8Ks8YDBXa8xCxevwvsKMXqky2GV1xzjj5gNo9P",
	"L9GecKB3v7WwCxdDXGSzYJ9Bt6MZqeSgWmLV90aY0ldDjPHnv6SzjMxnmea3D6S3QSaSAPvOc5E2KCq/",
	"S668+GkjNT0aczHh6iDEUt5x4ReT1SvCfInicUgQSRQiM0wDTU9lSDw6psSPhad8ihqp6RtY8CJebzPE",
	"NbtIhrxmT/UaDpDuuTNXZKnugxK+RVRYSD4y8UpZiHSBPSVFen4H5gM+oawY0p0P47gXzPT8hsz97bdr",
	"pDT2FcP4e1hgM6ANc5dA9Jkgvt59KrlsqUKOvpILTEVneNsx+aEUjcDxFFh4rYU63HjD83HnnN3igNri",
	"71OCBBkLIqfI4/yGkkN0FlDCFJJTHgU+8qn0sPCN5ADOT4NZh2WYpdd/dPGU1NwL+tvVp49oxP35fgeU",
	"xUCZvHI1QNaQSykzYQSUM4RHPFI5UmquWBqp6WZl0g/kyQuiXiSExnhgo/olyl61Mgg1M1souAkxiRON",
	"+kYe7ScywX5BeGr6sJtqFXZh9vZgrrDOC1ZionuAXIlsip1Vm/ANYfuthXbm4UYtEsrhf8m9N8VsQop5",
	"+2s7QiKMOCMHis4I+qTnRR73CdrTGuFoDtxcEnGr5WY91qQ0JgZwhMfwv068UzwLDoIR9m72wd5uZOxD",
	"dO2IEfA3RKUVxrW6KRFmaKpU+IkF81jOKJQfPumzxgfZEAWAw8RrPFS9yt2VxtFe7NXhAs1woJkz8QGE",
	"9h/OkI32AIbJfagfSG8NB4Jgf67xyea97K7A5GAhSYG7LuqHgt9Sv04+9N2UelOLrclXCAuCPM7GdBLp",
	"u9PKsiVGwRwRhkcB8Q+LJCzAyItkBxvECdh2slINDrnr7x06t1b3rb/FH30veWyfCuIpmcYgKA7/nV32",
	"vySKOasRrq3LsPqZq3Lhs+tAi0erR02omkajPppwPgnSvo9ZT2qYLrN2CMMiYKC9seVSvyKm1YogmKOf",
	"BidI2FsDUvHT4KT4XvVtZk/4sPJYJZzFR1sJzI5irl4Ib+8w8wNrL1h4+fjbfkLWpKFyqYBgbXMJyBpI",
	"HQu4R78WOJ7FO9xBsOznWSdTlIPLSIQhK3wtAFd+MQf9ZcOSEUqLmakcp9/g7OryjV5JEQ9G5a8l9Ze9",
	"3cG+GDpMNQ8LR5ShscCT2QMbjH7MKIIdSWHPE6pS4lBN/KyeUqxDXZoBWody7J0oAnlY426iyWQtp0jr",
	"Vlglltp87cbO3ntoxeIHzB0BNgCy0ggztvsaw6WrUcuawD2hUhFRFXrjFlHRVBXsAXOpyKwEcO3Um9HI",
	"4+lL3GZmiNkapLn3thmJk27wEQTiPAid3nFkMs+XgH1NfJKE+Qe3RNBx/HMJ45AQgOGOTsMvajg0UlTT",
	"E/3DXXQ3ohw6V9gahVj1m+bAxqpweDCaH5gJVgHI0dz+h42rOUQvgjs8l0kIhbX8asgNBblNrNaERTML",
	"s4cNAPjl/LU97GaYR8F6XZ7TIw0cKkCWJbitjT114uf0ssoJoLMiv0bqUlDfdKhcZo0SAQnIDxhbNJML",
	"s5vqID+F/OMtrv2WM/II0E258FKNUoCalQzIUOQ4Qs8groNUph65xRgIuUF7+JZTP9a5KUOfL98fWT08",
	"4BO5X4iIsNZGuYyzQsdXOuyqi10GbGoKe1CFQR59C7GaFrt/roiAVhWmZsOYBkSivXEUBAeS/gHhC2oa",
	"zUYM02Bfs0ypuMATgvSsh+giGgXUQ4T5IadMGQtrmr9A2STfEwirvZxfGIt5eaVkZ8HY3u/stsD4bv7V",
	"ZkorVLk5+ndIJtnnr1O0xnwbspU/vSOjsOm3RRVo0nI9WzcB2x0U1nZaLvJtPhjNkX3RBOQNdFtYt10V",
	"m1X4jj9Ce1BH37ZYpSSHMbwl6mW8xDZyn5Pup80zn3fQragfMrls/QLOOybXah5yhUx6/ZROwjBQIJs8",
	"b5roGe9hUbaS6cpzaQiFdMdQzn5NZx7eUklHNKBqjibG7JmZjnF2YMqAQTpyLtkry8pfMDVDyXn3XKM5",
	"UniCIG04z+mm8KTX5ew/MjdC8r7IgS4NrdAqNvYstBKYm0LSAgY6QLmIg0eSB5HedTU2aixMRgPGOSta",
	"dLT+aitPa9E9HwfvBFUkCoc2luivmndX4NNVstGtgnm87GumxLyD9TJYP4ifVSKfSnjYlnoALIOehTfP",
	"Jbd1wF2/XgPGc4tpoA+SLoTMDKWgem2HtAOmC2T+0csJy1dZ5+G+Jf9ti8WX0yokKZtk3g2kBp8oTIMy",
	"eQHtgYLUh8Yzso/GVEiFRgHn/v72hYiz9NBV8kQy1BEgshqTl5lse7WAatHZV/AyO18M5PGW5EgxYTQ3",
	"INIY7fQxZvoQlfgXD7R1dpJJDtGLhKRyFsxt6oC+HqIoWO6nWCLC/IIA41zUOIu39WhRpJ5MYo7ZCd71",
	"BG8HphhXBqbaErVd8E5gxkWpGCLr9Ceys7WLKxdc7jSybKr+ToIkD1KAZwlFu/I7PwJNsPV3XESuoAql",
	"bBYk0NpKijHoY6WwNzW1sHBm9Xo89A2s+WA0oZ9jHjMKwqkjuXARq5hFJjI9bX4/Q/dK4oaG7t/iib/2",
	"H4a76wOfKzJ7FGy9XYF0bGGvuUAK2tkBaGe1qlkZbQ6MBwIUfJfd/jYlLMNeqURjwf8grJ8EOpl/o1tK",
	"7lDEAnA001sCBiybuAIklgj9NSh6hw1wUEj1Eg6zO4h4PkYlh4tvBm4B7Wnt1lzRvqs5Iz/S06OxIOQP",
	"MPTlIa+eIs/APeI8IJhtWBNNL7+rSJnLPKXHBRlxLPxSU/bj1pIdoF2JIIHVqDbrhtHLcr+tcqORbGou",
	"Xw/RuGUaIRPffFmfsryjT1891md8dLrxQyVnPd+m6nHOFBEMB+jKFJGAD9rB1xSD8gRuA/Z1UPbom/4/",
	"/U+DYsVRarbLPcKmNflojmRImA9hapoQQpSMrK+Pwx7fweJm6h3i/XpbhauYC9sZS3IW/bsiOUuk5mSb",
	"CC+j8Zh6UBrOIsS2JReogzeLNDcniDKEAT1/oJTYF3G5EyszPIW8GEMhgfI2JfOaFpvovNzuf1dEOa3/",
	"gJKbL5bFs8QJqDVKGKk4muJbEnul9d/T8XntAnM5waXZ4VOzy7rHNUd8oHjoePFOu8vR7gCOFzrTZOC4",
	"BTPpRaRcpMqT2Mwb1UTm+oqWHb+Ey7UVqHhfT1uFWsSQH8QS6ULHOkBpHrOeh3ypSxRyP0d7oSDwB0lV",
	"QbhyPpy6e3ji7vA0EjU5c6f/P0A8icjCXHOjWRzaVx1WkqwZf3Jk3TaIutF6mPlpq7U8ZlYbn+Lwzyce",
	"fRUfsxOO8gNbU8BLxaOng8AyBfKVkPe2gbfaDF8UxJrg4y35YTgbnPZxRZ4/EXy4XdEhLaPRjKoaOc7j",
	"AC9oQW5Ps1P0HGGlyCxUEtqazSiLFKlvVb4y+3hqtgRzrDcBnpQUNtA/I8VNQYj5VgsauPvrTNFdS8WH",
	"LYZoi9ilhC2ugO1kaxE8238KlmGDeUBWVyLc5ouaQowevLIIc42fvB3pGk86TXxrgksCjbkxp0sYYINQ",
	"oZuyAfWAKLIM9K/g7xI6D8aRrZA6smw1NUPj8NYauUp2uiLgXhuma3SP+gFt/Fp3jV+S3zEiHnW4lgG6",
	"+EAlYdZpROeRKRdQJ30pCQK1FQb2QqiD0kfMFGfMN8mm312ZlTZpvFlcbJdFzqqc0KULz75n/GPypGxM",
	"J/LIvEnlc5phtqMFwqB8KXRD5ge3OIgImuEQ7Wmi4iP4g9w/RB/NM8fGzYJsNLMPUyJns2+tFzLrPOJn",
	"zjxE9on1X+zr+mQUVbf3h1FuK7hDBGW2UyswZejqxZvXww+fXr1Gez65JQEPNWXYr+z5/wq2sOaDYt8H",
	"oMXBhdArKKrnMczMsjA++jfxcpXYV4vH69S27XGoFIaAZ7qA1FIG4RL0OshwZUprG2QYUxL4NThWJBWf",
	"ITMahEHh1r/eG5tqM6M5IkxRNR9qAMzlYW/MgksSXF7EvjNXQdaNrVwcJ9zEpZQJnj1gog0J/CdUd8m+",
	"efK0yD5HDE72QWNwCog8Gs0PqA8KwJHP71jAcXX6TCiIpBNGfPT58j1AGPRqTL7PBaWAyPNXr9IhVRWR",
	"yOZUgjYzRQISn+nz5fvOZ1Yr11IqLJRpxPaUEkZi+NdYUaZ2G8SLR1eWbFRC3xFgmK2MB05tU+h0of/i",
	"YRxXT2dhAG54Q/QjSSTyphQJHimC3r6+Rovb+G+0d0cD38PC3/8VXOSwVNoSaEQCfoeoiXUM+IR6ODBj",
	"9sgtEXM1pWxiM9Phc0HG9L6PZniuxTyFKUMywHIKQvVnSXw72NlNhg4lmXZY3+gh+p+FXpNOw8gSwRwo",
	"T4yj+SUoVykpmX2k9/Y64JVMscxz5jbLXHgPE4EQPweV+S+in4FKc8f23o2Wwsfwj/i9rHH3+OeDKbk/",
	"8KZYSJgrbkkqCXQ+Oj6y/3ECvx6qe7V/mFeGMp/Dx+Ws695JfOduyd6Sp7Zo2l+tfRQwDAmo8rD9L+Nm",
	"4PBoXKC4HyZcwn5X++6JJgy6VDoB6j2L/CVEd7+MUUwJDtS0kDOcTYl3I9Grl310SXwq+8AX4pK9HmeM",
	"eIreUjU/RLHodjIYQHxUECB+00fPBz8hrqZE3FFJDr+w85hM2e67sTIxhTZ+wuhAtxRbNgPZXGPskf1f",
	"3ZArhezWYUNHOKRHt8f2T4dfWB6VfmeOusmkIFihPEsisL2MJEo2iAOHnpQ6Up+3iFrVm/3EgLTPuCDJ",
	"piOWPEKpqmBmR56GHwf+ztlYYKlE5KlIkAwMmqGFIgpwN8j7ZkRKM/GvCfvWMGcKtYI578jHCo+wJIfo",
	"jVYdoiBAgmCfwrd7/qgPHf9kPwblfS2+GPSxYGVa1WrBwqacPx/8dFgMVvFBNwxbsMwjNcm5IIH24pfc",
	"LzJFzIgS1Cu2Rby+D7kWOS8EnxE1JZFE9pND9MIU5devNyKa8eu/K+ODNubAakK0SG7s5Bl6Ey+YT3A+",
	"2BPUES7sWESZeyCiz2iUGlueuxahKHmE5duqwk7GVdLopL7PehLwEQ5Q9uOcO/q4MKCGGci2Cc6x/xwn",
	"kh1likyIKJY0QyKGxROdDHJm2oq5yL2Px2Q12ukuB1pzLgDIGPSzcGggn4eE4ZAexnuvrPfyKSTsxcU5",
	"+ulwgGRIvLRBEGXob1efPjanOu4eMqTH/aGA/tjt1KI/7tb1TpHPvWihl+2KPaDtzJkLqSI6GjXrExtw",
	"9Mgp8aGFuER7iqqA9JEMokmu1fkCT8h2Kjvrld5Tqc4VmT0hK/DijS+UADf36zzl0Tf9FtWVdPVgKHIQ",
	"RBPrBIdVOAvmxS95FUSTWiYXGVg/2y4Ydi9qdsvZBW11GQCchyp6eEFvsTevfPMLMw5d8IB6czNzfNy8",
	"F7fTVr6MIvfqaKpmQfaCKruaLOzHc8N4dhQds1sukqgFH3ElD9W9qnyTdGh8flMHnWDhTRFhE8oI8gS+",
	"CzS25bzSJUxwfa9qvlMYYLpwe+Qea15piysc4Alh6hT99xf2ikocBPzu1DDDL+yF/Rewwcr3XT7bTr+t",
	"82oF75qWyqrhuBVCP6ZTXQua6yPJhdWPTAENpL83hWYO0afQmCnipitoz/a2maPzV/vIeHtlHOAbN76Z",
	"b67GXVFl9KKyYfCURO7nKvBX6fXVa6LirDGaL9/JfnFPFTs2o3QkfZeiiPr5pvKWSuQ5+85WyEPnE8YF",
	"8ZPCXzCTrF05L9GbxjiQabhJe5X0aola6TtCDlNXuLppnT1b/Y0LA0nywEhdT6h+l3RRPaGl6R8X6enR",
	"ROBwWklVnTuED6ABvLFHmoItdEYCymwi4i2VEQ7oHzaMDGjkpgp/pmd7CyepIHAfo9nIlCpVPIS9Q5Nl",
	"yrwg8klRFVweFphjBvn2mNXJGdzrI6juuXjtHcnpSI6lDaWEh6goLM7mjGv4qylBlFFFcRAjiRVwspHN",
	"REEhkb5FLRvowBCOu6ffkII+6VewkQpi8YmRA03ZEGzbdcFbn6SxtEdpQ3ZA1CnBPoTlWUz9fw9gtYPr",
	"St//trI+9XYeqGgUrH3Gtd6jdr2V7gMG6G7R0gwvkqQyevZpdtzgHUOQKTB8ICJmkNQlPvBvh+7UzVa5",
	"mxI1jeOvAqy0/mJJwB39A4g6lsmFjYjVAPV28qOnYCebT2BxltltxNo9zpdftzoFq+Ukmgx0SVLeLFoc",
	"XBGm0OtbqEWlBGYy5EKhA4QD2J3Ssp/i6DcyuuKgbGs5mrBbKjgzFazUFKsvzOcm+DMKYYJ0fBROBPaJ",
	"PESvZ1QZFirxjCCiFzWt4RCW6OiuyJl7BYFj1Y6Uq6vXNkgMEalwbMDeAysXrHZgft5/5KXM9EHjAKCM",
	"Q8e8Y/z4CisqFfVkk1a86Vcm7znbkdeoI1oHgMxy5PGIKbmgSUWSOCrTHshJ+zBboknkU6Nk6frNdR+r",
	"CtOwPIzCprDuI/BFP6Ra9VQ0F6dCTYITLolP/1iC6rZg01FIhEeYquXWNVidfmGoPfamS+1TNoHspubT",
	"hbPfDvvj4lDprXR04EekAwuIuQI5+Fann67pm2v77btywHKf3T1DXzKdc/vOFvc3SCnyKk80zyXbqP/n",
	"sRhMFxrzWlFjN0nKFuMxzjKFIMdPrZ1KisYG45sLGhPCiMBBJUWx4xyDRUpZ9oz+gPjYNMnuG8dH31E5",
	"+rZIX/vU5K09wBOVMcogzx59p3G9Ex/WRvIY9RrjdoOwloxHSSou5oCExhm74G99ZdyTpvIlOh6gvRm+",
	"R88H7eN2/cASx++64HNFlCVH2rOeVXQ86CO76ULMNvU4C7yyM3xPZ9Gsd/pc/4My84/jp+yubRhC8s7c",
	"eeNquB2xeireWot1TYiVPPKplttH9erLu4Nj3Dc7kAh7gkuJBNbix2Yok3zlbvZHNnLAdbi38TKCML0O",
	"738ovM8gZF28j0aQfl8nNw5PJoJMsCI+Sj9zNZGQCOTjefvo7mzyB1Q00uNf0xm5IoIS2RXMfvo4nYdj",
	"zdH66JsG1mqjZSlK2xh5WwV7HhK053EhiAdtACmz/9jfJOpfm0JdpeifDje7NNvOr5FlC38VWzbjMmz2",
	"cDBL/N9fn7Chs17zM6dgniZLF5yyRyBxpNVnTEm/p04vYnytSTdAfa/OFYZ+n27FxDwhoCjHBSqw5KW5",
	"VJCCa9jbo4DtH7Lu6FPBozLorolGYIevRCPoubZ1NPosTcpjh0YdGm0SjcqguxSN7vBkQsQRZT65P4zz",
	"n3MRCXaPPQivfHFxntR8sLmUV2Ym9Pl83xZ99FHEfCJQssh/N69okXyaKWfhTpiLf+b3z/WqWaQ7R++u",
	"P7xfu4ZFOl9V4YpGjV1wEEA7jbwD274tO9s9pYuPLomPdh42hhZ4TwsjtYTEEE8oA2NR0gcIfEMQCJOy",
	"MmJ6j8pDhD1wZA+dvOcJ5AtlRyf5vfa7XOCzomK5rmiKAcTqVZ6u9Z9eWf5O/8HqOz3fRH2nUiQjePae",
	"SrXT1ZvX5Vr6gAZIXbiHf3/93q9IamPkDr6Fsr0CjYjHZ0QiD4cKm4z/hUp/0MTBlrO3Mp6PqKlamwA0",
	"uuNR4CM8HhNPIXKvOSWbGGuBZj+eMwmiehfEJ75bV/DYrKaPEd8k0rw4giS6/PS5VNNqPzvN3JfZTmFP",
	"Qv0zHHKr7QjzXqSoYVxy6fH20IiMuSAoFNwjxAcK0e+dtIgN7hPmbgtu1v/BmyU+QOPA9SmPeTqgHzmk",
	"J+G5R/gOC18efdP/qhOIasbb2FM7ez6zPH/1AsbWigg1y+9eIz04Qlc3o3Z3M8qMsUNzEv1vY59/uKpd",
	"aA+2k8SK7rdo0MExeBdj1xjToAFyjW2Md+qhcBAN7SXy734J0r3RS24K5+rKp2vJpFsVQ/V17bwY2uH0",
	"tnB6bLGnGKX/zU1VtnzZ/W+cxt6M0RxRdks1E7Z1HArEYv3NhkRjPXWFYHye3eP2ZOMq4fOHb9L9Q7XK",
	"hoWPt/jWbzkj4LpNoB+R+1CDfgv0RONdtewdEHxLimnJe/1zUp8wV9ZOaAiM7a3ShrdT6x6TWmdgohKy",
	"ZqS0sTSVI8x8U/PBhS+0d2aMSwXVhU3HX1juw2rQ9gP639Zus2xeq+jRtaSvvOny1X8OfTAjxg8cSSL+",
	"S1qLovvOORY7PaP7zO1LJmZ3S7JJJ37sDH18wBbpBjj3H4xOoz1o4qaw6R62LgYbWEezeR3CfYRvscKi",
	"lH6bxutGKYPRaM+rT7hfmAXqkG8zFJmN+LGJfxwFwbyDUNoGbJS85X4+tY9UHq2H1mdcoMjAWgPYuIjU",
	"MmAUEfxZFCgaYqGOxlzMDsChkrnl0Om0/a03pgEphCo6g0omNCBo728Xr9/20cXHt330Gxld9NHb8ze/",
	"moy+Dy9/RTPK0PFgcH88SPL8BoN7/T/6PEm9gBFl2OQnLdqtHMbyL7Orr7k9wLfHf8wlmIcr7Y9mLiuC",
	"gbk42HGoh8L/3F6Kx1vc1gWeA+Jfc47eYzEhbTAr0z60JkHKsi5jEW/gQ8oRTgtt2x9I4lDqHD+7hBEQ",
	"lzeLpEIjyM42/ooHtRAzHu+hDdOwldzqeHxmxDh9VvX15CBELcfPB1Lm+On8NR0qPi1UrHbUzMiRse7W",
	"alQHk1pr8OfL90emFHiFnSRFPuNF6W3YXmFW6UC/puXgKcC7C5exj65uIOElMZVm4gr5S3OZjA+iJMIQ",
	"bQgOEBvqDs3t/4x8PJf7lfbC2A3RIUKHCBtAhBSQa+FDhgeYMmX1KqyuopOY4qhb0Ulgqd+ompqSgLJT",
	"TzqZyJWJZAyKZQgxGxGRFh0tMjH/nXo3miuY8aaHScJCmngJYbm8sqCLzb5hHQh0T3vFNaoaWh0f2vkn",
	"i7qH7EJD1eawr4HUQmg50Fd3XKXMGJEhDXbEI5XvNj0fI4u6aWOyZ4NnJZrBfNOikOYHFs12Xh7aIpgB",
	"JaES2QBGG6veJrktBTnJA17dtgprks2tQstNAxngVntXJCCeQlf65w/cJ/vFMrces9HMGr1ARRBh0g7V",
	"Zg8NBZFEobspMTl1SfMbaISTnrq37GH5wbJbWsrzSG+0AipvSYN4dEcorkz2SOTgx5vs0cnXXYx4DWtM",
	"DTEbOjaNiTiwengxK7i2I+M+0UawFjwgxRQ//saK4Rsi/gurlFD/j+Qu2XkOXm/Si/6BSIknpAvk6tSK",
	"1tSKBCUtTMspDUuxvVYHD2u4StWM0Rydv9pe7YJqHRxSpDemfG8/cvMHZMUWaJzSTfuPGRMTlgu4UoSD",
	"vNq6e03EDNpZXBFxSz2CQjwhKL6PPJThNUy60MAwLidUjAs5tQgWduPtQkJGRQGXxU27BZfmUpGZfQ5N",
	"ho4YV3RsN12/+E/mqyVTfN4zaS3/Y2at1eIf2q+ncrKJeiq1tJjFO3lUWkxrZcLYAlTEsJqFliKQBZZ+",
	"JAiGRhsFCRYfsLiRmYUQlgg+yk2oWALW81eXZvDaHbO2yX4biNw/ZvrkTjXBbo5CGqyLoLoSi8AlW5/i",
	"v7g4N17c+uT+2qywlRjQi3NY7SlR0OXyVLO58wzOG+vLrlGlykSOJDOkZanCAGvOd69srAlnHskPHVl4",
	"1k3ZsdPnbJBw1t47xstbs3NXd6ktKLYm8AQEl2F4gTxVer8vyS2/0bDNMrPmublT2G2n9+Xj92LvpKq5",
	"EE6kn7cOwKxSkxK+24pdJ6673NWkbCspWRLxY9SkjCzouHDvCnLNMlEXYiVwnEdYRDCfShJqS8mfxkMe",
	"X8jik9RN+az3CBeRWn6BLtuzy/bs3Fi5FnUywzQAP/ItEXRMn1aWZznlyTKDtXI7C8WXLqlz4/bQ2Xw5",
	"cTH3iVtLXKzKWLQv32UsPjU4W8zKywWz9TIySuCpS8XY6mMvxUHlv3aDdqAuTdnDQYCwUmQWKrmfhMfW",
	"BYWy/p5PySVYr8vnj0J/ZObZi+GyVsROGI0C6uWkBmArNzFfgyQVBhN85E1xEBDTnrqgx9avrdt/quN6",
	"NptU06715UJwra914T0/SngPYFJoXr0SZVdQQnA5p2jUpKBrUPD4A9X5HbOkexfC1FvEoRoqHqDQWkoe",
	"rq/eNelE0HUh6KraPArE/WxDy0xSSYvYW604A/I2V50r+V+DvK0uZ6vDqMfACksNE3fF6PNaKjwKqJxC",
	"WNNvZHTFvRuikMcZIx4ogBqlBMHBgaIz4jZLjmy1bXudaXTc4Rf2hf3pT+gsneRCcMU9Huhfjg/RWUAJ",
	"U0gS5kv0+9vX1+joTv5umuz9/jmcCOyTU3RHRhK28zuaEuwTIb+wk8O4CWdkhtmS7ulSpsCPnhij3+3f",
	"if87IreEqS/sp2SCMIJjw98lwhL97erTRzQzsZ7yC3uWjDTTpbcTUjZBY0074HMxR//f82dIEo8zX/6K",
	"PHM6qL9hyIFvjhZyNrF383dCwoMXAb0l+g8H6EJPqTmvuMXBKUqngx85myB9/TxSp+jnQfwb2nPO7QVc",
	"muaHjMNKSBCP0Fvi7+s5PuB7RJnHZ3ohe0gk6R/kFD0/PkGjudJnhr1dknRa/aePHEmS9sQniEo0w5Qp",
	"TBn07FN3hDDnDWT8whLJKfRepHF74C9MOLObayH3BocoDtAIezd8PD5EL9BYEDldfkK9utT/zxki2Js6",
	"68aA9xrGvWa3JOAhXPCLIEheVmMMUlNqHzxp3nuqB/7+++8a3b+wb18YQl+AoH7pnaIvvS/RYPCTB1sY",
	"wl/1v8mXXt8MDI3HSo/9hg4PD9F3+4N+N6nwLDTTnAxOnh8Mjg+On18fPzv9aXA6GPzzS+8L+w5rZw5w",
	"PQ/jN/mTew9f2JU5v0dQFKZ9KMdRkIvCh+UHSybOOwuLgmD1g/wJ/Z4SjKEhGL+jPaBW+/YYkDGP3TxT",
	"hFO7UsXel2bPfQ/9l4Xv9EJ2LPxC8GxIffPj8+cD8suzweCAnPxldPDs2H92gP98/PPBs2c///z8+bNn",
	"g8Fg4Hyb7NV8ffU/79E5+7cF8OPBsTM05JQpqcc9HwzSxetdLFoHpApeYkyFVMNRwLmf9x7UUFcYhRQ3",
	"77OF53G2tZlHegmBFOj1fRhwalqd5z7T8WD77+Ty0t8zj8KMyIJGgmPfw9JUsXOGVzyHO7TmS+R8ogdY",
	"WmrGfCR3aEqZZnYBwZoJgQcrvnH0X2diHiquceG/nDkCcksCMwNlY+4+dPG9PT8dNLto94P0ot1ofgQb",
	"kafod72N3/vo9zssGGUT/Z9ES3P6PyyN/T2/M/1vSz64YyNjL7akp8qbag4cC0QSHeSLXSSRzHzTAzen",
	"c/2nv6M92zHXSkP7XQD1ysJ03jM4EjXwZBCpV1wIZMk8b8XZ9Rt0EWA15mKGXlyc9/q9SAS9094RDunR",
	"7XHv+9fv/38AAAD//6S6LcSGdQMA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
