// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/coder/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConn creates a new instance of MockConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConn {
	mock := &MockConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConn is an autogenerated mock type for the Conn type
type MockConn struct {
	mock.Mock
}

type MockConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConn) EXPECT() *MockConn_Expecter {
	return &MockConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConn
func (_mock *MockConn) Close(code websocket.StatusCode, reason string) error {
	ret := _mock.Called(code, reason)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(websocket.StatusCode, string) error); ok {
		r0 = returnFunc(code, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - code websocket.StatusCode
//   - reason string
func (_e *MockConn_Expecter) Close(code any, reason any) *MockConn_Close_Call {
	return &MockConn_Close_Call{Call: _e.mock.On("Close", code, reason)}
}

func (_c *MockConn_Close_Call) Run(run func(code websocket.StatusCode, reason string)) *MockConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 websocket.StatusCode
		if args[0] != nil {
			arg0 = args[0].(websocket.StatusCode)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_Close_Call) Return(err error) *MockConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Close_Call) RunAndReturn(run func(code websocket.StatusCode, reason string) error) *MockConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockConn
func (_mock *MockConn) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockConn_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConn_Expecter) Ping(ctx any) *MockConn_Ping_Call {
	return &MockConn_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockConn_Ping_Call) Run(run func(ctx context.Context)) *MockConn_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_Ping_Call) Return(err error) *MockConn_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockConn_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockConn
func (_mock *MockConn) Read(ctx context.Context) (websocket.MessageType, []byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 websocket.MessageType
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (websocket.MessageType, []byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) websocket.MessageType); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(websocket.MessageType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []byte); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConn_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockConn_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConn_Expecter) Read(ctx any) *MockConn_Read_Call {
	return &MockConn_Read_Call{Call: _e.mock.On("Read", ctx)}
}

func (_c *MockConn_Read_Call) Run(run func(ctx context.Context)) *MockConn_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_Read_Call) Return(messageType websocket.MessageType, bytes []byte, err error) *MockConn_Read_Call {
	_c.Call.Return(messageType, bytes, err)
	return _c
}

func (_c *MockConn_Read_Call) RunAndReturn(run func(ctx context.Context) (websocket.MessageType, []byte, error)) *MockConn_Read_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadLimit provides a mock function for the type MockConn
func (_mock *MockConn) SetReadLimit(limit int64) {
	_mock.Called(limit)
	return
}

// MockConn_SetReadLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadLimit'
type MockConn_SetReadLimit_Call struct {
	*mock.Call
}

// SetReadLimit is a helper method to define mock.On call
//   - limit int64
func (_e *MockConn_Expecter) SetReadLimit(limit any) *MockConn_SetReadLimit_Call {
	return &MockConn_SetReadLimit_Call{Call: _e.mock.On("SetReadLimit", limit)}
}

func (_c *MockConn_SetReadLimit_Call) Run(run func(limit int64)) *MockConn_SetReadLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_SetReadLimit_Call) Return() *MockConn_SetReadLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConn_SetReadLimit_Call) RunAndReturn(run func(limit int64)) *MockConn_SetReadLimit_Call {
	_c.Run(run)
	return _c
}

// Writer provides a mock function for the type MockConn
func (_mock *MockConn) Writer(ctx context.Context, typ websocket.MessageType) (io.WriteCloser, error) {
	ret := _mock.Called(ctx, typ)

	if len(ret) == 0 {
		panic("no return value specified for Writer")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, websocket.MessageType) (io.WriteCloser, error)); ok {
		return returnFunc(ctx, typ)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, websocket.MessageType) io.WriteCloser); ok {
		r0 = returnFunc(ctx, typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, websocket.MessageType) error); ok {
		r1 = returnFunc(ctx, typ)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_Writer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writer'
type MockConn_Writer_Call struct {
	*mock.Call
}

// Writer is a helper method to define mock.On call
//   - ctx context.Context
//   - typ websocket.MessageType
func (_e *MockConn_Expecter) Writer(ctx any, typ any) *MockConn_Writer_Call {
	return &MockConn_Writer_Call{Call: _e.mock.On("Writer", ctx, typ)}
}

func (_c *MockConn_Writer_Call) Run(run func(ctx context.Context, typ websocket.MessageType)) *MockConn_Writer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 websocket.MessageType
		if args[1] != nil {
			arg1 = args[1].(websocket.MessageType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_Writer_Call) Return(writeCloser io.WriteCloser, err error) *MockConn_Writer_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *MockConn_Writer_Call) RunAndReturn(run func(ctx context.Context, typ websocket.MessageType) (io.WriteCloser, error)) *MockConn_Writer_Call {
	_c.Call.Return(run)
	return _c
}
