// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/TakuyaYagam1/AstroCTFb/internal/domain"
)

// NewMockCompetitionParamRepo creates a new instance of MockCompetitionParamRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompetitionParamRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompetitionParamRepo {
	mock := &MockCompetitionParamRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompetitionParamRepo is an autogenerated mock type for the CompetitionParamRepository type
type MockCompetitionParamRepo struct {
	mock.Mock
}

type MockCompetitionParamRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompetitionParamRepo) EXPECT() *MockCompetitionParamRepo_Expecter {
	return &MockCompetitionParamRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompetitionParamRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCompetitionParamRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCompetitionParamRepo_Expecter) Delete(ctx interface{}, key interface{}) *MockCompetitionParamRepo_Delete_Call {
	return &MockCompetitionParamRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCompetitionParamRepo_Delete_Call) Run(run func(ctx context.Context, key string)) *MockCompetitionParamRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_Delete_Call) Return(err error) *MockCompetitionParamRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompetitionParamRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCompetitionParamRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) GetAll(ctx context.Context) ([]*domain.CompetitionParam, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.CompetitionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.CompetitionParam, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.CompetitionParam); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CompetitionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompetitionParamRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCompetitionParamRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCompetitionParamRepo_Expecter) GetAll(ctx interface{}) *MockCompetitionParamRepo_GetAll_Call {
	return &MockCompetitionParamRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockCompetitionParamRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockCompetitionParamRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_GetAll_Call) Return(competitionParams []*domain.CompetitionParam, err error) *MockCompetitionParamRepo_GetAll_Call {
	_c.Call.Return(competitionParams, err)
	return _c
}

func (_c *MockCompetitionParamRepo_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.CompetitionParam, error)) *MockCompetitionParamRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCategory provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) GetByCategory(ctx context.Context, category string) ([]*domain.CompetitionParam, error) {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 []*domain.CompetitionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.CompetitionParam, error)); ok {
		return returnFunc(ctx, category)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.CompetitionParam); ok {
		r0 = returnFunc(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CompetitionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompetitionParamRepo_GetByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCategory'
type MockCompetitionParamRepo_GetByCategory_Call struct {
	*mock.Call
}

// GetByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
func (_e *MockCompetitionParamRepo_Expecter) GetByCategory(ctx interface{}, category interface{}) *MockCompetitionParamRepo_GetByCategory_Call {
	return &MockCompetitionParamRepo_GetByCategory_Call{Call: _e.mock.On("GetByCategory", ctx, category)}
}

func (_c *MockCompetitionParamRepo_GetByCategory_Call) Run(run func(ctx context.Context, category string)) *MockCompetitionParamRepo_GetByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_GetByCategory_Call) Return(competitionParams []*domain.CompetitionParam, err error) *MockCompetitionParamRepo_GetByCategory_Call {
	_c.Call.Return(competitionParams, err)
	return _c
}

func (_c *MockCompetitionParamRepo_GetByCategory_Call) RunAndReturn(run func(ctx context.Context, category string) ([]*domain.CompetitionParam, error)) *MockCompetitionParamRepo_GetByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) GetByKey(ctx context.Context, key string) (*domain.CompetitionParam, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *domain.CompetitionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.CompetitionParam, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.CompetitionParam); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompetitionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompetitionParamRepo_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockCompetitionParamRepo_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCompetitionParamRepo_Expecter) GetByKey(ctx interface{}, key interface{}) *MockCompetitionParamRepo_GetByKey_Call {
	return &MockCompetitionParamRepo_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *MockCompetitionParamRepo_GetByKey_Call) Run(run func(ctx context.Context, key string)) *MockCompetitionParamRepo_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_GetByKey_Call) Return(competitionParam *domain.CompetitionParam, err error) *MockCompetitionParamRepo_GetByKey_Call {
	_c.Call.Return(competitionParam, err)
	return _c
}

func (_c *MockCompetitionParamRepo_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.CompetitionParam, error)) *MockCompetitionParamRepo_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKeyForUpdate provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) GetByKeyForUpdate(ctx context.Context, key string) (*domain.CompetitionParam, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKeyForUpdate")
	}

	var r0 *domain.CompetitionParam
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.CompetitionParam, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.CompetitionParam); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CompetitionParam)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompetitionParamRepo_GetByKeyForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKeyForUpdate'
type MockCompetitionParamRepo_GetByKeyForUpdate_Call struct {
	*mock.Call
}

// GetByKeyForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCompetitionParamRepo_Expecter) GetByKeyForUpdate(ctx interface{}, key interface{}) *MockCompetitionParamRepo_GetByKeyForUpdate_Call {
	return &MockCompetitionParamRepo_GetByKeyForUpdate_Call{Call: _e.mock.On("GetByKeyForUpdate", ctx, key)}
}

func (_c *MockCompetitionParamRepo_GetByKeyForUpdate_Call) Run(run func(ctx context.Context, key string)) *MockCompetitionParamRepo_GetByKeyForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_GetByKeyForUpdate_Call) Return(competitionParam *domain.CompetitionParam, err error) *MockCompetitionParamRepo_GetByKeyForUpdate_Call {
	_c.Call.Return(competitionParam, err)
	return _c
}

func (_c *MockCompetitionParamRepo_GetByKeyForUpdate_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.CompetitionParam, error)) *MockCompetitionParamRepo_GetByKeyForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockCompetitionParamRepo
func (_mock *MockCompetitionParamRepo) Upsert(ctx context.Context, p *domain.CompetitionParam) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CompetitionParam) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompetitionParamRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockCompetitionParamRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.CompetitionParam
func (_e *MockCompetitionParamRepo_Expecter) Upsert(ctx interface{}, p interface{}) *MockCompetitionParamRepo_Upsert_Call {
	return &MockCompetitionParamRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, p)}
}

func (_c *MockCompetitionParamRepo_Upsert_Call) Run(run func(ctx context.Context, p *domain.CompetitionParam)) *MockCompetitionParamRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CompetitionParam
		if args[1] != nil {
			arg1 = args[1].(*domain.CompetitionParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompetitionParamRepo_Upsert_Call) Return(err error) *MockCompetitionParamRepo_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompetitionParamRepo_Upsert_Call) RunAndReturn(run func(ctx context.Context, p *domain.CompetitionParam) error) *MockCompetitionParamRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
