// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"time"

	"github.com/TakuyaYagam1/AstroCTFb/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatisticsRepository creates a new instance of MockStatisticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatisticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatisticsRepository {
	mock := &MockStatisticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatisticsRepository is an autogenerated mock type for the StatisticsRepository type
type MockStatisticsRepository struct {
	mock.Mock
}

type MockStatisticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatisticsRepository) EXPECT() *MockStatisticsRepository_Expecter {
	return &MockStatisticsRepository_Expecter{mock: &_m.Mock}
}

// GetAdminStatisticsFunnel provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetAdminStatisticsFunnel(ctx context.Context, limit int, freezeTime *time.Time) (*domain.AdminStatisticsFunnel, error) {
	ret := _mock.Called(ctx, limit, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminStatisticsFunnel")
	}

	var r0 *domain.AdminStatisticsFunnel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *time.Time) (*domain.AdminStatisticsFunnel, error)); ok {
		return returnFunc(ctx, limit, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *time.Time) *domain.AdminStatisticsFunnel); ok {
		r0 = returnFunc(ctx, limit, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AdminStatisticsFunnel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *time.Time) error); ok {
		r1 = returnFunc(ctx, limit, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetAdminStatisticsFunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminStatisticsFunnel'
type MockStatisticsRepository_GetAdminStatisticsFunnel_Call struct {
	*mock.Call
}

// GetAdminStatisticsFunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetAdminStatisticsFunnel(ctx interface{}, limit interface{}, freezeTime interface{}) *MockStatisticsRepository_GetAdminStatisticsFunnel_Call {
	return &MockStatisticsRepository_GetAdminStatisticsFunnel_Call{Call: _e.mock.On("GetAdminStatisticsFunnel", ctx, limit, freezeTime)}
}

func (_c *MockStatisticsRepository_GetAdminStatisticsFunnel_Call) Run(run func(ctx context.Context, limit int, freezeTime *time.Time)) *MockStatisticsRepository_GetAdminStatisticsFunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetAdminStatisticsFunnel_Call) Return(adminStatisticsFunnel *domain.AdminStatisticsFunnel, err error) *MockStatisticsRepository_GetAdminStatisticsFunnel_Call {
	_c.Call.Return(adminStatisticsFunnel, err)
	return _c
}

func (_c *MockStatisticsRepository_GetAdminStatisticsFunnel_Call) RunAndReturn(run func(ctx context.Context, limit int, freezeTime *time.Time) (*domain.AdminStatisticsFunnel, error)) *MockStatisticsRepository_GetAdminStatisticsFunnel_Call {
	_c.Call.Return(run)
	return _c
}

// GetChallengeDetailStats provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetChallengeDetailStats(ctx context.Context, challengeID uuid.UUID, freezeTime *time.Time) (*domain.ChallengeDetailStats, error) {
	ret := _mock.Called(ctx, challengeID, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetChallengeDetailStats")
	}

	var r0 *domain.ChallengeDetailStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time) (*domain.ChallengeDetailStats, error)); ok {
		return returnFunc(ctx, challengeID, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time) *domain.ChallengeDetailStats); ok {
		r0 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChallengeDetailStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time) error); ok {
		r1 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetChallengeDetailStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChallengeDetailStats'
type MockStatisticsRepository_GetChallengeDetailStats_Call struct {
	*mock.Call
}

// GetChallengeDetailStats is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetChallengeDetailStats(ctx interface{}, challengeID interface{}, freezeTime interface{}) *MockStatisticsRepository_GetChallengeDetailStats_Call {
	return &MockStatisticsRepository_GetChallengeDetailStats_Call{Call: _e.mock.On("GetChallengeDetailStats", ctx, challengeID, freezeTime)}
}

func (_c *MockStatisticsRepository_GetChallengeDetailStats_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, freezeTime *time.Time)) *MockStatisticsRepository_GetChallengeDetailStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeDetailStats_Call) Return(challengeDetailStats *domain.ChallengeDetailStats, err error) *MockStatisticsRepository_GetChallengeDetailStats_Call {
	_c.Call.Return(challengeDetailStats, err)
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeDetailStats_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, freezeTime *time.Time) (*domain.ChallengeDetailStats, error)) *MockStatisticsRepository_GetChallengeDetailStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetChallengeSolvePercentages provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetChallengeSolvePercentages(ctx context.Context, freezeTime *time.Time) ([]*domain.ChallengeSolvePercentage, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetChallengeSolvePercentages")
	}

	var r0 []*domain.ChallengeSolvePercentage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) ([]*domain.ChallengeSolvePercentage, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) []*domain.ChallengeSolvePercentage); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ChallengeSolvePercentage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetChallengeSolvePercentages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChallengeSolvePercentages'
type MockStatisticsRepository_GetChallengeSolvePercentages_Call struct {
	*mock.Call
}

// GetChallengeSolvePercentages is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetChallengeSolvePercentages(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetChallengeSolvePercentages_Call {
	return &MockStatisticsRepository_GetChallengeSolvePercentages_Call{Call: _e.mock.On("GetChallengeSolvePercentages", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetChallengeSolvePercentages_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetChallengeSolvePercentages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeSolvePercentages_Call) Return(challengeSolvePercentages []*domain.ChallengeSolvePercentage, err error) *MockStatisticsRepository_GetChallengeSolvePercentages_Call {
	_c.Call.Return(challengeSolvePercentages, err)
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeSolvePercentages_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) ([]*domain.ChallengeSolvePercentage, error)) *MockStatisticsRepository_GetChallengeSolvePercentages_Call {
	_c.Call.Return(run)
	return _c
}

// GetChallengeStats provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetChallengeStats(ctx context.Context, freezeTime *time.Time) ([]*domain.ChallengeStats, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetChallengeStats")
	}

	var r0 []*domain.ChallengeStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) ([]*domain.ChallengeStats, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) []*domain.ChallengeStats); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ChallengeStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetChallengeStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChallengeStats'
type MockStatisticsRepository_GetChallengeStats_Call struct {
	*mock.Call
}

// GetChallengeStats is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetChallengeStats(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetChallengeStats_Call {
	return &MockStatisticsRepository_GetChallengeStats_Call{Call: _e.mock.On("GetChallengeStats", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetChallengeStats_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetChallengeStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeStats_Call) Return(challengeStatss []*domain.ChallengeStats, err error) *MockStatisticsRepository_GetChallengeStats_Call {
	_c.Call.Return(challengeStatss, err)
	return _c
}

func (_c *MockStatisticsRepository_GetChallengeStats_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) ([]*domain.ChallengeStats, error)) *MockStatisticsRepository_GetChallengeStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetGeneralStats provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetGeneralStats(ctx context.Context, freezeTime *time.Time) (*domain.GeneralStats, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetGeneralStats")
	}

	var r0 *domain.GeneralStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) (*domain.GeneralStats, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) *domain.GeneralStats); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GeneralStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetGeneralStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGeneralStats'
type MockStatisticsRepository_GetGeneralStats_Call struct {
	*mock.Call
}

// GetGeneralStats is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetGeneralStats(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetGeneralStats_Call {
	return &MockStatisticsRepository_GetGeneralStats_Call{Call: _e.mock.On("GetGeneralStats", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetGeneralStats_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetGeneralStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetGeneralStats_Call) Return(generalStats *domain.GeneralStats, err error) *MockStatisticsRepository_GetGeneralStats_Call {
	_c.Call.Return(generalStats, err)
	return _c
}

func (_c *MockStatisticsRepository_GetGeneralStats_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) (*domain.GeneralStats, error)) *MockStatisticsRepository_GetGeneralStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreDistribution provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetScoreDistribution(ctx context.Context, freezeTime *time.Time) ([]*domain.ScoreDistributionBucket, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreDistribution")
	}

	var r0 []*domain.ScoreDistributionBucket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) ([]*domain.ScoreDistributionBucket, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) []*domain.ScoreDistributionBucket); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ScoreDistributionBucket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetScoreDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreDistribution'
type MockStatisticsRepository_GetScoreDistribution_Call struct {
	*mock.Call
}

// GetScoreDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetScoreDistribution(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetScoreDistribution_Call {
	return &MockStatisticsRepository_GetScoreDistribution_Call{Call: _e.mock.On("GetScoreDistribution", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetScoreDistribution_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetScoreDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetScoreDistribution_Call) Return(scoreDistributionBuckets []*domain.ScoreDistributionBucket, err error) *MockStatisticsRepository_GetScoreDistribution_Call {
	_c.Call.Return(scoreDistributionBuckets, err)
	return _c
}

func (_c *MockStatisticsRepository_GetScoreDistribution_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) ([]*domain.ScoreDistributionBucket, error)) *MockStatisticsRepository_GetScoreDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreboardHistory provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetScoreboardHistory(ctx context.Context, limit int, freezeTime *time.Time) ([]*domain.ScoreboardHistoryEntry, error) {
	ret := _mock.Called(ctx, limit, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreboardHistory")
	}

	var r0 []*domain.ScoreboardHistoryEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *time.Time) ([]*domain.ScoreboardHistoryEntry, error)); ok {
		return returnFunc(ctx, limit, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *time.Time) []*domain.ScoreboardHistoryEntry); ok {
		r0 = returnFunc(ctx, limit, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ScoreboardHistoryEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *time.Time) error); ok {
		r1 = returnFunc(ctx, limit, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetScoreboardHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreboardHistory'
type MockStatisticsRepository_GetScoreboardHistory_Call struct {
	*mock.Call
}

// GetScoreboardHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetScoreboardHistory(ctx interface{}, limit interface{}, freezeTime interface{}) *MockStatisticsRepository_GetScoreboardHistory_Call {
	return &MockStatisticsRepository_GetScoreboardHistory_Call{Call: _e.mock.On("GetScoreboardHistory", ctx, limit, freezeTime)}
}

func (_c *MockStatisticsRepository_GetScoreboardHistory_Call) Run(run func(ctx context.Context, limit int, freezeTime *time.Time)) *MockStatisticsRepository_GetScoreboardHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetScoreboardHistory_Call) Return(scoreboardHistoryEntrys []*domain.ScoreboardHistoryEntry, err error) *MockStatisticsRepository_GetScoreboardHistory_Call {
	_c.Call.Return(scoreboardHistoryEntrys, err)
	return _c
}

func (_c *MockStatisticsRepository_GetScoreboardHistory_Call) RunAndReturn(run func(ctx context.Context, limit int, freezeTime *time.Time) ([]*domain.ScoreboardHistoryEntry, error)) *MockStatisticsRepository_GetScoreboardHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSolveMatrix provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetSolveMatrix(ctx context.Context, freezeTime *time.Time) ([]*domain.SolveMatrixRow, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetSolveMatrix")
	}

	var r0 []*domain.SolveMatrixRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) ([]*domain.SolveMatrixRow, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) []*domain.SolveMatrixRow); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SolveMatrixRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetSolveMatrix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSolveMatrix'
type MockStatisticsRepository_GetSolveMatrix_Call struct {
	*mock.Call
}

// GetSolveMatrix is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetSolveMatrix(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetSolveMatrix_Call {
	return &MockStatisticsRepository_GetSolveMatrix_Call{Call: _e.mock.On("GetSolveMatrix", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetSolveMatrix_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetSolveMatrix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetSolveMatrix_Call) Return(solveMatrixRows []*domain.SolveMatrixRow, err error) *MockStatisticsRepository_GetSolveMatrix_Call {
	_c.Call.Return(solveMatrixRows, err)
	return _c
}

func (_c *MockStatisticsRepository_GetSolveMatrix_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) ([]*domain.SolveMatrixRow, error)) *MockStatisticsRepository_GetSolveMatrix_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubmissionTimeSeries provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetSubmissionTimeSeries(ctx context.Context, freezeTime *time.Time) (*domain.SubmissionTimeSeriesStats, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmissionTimeSeries")
	}

	var r0 *domain.SubmissionTimeSeriesStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) (*domain.SubmissionTimeSeriesStats, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time) *domain.SubmissionTimeSeriesStats); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SubmissionTimeSeriesStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetSubmissionTimeSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubmissionTimeSeries'
type MockStatisticsRepository_GetSubmissionTimeSeries_Call struct {
	*mock.Call
}

// GetSubmissionTimeSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetSubmissionTimeSeries(ctx interface{}, freezeTime interface{}) *MockStatisticsRepository_GetSubmissionTimeSeries_Call {
	return &MockStatisticsRepository_GetSubmissionTimeSeries_Call{Call: _e.mock.On("GetSubmissionTimeSeries", ctx, freezeTime)}
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeries_Call) Run(run func(ctx context.Context, freezeTime *time.Time)) *MockStatisticsRepository_GetSubmissionTimeSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeries_Call) Return(submissionTimeSeriesStats *domain.SubmissionTimeSeriesStats, err error) *MockStatisticsRepository_GetSubmissionTimeSeries_Call {
	_c.Call.Return(submissionTimeSeriesStats, err)
	return _c
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeries_Call) RunAndReturn(run func(ctx context.Context, freezeTime *time.Time) (*domain.SubmissionTimeSeriesStats, error)) *MockStatisticsRepository_GetSubmissionTimeSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubmissionTimeSeriesByType provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetSubmissionTimeSeriesByType(ctx context.Context, isCorrect bool, freezeTime *time.Time) ([]*domain.RegistrationTimePoint, error) {
	ret := _mock.Called(ctx, isCorrect, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmissionTimeSeriesByType")
	}

	var r0 []*domain.RegistrationTimePoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Time) ([]*domain.RegistrationTimePoint, error)); ok {
		return returnFunc(ctx, isCorrect, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Time) []*domain.RegistrationTimePoint); ok {
		r0 = returnFunc(ctx, isCorrect, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RegistrationTimePoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Time) error); ok {
		r1 = returnFunc(ctx, isCorrect, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubmissionTimeSeriesByType'
type MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call struct {
	*mock.Call
}

// GetSubmissionTimeSeriesByType is a helper method to define mock.On call
//   - ctx context.Context
//   - isCorrect bool
//   - freezeTime *time.Time
func (_e *MockStatisticsRepository_Expecter) GetSubmissionTimeSeriesByType(ctx interface{}, isCorrect interface{}, freezeTime interface{}) *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call {
	return &MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call{Call: _e.mock.On("GetSubmissionTimeSeriesByType", ctx, isCorrect, freezeTime)}
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call) Run(run func(ctx context.Context, isCorrect bool, freezeTime *time.Time)) *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call) Return(registrationTimePoints []*domain.RegistrationTimePoint, err error) *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call {
	_c.Call.Return(registrationTimePoints, err)
	return _c
}

func (_c *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call) RunAndReturn(run func(ctx context.Context, isCorrect bool, freezeTime *time.Time) ([]*domain.RegistrationTimePoint, error)) *MockStatisticsRepository_GetSubmissionTimeSeriesByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamRegistrationTimeSeries provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetTeamRegistrationTimeSeries(ctx context.Context) ([]*domain.RegistrationTimePoint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamRegistrationTimeSeries")
	}

	var r0 []*domain.RegistrationTimePoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.RegistrationTimePoint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.RegistrationTimePoint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RegistrationTimePoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamRegistrationTimeSeries'
type MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call struct {
	*mock.Call
}

// GetTeamRegistrationTimeSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatisticsRepository_Expecter) GetTeamRegistrationTimeSeries(ctx interface{}) *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call {
	return &MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call{Call: _e.mock.On("GetTeamRegistrationTimeSeries", ctx)}
}

func (_c *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call) Run(run func(ctx context.Context)) *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call) Return(registrationTimePoints []*domain.RegistrationTimePoint, err error) *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call {
	_c.Call.Return(registrationTimePoints, err)
	return _c
}

func (_c *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.RegistrationTimePoint, error)) *MockStatisticsRepository_GetTeamRegistrationTimeSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRegistrationTimeSeries provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetUserRegistrationTimeSeries(ctx context.Context) ([]*domain.RegistrationTimePoint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRegistrationTimeSeries")
	}

	var r0 []*domain.RegistrationTimePoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.RegistrationTimePoint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.RegistrationTimePoint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RegistrationTimePoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetUserRegistrationTimeSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRegistrationTimeSeries'
type MockStatisticsRepository_GetUserRegistrationTimeSeries_Call struct {
	*mock.Call
}

// GetUserRegistrationTimeSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatisticsRepository_Expecter) GetUserRegistrationTimeSeries(ctx interface{}) *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call {
	return &MockStatisticsRepository_GetUserRegistrationTimeSeries_Call{Call: _e.mock.On("GetUserRegistrationTimeSeries", ctx)}
}

func (_c *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call) Run(run func(ctx context.Context)) *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call) Return(registrationTimePoints []*domain.RegistrationTimePoint, err error) *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call {
	_c.Call.Return(registrationTimePoints, err)
	return _c
}

func (_c *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.RegistrationTimePoint, error)) *MockStatisticsRepository_GetUserRegistrationTimeSeries_Call {
	_c.Call.Return(run)
	return _c
}
