// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVaultSecretGetter creates a new instance of MockVaultSecretGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultSecretGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultSecretGetter {
	mock := &MockVaultSecretGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVaultSecretGetter is an autogenerated mock type for the vaultSecretGetter type
type MockVaultSecretGetter struct {
	mock.Mock
}

type MockVaultSecretGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultSecretGetter) EXPECT() *MockVaultSecretGetter_Expecter {
	return &MockVaultSecretGetter_Expecter{mock: &_m.Mock}
}

// GetSecret provides a mock function for the type MockVaultSecretGetter
func (_mock *MockVaultSecretGetter) GetSecret(ctx context.Context, path string) (map[string]any, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]any, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]any); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultSecretGetter_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockVaultSecretGetter_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockVaultSecretGetter_Expecter) GetSecret(ctx interface{}, path interface{}) *MockVaultSecretGetter_GetSecret_Call {
	return &MockVaultSecretGetter_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, path)}
}

func (_c *MockVaultSecretGetter_GetSecret_Call) Run(run func(ctx context.Context, path string)) *MockVaultSecretGetter_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultSecretGetter_GetSecret_Call) Return(stringToV map[string]any, err error) *MockVaultSecretGetter_GetSecret_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockVaultSecretGetter_GetSecret_Call) RunAndReturn(run func(ctx context.Context, path string) (map[string]any, error)) *MockVaultSecretGetter_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}
