// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/skr1ms/CTFBoard/internal/entity"
	"github.com/skr1ms/CTFBoard/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSolveRepository creates a new instance of MockSolveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSolveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSolveRepository {
	mock := &MockSolveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSolveRepository is an autogenerated mock type for the SolveRepository type
type MockSolveRepository struct {
	mock.Mock
}

type MockSolveRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSolveRepository) EXPECT() *MockSolveRepository_Expecter {
	return &MockSolveRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) Create(ctx context.Context, solve *entity.Solve) error {
	ret := _mock.Called(ctx, solve)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Solve) error); ok {
		r0 = returnFunc(ctx, solve)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSolveRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSolveRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - solve *entity.Solve
func (_e *MockSolveRepository_Expecter) Create(ctx interface{}, solve interface{}) *MockSolveRepository_Create_Call {
	return &MockSolveRepository_Create_Call{Call: _e.mock.On("Create", ctx, solve)}
}

func (_c *MockSolveRepository_Create_Call) Run(run func(ctx context.Context, solve *entity.Solve)) *MockSolveRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Solve
		if args[1] != nil {
			arg1 = args[1].(*entity.Solve)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_Create_Call) Return(err error) *MockSolveRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSolveRepository_Create_Call) RunAndReturn(run func(ctx context.Context, solve *entity.Solve) error) *MockSolveRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetAll(ctx context.Context) ([]*entity.Solve, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Solve
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Solve, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Solve); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Solve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSolveRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSolveRepository_Expecter) GetAll(ctx interface{}) *MockSolveRepository_GetAll_Call {
	return &MockSolveRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockSolveRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockSolveRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetAll_Call) Return(solves []*entity.Solve, err error) *MockSolveRepository_GetAll_Call {
	_c.Call.Return(solves, err)
	return _c
}

func (_c *MockSolveRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Solve, error)) *MockSolveRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetByID(ctx context.Context, ID uuid.UUID) (*entity.Solve, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Solve
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Solve, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Solve); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Solve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSolveRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockSolveRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockSolveRepository_GetByID_Call {
	return &MockSolveRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockSolveRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockSolveRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetByID_Call) Return(solve *entity.Solve, err error) *MockSolveRepository_GetByID_Call {
	_c.Call.Return(solve, err)
	return _c
}

func (_c *MockSolveRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*entity.Solve, error)) *MockSolveRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeamAndChallenge provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetByTeamAndChallenge(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) (*entity.Solve, error) {
	ret := _mock.Called(ctx, teamID, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamAndChallenge")
	}

	var r0 *entity.Solve
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Solve, error)); ok {
		return returnFunc(ctx, teamID, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Solve); ok {
		r0 = returnFunc(ctx, teamID, challengeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Solve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamID, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetByTeamAndChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamAndChallenge'
type MockSolveRepository_GetByTeamAndChallenge_Call struct {
	*mock.Call
}

// GetByTeamAndChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - challengeID uuid.UUID
func (_e *MockSolveRepository_Expecter) GetByTeamAndChallenge(ctx interface{}, teamID interface{}, challengeID interface{}) *MockSolveRepository_GetByTeamAndChallenge_Call {
	return &MockSolveRepository_GetByTeamAndChallenge_Call{Call: _e.mock.On("GetByTeamAndChallenge", ctx, teamID, challengeID)}
}

func (_c *MockSolveRepository_GetByTeamAndChallenge_Call) Run(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID)) *MockSolveRepository_GetByTeamAndChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetByTeamAndChallenge_Call) Return(solve *entity.Solve, err error) *MockSolveRepository_GetByTeamAndChallenge_Call {
	_c.Call.Return(solve, err)
	return _c
}

func (_c *MockSolveRepository_GetByTeamAndChallenge_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) (*entity.Solve, error)) *MockSolveRepository_GetByTeamAndChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.Solve, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.Solve
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Solve, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Solve); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Solve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockSolveRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSolveRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockSolveRepository_GetByUserID_Call {
	return &MockSolveRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockSolveRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSolveRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetByUserID_Call) Return(solves []*entity.Solve, err error) *MockSolveRepository_GetByUserID_Call {
	_c.Call.Return(solves, err)
	return _c
}

func (_c *MockSolveRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Solve, error)) *MockSolveRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstBlood provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetFirstBlood(ctx context.Context, challengeID uuid.UUID) (*repo.FirstBloodEntry, error) {
	ret := _mock.Called(ctx, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstBlood")
	}

	var r0 *repo.FirstBloodEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repo.FirstBloodEntry, error)); ok {
		return returnFunc(ctx, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repo.FirstBloodEntry); ok {
		r0 = returnFunc(ctx, challengeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.FirstBloodEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetFirstBlood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstBlood'
type MockSolveRepository_GetFirstBlood_Call struct {
	*mock.Call
}

// GetFirstBlood is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
func (_e *MockSolveRepository_Expecter) GetFirstBlood(ctx interface{}, challengeID interface{}) *MockSolveRepository_GetFirstBlood_Call {
	return &MockSolveRepository_GetFirstBlood_Call{Call: _e.mock.On("GetFirstBlood", ctx, challengeID)}
}

func (_c *MockSolveRepository_GetFirstBlood_Call) Run(run func(ctx context.Context, challengeID uuid.UUID)) *MockSolveRepository_GetFirstBlood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetFirstBlood_Call) Return(firstBloodEntry *repo.FirstBloodEntry, err error) *MockSolveRepository_GetFirstBlood_Call {
	_c.Call.Return(firstBloodEntry, err)
	return _c
}

func (_c *MockSolveRepository_GetFirstBlood_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID) (*repo.FirstBloodEntry, error)) *MockSolveRepository_GetFirstBlood_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreboard provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetScoreboard(ctx context.Context) ([]*repo.ScoreboardEntry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreboard")
	}

	var r0 []*repo.ScoreboardEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*repo.ScoreboardEntry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*repo.ScoreboardEntry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repo.ScoreboardEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetScoreboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreboard'
type MockSolveRepository_GetScoreboard_Call struct {
	*mock.Call
}

// GetScoreboard is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSolveRepository_Expecter) GetScoreboard(ctx interface{}) *MockSolveRepository_GetScoreboard_Call {
	return &MockSolveRepository_GetScoreboard_Call{Call: _e.mock.On("GetScoreboard", ctx)}
}

func (_c *MockSolveRepository_GetScoreboard_Call) Run(run func(ctx context.Context)) *MockSolveRepository_GetScoreboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetScoreboard_Call) Return(scoreboardEntrys []*repo.ScoreboardEntry, err error) *MockSolveRepository_GetScoreboard_Call {
	_c.Call.Return(scoreboardEntrys, err)
	return _c
}

func (_c *MockSolveRepository_GetScoreboard_Call) RunAndReturn(run func(ctx context.Context) ([]*repo.ScoreboardEntry, error)) *MockSolveRepository_GetScoreboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreboardFrozen provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetScoreboardFrozen(ctx context.Context, freezeTime time.Time) ([]*repo.ScoreboardEntry, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreboardFrozen")
	}

	var r0 []*repo.ScoreboardEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]*repo.ScoreboardEntry, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []*repo.ScoreboardEntry); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repo.ScoreboardEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetScoreboardFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreboardFrozen'
type MockSolveRepository_GetScoreboardFrozen_Call struct {
	*mock.Call
}

// GetScoreboardFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime time.Time
func (_e *MockSolveRepository_Expecter) GetScoreboardFrozen(ctx interface{}, freezeTime interface{}) *MockSolveRepository_GetScoreboardFrozen_Call {
	return &MockSolveRepository_GetScoreboardFrozen_Call{Call: _e.mock.On("GetScoreboardFrozen", ctx, freezeTime)}
}

func (_c *MockSolveRepository_GetScoreboardFrozen_Call) Run(run func(ctx context.Context, freezeTime time.Time)) *MockSolveRepository_GetScoreboardFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetScoreboardFrozen_Call) Return(scoreboardEntrys []*repo.ScoreboardEntry, err error) *MockSolveRepository_GetScoreboardFrozen_Call {
	_c.Call.Return(scoreboardEntrys, err)
	return _c
}

func (_c *MockSolveRepository_GetScoreboardFrozen_Call) RunAndReturn(run func(ctx context.Context, freezeTime time.Time) ([]*repo.ScoreboardEntry, error)) *MockSolveRepository_GetScoreboardFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamScore provides a mock function for the type MockSolveRepository
func (_mock *MockSolveRepository) GetTeamScore(ctx context.Context, teamID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamScore")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolveRepository_GetTeamScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamScore'
type MockSolveRepository_GetTeamScore_Call struct {
	*mock.Call
}

// GetTeamScore is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSolveRepository_Expecter) GetTeamScore(ctx interface{}, teamID interface{}) *MockSolveRepository_GetTeamScore_Call {
	return &MockSolveRepository_GetTeamScore_Call{Call: _e.mock.On("GetTeamScore", ctx, teamID)}
}

func (_c *MockSolveRepository_GetTeamScore_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSolveRepository_GetTeamScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolveRepository_GetTeamScore_Call) Return(n int, err error) *MockSolveRepository_GetTeamScore_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSolveRepository_GetTeamScore_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) (int, error)) *MockSolveRepository_GetTeamScore_Call {
	_c.Call.Return(run)
	return _c
}
