// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ban_appeals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBanAppeals = `-- name: CountBanAppeals :one
SELECT COUNT(*) FROM ban_appeals
`

func (q *Queries) CountBanAppeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBanAppeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBanAppealsByDecision = `-- name: CountBanAppealsByDecision :one
SELECT COUNT(*) FROM ban_appeals WHERE decision = $1
`

func (q *Queries) CountBanAppealsByDecision(ctx context.Context, decision string) (int64, error) {
	row := q.db.QueryRow(ctx, countBanAppealsByDecision, decision)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBanAppeal = `-- name: CreateBanAppeal :one
INSERT INTO ban_appeals (user_id, message)
VALUES ($1, $2)
RETURNING id, user_id, message, created_at, reviewed_at, admin_response, decision
`

type CreateBanAppealParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Message string    `json:"message"`
}

func (q *Queries) CreateBanAppeal(ctx context.Context, arg CreateBanAppealParams) (BanAppeal, error) {
	row := q.db.QueryRow(ctx, createBanAppeal, arg.UserID, arg.Message)
	var i BanAppeal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.AdminResponse,
		&i.Decision,
	)
	return i, err
}

const getBanAppealByID = `-- name: GetBanAppealByID :one
SELECT id, user_id, message, created_at, reviewed_at, admin_response, decision
FROM ban_appeals
WHERE id = $1
`

func (q *Queries) GetBanAppealByID(ctx context.Context, id uuid.UUID) (BanAppeal, error) {
	row := q.db.QueryRow(ctx, getBanAppealByID, id)
	var i BanAppeal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.AdminResponse,
		&i.Decision,
	)
	return i, err
}

const getBanAppealsByUserID = `-- name: GetBanAppealsByUserID :many
SELECT id, user_id, message, created_at, reviewed_at, admin_response, decision
FROM ban_appeals
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBanAppealsByUserID(ctx context.Context, userID uuid.UUID) ([]BanAppeal, error) {
	rows, err := q.db.Query(ctx, getBanAppealsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BanAppeal
	for rows.Next() {
		var i BanAppeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.AdminResponse,
			&i.Decision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBanAppealByUserID = `-- name: GetLatestBanAppealByUserID :one
SELECT id, user_id, message, created_at, reviewed_at, admin_response, decision
FROM ban_appeals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBanAppealByUserID(ctx context.Context, userID uuid.UUID) (BanAppeal, error) {
	row := q.db.QueryRow(ctx, getLatestBanAppealByUserID, userID)
	var i BanAppeal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.AdminResponse,
		&i.Decision,
	)
	return i, err
}

const listBanAppeals = `-- name: ListBanAppeals :many
SELECT id, user_id, message, created_at, reviewed_at, admin_response, decision
FROM ban_appeals
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBanAppealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBanAppeals(ctx context.Context, arg ListBanAppealsParams) ([]BanAppeal, error) {
	rows, err := q.db.Query(ctx, listBanAppeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BanAppeal
	for rows.Next() {
		var i BanAppeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.AdminResponse,
			&i.Decision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBanAppealsByDecision = `-- name: ListBanAppealsByDecision :many
SELECT id, user_id, message, created_at, reviewed_at, admin_response, decision
FROM ban_appeals
WHERE decision = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBanAppealsByDecisionParams struct {
	Decision string `json:"decision"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListBanAppealsByDecision(ctx context.Context, arg ListBanAppealsByDecisionParams) ([]BanAppeal, error) {
	rows, err := q.db.Query(ctx, listBanAppealsByDecision, arg.Decision, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BanAppeal
	for rows.Next() {
		var i BanAppeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.AdminResponse,
			&i.Decision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBanAppeal = `-- name: UpdateBanAppeal :execrows
UPDATE ban_appeals
SET decision = $2, admin_response = $3, reviewed_at = $4
WHERE id = $1
`

type UpdateBanAppealParams struct {
	ID            uuid.UUID          `json:"id"`
	Decision      string             `json:"decision"`
	AdminResponse *string            `json:"admin_response"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
}

func (q *Queries) UpdateBanAppeal(ctx context.Context, arg UpdateBanAppealParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBanAppeal,
		arg.ID,
		arg.Decision,
		arg.AdminResponse,
		arg.ReviewedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
