// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package sqlc

import (
	"context"
	"time"
)

const getCompetition = `-- name: GetCompetition :one
SELECT id, name, start_time, end_time, freeze_time, is_paused, is_public,
       flag_regex, mode, allow_team_switch, min_team_size, max_team_size, created_at, updated_at
FROM competition
WHERE id = 1
`

func (q *Queries) GetCompetition(ctx context.Context) (Competition, error) {
	row := q.db.QueryRow(ctx, getCompetition)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.FreezeTime,
		&i.IsPaused,
		&i.IsPublic,
		&i.FlagRegex,
		&i.Mode,
		&i.AllowTeamSwitch,
		&i.MinTeamSize,
		&i.MaxTeamSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetition = `-- name: UpdateCompetition :exec
UPDATE competition SET
    name = $1,
    start_time = $2,
    end_time = $3,
    freeze_time = $4,
    is_paused = $5,
    is_public = $6,
    flag_regex = $7,
    mode = $8,
    allow_team_switch = $9,
    min_team_size = $10,
    max_team_size = $11,
    updated_at = $12
WHERE id = 1
`

type UpdateCompetitionParams struct {
	Name            string     `json:"name"`
	StartTime       *time.Time `json:"start_time"`
	EndTime         *time.Time `json:"end_time"`
	FreezeTime      *time.Time `json:"freeze_time"`
	IsPaused        *bool      `json:"is_paused"`
	IsPublic        *bool      `json:"is_public"`
	FlagRegex       *string    `json:"flag_regex"`
	Mode            *string    `json:"mode"`
	AllowTeamSwitch *bool      `json:"allow_team_switch"`
	MinTeamSize     *int32     `json:"min_team_size"`
	MaxTeamSize     *int32     `json:"max_team_size"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

func (q *Queries) UpdateCompetition(ctx context.Context, arg UpdateCompetitionParams) error {
	_, err := q.db.Exec(ctx, updateCompetition,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.FreezeTime,
		arg.IsPaused,
		arg.IsPublic,
		arg.FlagRegex,
		arg.Mode,
		arg.AllowTeamSwitch,
		arg.MinTeamSize,
		arg.MaxTeamSize,
		arg.UpdatedAt,
	)
	return err
}
