// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_params.sql

package sqlc

import (
	"context"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM configs WHERE key = $1
`

func (q *Queries) DeleteConfig(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteConfig, key)
	return err
}

const getAllConfigs = `-- name: GetAllConfigs :many
SELECT key, value, value_type, description, category, updated_at
FROM configs ORDER BY key ASC
`

func (q *Queries) GetAllConfigs(ctx context.Context) ([]CompetitionParam, error) {
	rows, err := q.db.Query(ctx, getAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionParam
	for rows.Next() {
		var i CompetitionParam
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Description,
			&i.Category,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigByKey = `-- name: GetConfigByKey :one
SELECT key, value, value_type, description, category, updated_at
FROM configs WHERE key = $1
`

func (q *Queries) GetConfigByKey(ctx context.Context, key string) (CompetitionParam, error) {
	row := q.db.QueryRow(ctx, getConfigByKey, key)
	var i CompetitionParam
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Description,
		&i.Category,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigByKeyForUpdate = `-- name: GetConfigByKeyForUpdate :one
SELECT key, value, value_type, description, category, updated_at
FROM configs WHERE key = $1 FOR UPDATE
`

func (q *Queries) GetConfigByKeyForUpdate(ctx context.Context, key string) (CompetitionParam, error) {
	row := q.db.QueryRow(ctx, getConfigByKeyForUpdate, key)
	var i CompetitionParam
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Description,
		&i.Category,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO configs (key, value, value_type, description, category, updated_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    value_type = EXCLUDED.value_type,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertConfigParams struct {
	Key         string  `json:"key"`
	Value       string  `json:"value"`
	ValueType   string  `json:"value_type"`
	Description *string `json:"description"`
	Category    string  `json:"category"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.Exec(ctx, upsertConfig,
		arg.Key,
		arg.Value,
		arg.ValueType,
		arg.Description,
		arg.Category,
	)
	return err
}
