// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solutions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteSolution = `-- name: DeleteSolution :exec
DELETE FROM solutions WHERE challenge_id = $1
`

func (q *Queries) DeleteSolution(ctx context.Context, challengeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSolution, challengeID)
	return err
}

const getAllSolutions = `-- name: GetAllSolutions :many
SELECT id, challenge_id, content FROM solutions ORDER BY challenge_id
`

func (q *Queries) GetAllSolutions(ctx context.Context) ([]Solution, error) {
	rows, err := q.db.Query(ctx, getAllSolutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(&i.ID, &i.ChallengeID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSolutionByChallengeID = `-- name: GetSolutionByChallengeID :one
SELECT id, challenge_id, content FROM solutions WHERE challenge_id = $1
`

func (q *Queries) GetSolutionByChallengeID(ctx context.Context, challengeID uuid.UUID) (Solution, error) {
	row := q.db.QueryRow(ctx, getSolutionByChallengeID, challengeID)
	var i Solution
	err := row.Scan(&i.ID, &i.ChallengeID, &i.Content)
	return i, err
}

const getSolutionsByTeamID = `-- name: GetSolutionsByTeamID :many
SELECT
    s.challenge_id,
    s.content,
    c.title    AS challenge_title,
    c.category AS challenge_category
FROM solutions s
JOIN challenges c ON c.id = s.challenge_id
WHERE c.is_hidden = false
  AND EXISTS (
    SELECT 1 FROM solves sv
    WHERE sv.challenge_id = s.challenge_id
      AND sv.team_id = $1
      AND sv.banned_team_id IS NULL AND sv.banned_user_id IS NULL
)
ORDER BY c.category, c.title
`

type GetSolutionsByTeamIDRow struct {
	ChallengeID       uuid.UUID `json:"challenge_id"`
	Content           string    `json:"content"`
	ChallengeTitle    string    `json:"challenge_title"`
	ChallengeCategory *string   `json:"challenge_category"`
}

func (q *Queries) GetSolutionsByTeamID(ctx context.Context, teamID uuid.UUID) ([]GetSolutionsByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, getSolutionsByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSolutionsByTeamIDRow
	for rows.Next() {
		var i GetSolutionsByTeamIDRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.Content,
			&i.ChallengeTitle,
			&i.ChallengeCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWriteupFilesByIDs = `-- name: GetWriteupFilesByIDs :many
SELECT id, type, challenge_id, location, filename, size, sha256, created_at FROM files
WHERE type = 'writeup'
  AND challenge_id = ANY($1::uuid[])
ORDER BY challenge_id, created_at
`

func (q *Queries) GetWriteupFilesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getWriteupFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ChallengeID,
			&i.Location,
			&i.Filename,
			&i.Size,
			&i.SHA256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSolution = `-- name: UpsertSolution :one
INSERT INTO solutions (challenge_id, content)
VALUES ($1, $2)
ON CONFLICT (challenge_id) DO UPDATE SET content = EXCLUDED.content
RETURNING id, challenge_id, content
`

type UpsertSolutionParams struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
	Content     string    `json:"content"`
}

func (q *Queries) UpsertSolution(ctx context.Context, arg UpsertSolutionParams) (Solution, error) {
	row := q.db.QueryRow(ctx, upsertSolution, arg.ChallengeID, arg.Content)
	var i Solution
	err := row.Scan(&i.ID, &i.ChallengeID, &i.Content)
	return i, err
}
