// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/skr1ms/CTFBoard/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppSettingsRepository creates a new instance of MockAppSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppSettingsRepository {
	mock := &MockAppSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppSettingsRepository is an autogenerated mock type for the AppSettingsRepository type
type MockAppSettingsRepository struct {
	mock.Mock
}

type MockAppSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppSettingsRepository) EXPECT() *MockAppSettingsRepository_Expecter {
	return &MockAppSettingsRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAppSettingsRepository
func (_mock *MockAppSettingsRepository) Get(ctx context.Context) (*entity.AppSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.AppSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entity.AppSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entity.AppSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AppSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppSettingsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAppSettingsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAppSettingsRepository_Expecter) Get(ctx interface{}) *MockAppSettingsRepository_Get_Call {
	return &MockAppSettingsRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockAppSettingsRepository_Get_Call) Run(run func(ctx context.Context)) *MockAppSettingsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppSettingsRepository_Get_Call) Return(appSettings *entity.AppSettings, err error) *MockAppSettingsRepository_Get_Call {
	_c.Call.Return(appSettings, err)
	return _c
}

func (_c *MockAppSettingsRepository_Get_Call) RunAndReturn(run func(ctx context.Context) (*entity.AppSettings, error)) *MockAppSettingsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAppSettingsRepository
func (_mock *MockAppSettingsRepository) Update(ctx context.Context, s *entity.AppSettings) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.AppSettings) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppSettingsRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAppSettingsRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s *entity.AppSettings
func (_e *MockAppSettingsRepository_Expecter) Update(ctx interface{}, s interface{}) *MockAppSettingsRepository_Update_Call {
	return &MockAppSettingsRepository_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *MockAppSettingsRepository_Update_Call) Run(run func(ctx context.Context, s *entity.AppSettings)) *MockAppSettingsRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.AppSettings
		if args[1] != nil {
			arg1 = args[1].(*entity.AppSettings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppSettingsRepository_Update_Call) Return(err error) *MockAppSettingsRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppSettingsRepository_Update_Call) RunAndReturn(run func(ctx context.Context, s *entity.AppSettings) error) *MockAppSettingsRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
