#!/bin/sh
set -e

# ---------------------------------------------------------------------------
# CTF Platform HAProxy entrypoint
#
# Generates per-deployment map files (IP allow-lists, CDN CIDRs) and the
# main frontend config, then starts HAProxy in master-worker mode.
# ---------------------------------------------------------------------------

mkdir -p /var/run/haproxy /var/lib/haproxy /etc/haproxy/maps /etc/haproxy/certs

write_map_file() {
    value="$1"
    target="$2"
    printf '%s\n' "$value" | tr ', ' '\n\n' | awk 'NF' > "$target"
}

# Admin IP allow-list: space/comma-separated CIDRs.
# Default covers all RFC-1918 ranges + loopback.
write_map_file "${ADMIN_ALLOWED_IPS:-10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 127.0.0.1/32}" /etc/haproxy/maps/admin_ips.txt

# Vault admin IP(s) - defaults to loopback only.
write_map_file "${VAULT_ADMIN_IP:-127.0.0.1}" /etc/haproxy/maps/vault_ips.txt

# Trusted CDN CIDRs (DDoS-Guard, Cloudflare, etc.).
# Empty = direct mode (track src). Non-empty = CDN mode (track XFF).
write_map_file "${TRUSTED_CDN_CIDRS:-}" /etc/haproxy/maps/cdn_cidrs.txt

DOMAIN="${DOMAIN:-localhost}"
API_DOMAIN="${API_DOMAIN:-api.${DOMAIN}}"
GRAFANA_DOMAIN="${GRAFANA_DOMAIN:-grafana.${DOMAIN}}"
VAULT_DOMAIN="${VAULT_DOMAIN:-vault.${DOMAIN}}"
S3_DOMAIN="${S3_DOMAIN:-s3.${DOMAIN}}"
HAPROXY_STATS_USER="${HAPROXY_STATS_USER:-admin}"
HAPROXY_STATS_PASSWORD="${HAPROXY_STATS_PASSWORD:?HAPROXY_STATS_PASSWORD is required}"
HAPROXY_EDGE_REQ_RATE_PER_MINUTE="${HAPROXY_EDGE_REQ_RATE_PER_MINUTE:-3000}"
HAPROXY_EDGE_CONN_RATE_PER_10S="${HAPROXY_EDGE_CONN_RATE_PER_10S:-100}"
HAPROXY_EDGE_ERR_RATE_PER_30S="${HAPROXY_EDGE_ERR_RATE_PER_30S:-120}"
HAPROXY_EDGE_SUBMIT_RATE_PER_MINUTE="${HAPROXY_EDGE_SUBMIT_RATE_PER_MINUTE:-120}"

CERT_FILE="/etc/haproxy/certs/${DOMAIN}.pem"

# ---------------------------------------------------------------------------
# TLS bootstrap: generate a self-signed certificate if no real cert exists.
# This ensures :443 always binds on first start, before Let's Encrypt issues
# a real certificate. The certbot renewal hook will hot-swap it via Runtime API.
# ---------------------------------------------------------------------------
if [ ! -f "$CERT_FILE" ]; then
    echo "No TLS certificate found at ${CERT_FILE} - generating self-signed bootstrap cert..."
    openssl req -x509 \
        -newkey ec \
        -pkeyopt ec_paramgen_curve:P-256 \
        -keyout /tmp/ss_key.pem \
        -out /tmp/ss_cert.pem \
        -days 90 \
        -nodes \
        -subj "/CN=${DOMAIN}" \
        -addext "subjectAltName=DNS:${DOMAIN},DNS:${API_DOMAIN},DNS:${GRAFANA_DOMAIN},DNS:${VAULT_DOMAIN},DNS:${S3_DOMAIN}" \
        2>/dev/null
    cat /tmp/ss_cert.pem /tmp/ss_key.pem > "$CERT_FILE"
    chmod 600 "$CERT_FILE"
    rm -f /tmp/ss_cert.pem /tmp/ss_key.pem
    echo "Self-signed bootstrap certificate generated."
fi

HTTPS_BIND_LINE=""
HTTP_REDIRECT_RULE=""

if [ "${HAPROXY_BEHIND_CDN:-false}" = "true" ]; then
    HTTP_REDIRECT_RULE="# CDN mode: HTTPS terminated upstream - no redirect"
else
    HTTPS_BIND_LINE="
    bind :443 ssl crt ${CERT_FILE} alpn h2,http/1.1"
    HTTP_REDIRECT_RULE="http-request redirect scheme https code 301 unless { path_beg /.well-known/acme-challenge/ } || { ssl_fc }"
fi

cat > /tmp/fe_main.cfg << EOF
# Generated by entrypoint.sh - do not edit manually

frontend fe_main
    bind :80${HTTPS_BIND_LINE}
    option http-ignore-probes

    filter cache short_cache
    filter cache avatar_cache
    filter cache scoreboard_cache

    ${HTTP_REDIRECT_RULE}

    # sc0 = HTTP request rate  (HTTP flood)
    # sc1 = new connection rate (TCP/connection flood)
    # sc2 = HTTP error rate    (scanner / brute-force detection)
    # sc3 = submit path rate   (flag brute-force)
    #
    # In CDN mode: track real client IP from the first XFF entry.
    # In direct mode: track src (direct connection IP).
    acl from_cdn src -f /etc/haproxy/maps/cdn_cidrs.txt

    http-request track-sc0 hdr(X-Forwarded-For,1) table st_per_ip_rate if from_cdn
    http-request track-sc0 src                     table st_per_ip_rate if !from_cdn

    http-request track-sc1 src table st_per_ip_conn

    http-request track-sc2 hdr(X-Forwarded-For,1) table st_per_ip_err if from_cdn
    http-request track-sc2 src                     table st_per_ip_err if !from_cdn

    acl is_submit_path path_reg -i ^/api/v1/challenges/[^/]+/submit$
    http-request track-sc3 hdr(X-Forwarded-For,1) table st_submit_abuse if is_submit_path from_cdn
    http-request track-sc3 src                     table st_submit_abuse if is_submit_path !from_cdn

    http-request deny deny_status 429 if { sc_conn_rate(1,st_per_ip_conn) gt ${HAPROXY_EDGE_CONN_RATE_PER_10S} }
    http-request deny deny_status 429 if { sc_http_req_rate(0,st_per_ip_rate) gt ${HAPROXY_EDGE_REQ_RATE_PER_MINUTE} }
    http-request deny deny_status 403 if { sc_http_err_rate(2,st_per_ip_err) gt ${HAPROXY_EDGE_ERR_RATE_PER_30S} }
    http-request deny deny_status 429 if is_submit_path { sc_http_req_rate(3,st_submit_abuse) gt ${HAPROXY_EDGE_SUBMIT_RATE_PER_MINUTE} }

    http-request del-header X-Real-IP
    http-request del-header X-Forwarded-For if !from_cdn

    http-request set-header X-Real-IP %[hdr(X-Forwarded-For,1)] if from_cdn
    http-request set-header X-Real-IP %[src]                     if !from_cdn

    # X-Forwarded-For is appended by "option forwardfor" in defaults
    http-request set-header X-Forwarded-Proto https if from_cdn
    http-request set-header X-Forwarded-Proto https if !from_cdn { ssl_fc }
    http-request set-header X-Forwarded-Proto http  if !from_cdn !{ ssl_fc }

    http-response set-header X-Frame-Options              "DENY"
    http-response set-header X-Content-Type-Options       "nosniff"
    http-response set-header Strict-Transport-Security    "max-age=63072000; includeSubDomains; preload"
    http-response set-header Referrer-Policy              "strict-origin-when-cross-origin"
    http-response set-header Cross-Origin-Opener-Policy   "same-origin"
    http-response set-header Cross-Origin-Resource-Policy "same-site"
    http-response set-header Permissions-Policy           "geolocation=(), microphone=(), camera=(), interest-cohort=()"
    http-response set-header Retry-After                  "60" if { status eq 429 }
    http-response del-header Server
    http-response set-header Vary "Accept-Encoding" if { res.comp }

    acl is_acme      path_beg /.well-known/acme-challenge/
    acl is_grafana   hdr(host) -i ${GRAFANA_DOMAIN}
    acl is_vault     hdr(host) -i ${VAULT_DOMAIN}
    acl is_s3        hdr(host) -i ${S3_DOMAIN}
    acl is_s3_filer  path_beg /filer/
    acl is_s3_master path_beg /master/
    acl admin_ok     src -f /etc/haproxy/maps/admin_ips.txt
    acl vault_ok     src -f /etc/haproxy/maps/vault_ips.txt

    acl is_api_host hdr(host) -i ${API_DOMAIN}

    acl is_ws         path /api/v1/ws
    acl is_ws_upgrade hdr(Upgrade) -i websocket

    acl is_sse path /api/v1/sse
    acl is_api path_beg /api/

    http-request deny deny_status 403 if is_grafana !admin_ok !is_acme
    http-request deny deny_status 403 if is_vault   !vault_ok !is_acme
    http-request deny deny_status 403 if is_s3      !admin_ok !is_acme

    # Edge cache lookups - GET/HEAD only on public cacheable paths.
    # Placed after access-control denies so blocked paths never hit cache.
    acl is_cacheable_api_get  method GET HEAD
    acl is_public_api         path_beg /api/v1/competition/status /api/v1/tags /api/v1/brackets /api/v1/fields /api/v1/pages /api/v1/challenges/types /api/v1/notifications /api/v1/robots.txt /api/v1/tos /api/v1/privacy /api/v1/configs/public /api/v1/statistics/ /api/v1/scoreboard/graph
    acl is_avatar             path_beg /avatars/
    acl is_scoreboard         path /api/v1/scoreboard

    http-request set-var(txn.cache_avatar)     str(1) if is_cacheable_api_get is_avatar
    http-request set-var(txn.cache_public_api) str(1) if is_cacheable_api_get is_public_api
    http-request set-var(txn.cache_scoreboard) str(1) if is_cacheable_api_get is_scoreboard

    http-request  cache-use avatar_cache     if is_cacheable_api_get is_avatar
    http-response cache-store avatar_cache   if { var(txn.cache_avatar) -m str 1 }

    http-request  cache-use short_cache      if is_cacheable_api_get is_public_api
    http-response cache-store short_cache    if { var(txn.cache_public_api) -m str 1 }

    http-request  cache-use scoreboard_cache  if is_cacheable_api_get is_scoreboard
    http-response cache-store scoreboard_cache if { var(txn.cache_scoreboard) -m str 1 }

    use_backend bk_acme if is_acme
    use_backend bk_seaweedfs_filer  if is_s3 is_s3_filer
    use_backend bk_seaweedfs_master if is_s3 is_s3_master
    use_backend bk_s3_ui            if is_s3
    use_backend bk_grafana          if is_grafana
    use_backend bk_vault            if is_vault

    # api.DOMAIN host-based routing (before path-based catch-all)
    use_backend bk_websocket if is_api_host is_ws is_ws_upgrade
    use_backend bk_sse       if is_api_host is_sse
    use_backend bk_api       if is_api_host

    # WS/SSE must come before the generic /api/ catch-all
    use_backend bk_websocket if is_ws is_ws_upgrade
    use_backend bk_sse       if is_sse

    use_backend bk_api if is_api

    default_backend bk_frontend

# Not published to host (expose only in docker-compose). Access via SSH tunnel.
frontend fe_stats
    bind :8405

    stats enable
    stats uri /stats
    stats refresh 5s
    stats auth ${HAPROXY_STATS_USER}:${HAPROXY_STATS_PASSWORD}
    stats show-legends
    stats show-node

    http-request use-service prometheus-exporter if { path /metrics }
    http-request return status 200 content-type "text/plain" lf-string "OK\n" if { path /health }
EOF

haproxy -c \
    -f /usr/local/etc/haproxy/haproxy.cfg \
    -f /tmp/fe_main.cfg

exec haproxy \
    -f /usr/local/etc/haproxy/haproxy.cfg \
    -f /tmp/fe_main.cfg \
    -W \
    -db \
    -p /var/run/haproxy/haproxy.pid \
    "$@"
