// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/TakuyaYagam1/AstroCTFb/internal/domain"
)

// NewMockSubmissionRepository creates a new instance of MockSubmissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubmissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubmissionRepository {
	mock := &MockSubmissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubmissionRepository is an autogenerated mock type for the SubmissionRepository type
type MockSubmissionRepository struct {
	mock.Mock
}

type MockSubmissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubmissionRepository) EXPECT() *MockSubmissionRepository_Expecter {
	return &MockSubmissionRepository_Expecter{mock: &_m.Mock}
}

// AcquireAdvisoryLockForSubmit provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) AcquireAdvisoryLockForSubmit(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) error {
	ret := _mock.Called(ctx, teamID, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for AcquireAdvisoryLockForSubmit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, teamID, challengeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireAdvisoryLockForSubmit'
type MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call struct {
	*mock.Call
}

// AcquireAdvisoryLockForSubmit is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - challengeID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) AcquireAdvisoryLockForSubmit(ctx interface{}, teamID interface{}, challengeID interface{}) *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call {
	return &MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call{Call: _e.mock.On("AcquireAdvisoryLockForSubmit", ctx, teamID, challengeID)}
}

func (_c *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call) Run(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID)) *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call) Return(err error) *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) error) *MockSubmissionRepository_AcquireAdvisoryLockForSubmit_Call {
	_c.Call.Return(run)
	return _c
}

// CountAll provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountAll(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type MockSubmissionRepository_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubmissionRepository_Expecter) CountAll(ctx interface{}) *MockSubmissionRepository_CountAll_Call {
	return &MockSubmissionRepository_CountAll_Call{Call: _e.mock.On("CountAll", ctx)}
}

func (_c *MockSubmissionRepository_CountAll_Call) Run(run func(ctx context.Context)) *MockSubmissionRepository_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountAll_Call) Return(n int64, err error) *MockSubmissionRepository_CountAll_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountAll_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockSubmissionRepository_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// CountAllFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountAllFrozen(ctx context.Context, freezeTime time.Time) (int64, error) {
	ret := _mock.Called(ctx, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for CountAllFrozen")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, freezeTime)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountAllFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAllFrozen'
type MockSubmissionRepository_CountAllFrozen_Call struct {
	*mock.Call
}

// CountAllFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime time.Time
func (_e *MockSubmissionRepository_Expecter) CountAllFrozen(ctx interface{}, freezeTime interface{}) *MockSubmissionRepository_CountAllFrozen_Call {
	return &MockSubmissionRepository_CountAllFrozen_Call{Call: _e.mock.On("CountAllFrozen", ctx, freezeTime)}
}

func (_c *MockSubmissionRepository_CountAllFrozen_Call) Run(run func(ctx context.Context, freezeTime time.Time)) *MockSubmissionRepository_CountAllFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountAllFrozen_Call) Return(n int64, err error) *MockSubmissionRepository_CountAllFrozen_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountAllFrozen_Call) RunAndReturn(run func(ctx context.Context, freezeTime time.Time) (int64, error)) *MockSubmissionRepository_CountAllFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// CountByChallenge provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByChallenge(ctx context.Context, challengeID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for CountByChallenge")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, challengeID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByChallenge'
type MockSubmissionRepository_CountByChallenge_Call struct {
	*mock.Call
}

// CountByChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountByChallenge(ctx interface{}, challengeID interface{}) *MockSubmissionRepository_CountByChallenge_Call {
	return &MockSubmissionRepository_CountByChallenge_Call{Call: _e.mock.On("CountByChallenge", ctx, challengeID)}
}

func (_c *MockSubmissionRepository_CountByChallenge_Call) Run(run func(ctx context.Context, challengeID uuid.UUID)) *MockSubmissionRepository_CountByChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByChallenge_Call) Return(n int64, err error) *MockSubmissionRepository_CountByChallenge_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByChallenge_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountByChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// CountByChallengeFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByChallengeFrozen(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time) (int64, error) {
	ret := _mock.Called(ctx, challengeID, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for CountByChallengeFrozen")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int64, error)); ok {
		return returnFunc(ctx, challengeID, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int64); ok {
		r0 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByChallengeFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByChallengeFrozen'
type MockSubmissionRepository_CountByChallengeFrozen_Call struct {
	*mock.Call
}

// CountByChallengeFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - freezeTime time.Time
func (_e *MockSubmissionRepository_Expecter) CountByChallengeFrozen(ctx interface{}, challengeID interface{}, freezeTime interface{}) *MockSubmissionRepository_CountByChallengeFrozen_Call {
	return &MockSubmissionRepository_CountByChallengeFrozen_Call{Call: _e.mock.On("CountByChallengeFrozen", ctx, challengeID, freezeTime)}
}

func (_c *MockSubmissionRepository_CountByChallengeFrozen_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time)) *MockSubmissionRepository_CountByChallengeFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByChallengeFrozen_Call) Return(n int64, err error) *MockSubmissionRepository_CountByChallengeFrozen_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByChallengeFrozen_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time) (int64, error)) *MockSubmissionRepository_CountByChallengeFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// CountByTeam provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeam")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeam'
type MockSubmissionRepository_CountByTeam_Call struct {
	*mock.Call
}

// CountByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountByTeam(ctx interface{}, teamID interface{}) *MockSubmissionRepository_CountByTeam_Call {
	return &MockSubmissionRepository_CountByTeam_Call{Call: _e.mock.On("CountByTeam", ctx, teamID)}
}

func (_c *MockSubmissionRepository_CountByTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSubmissionRepository_CountByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByTeam_Call) Return(n int64, err error) *MockSubmissionRepository_CountByTeam_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// CountByTeamFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByTeamFrozen(ctx context.Context, teamID uuid.UUID, freezeTime time.Time) (int64, error) {
	ret := _mock.Called(ctx, teamID, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeamFrozen")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int64, error)); ok {
		return returnFunc(ctx, teamID, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int64); ok {
		r0 = returnFunc(ctx, teamID, freezeTime)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, teamID, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByTeamFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeamFrozen'
type MockSubmissionRepository_CountByTeamFrozen_Call struct {
	*mock.Call
}

// CountByTeamFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - freezeTime time.Time
func (_e *MockSubmissionRepository_Expecter) CountByTeamFrozen(ctx interface{}, teamID interface{}, freezeTime interface{}) *MockSubmissionRepository_CountByTeamFrozen_Call {
	return &MockSubmissionRepository_CountByTeamFrozen_Call{Call: _e.mock.On("CountByTeamFrozen", ctx, teamID, freezeTime)}
}

func (_c *MockSubmissionRepository_CountByTeamFrozen_Call) Run(run func(ctx context.Context, teamID uuid.UUID, freezeTime time.Time)) *MockSubmissionRepository_CountByTeamFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByTeamFrozen_Call) Return(n int64, err error) *MockSubmissionRepository_CountByTeamFrozen_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByTeamFrozen_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, freezeTime time.Time) (int64, error)) *MockSubmissionRepository_CountByTeamFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// CountByUser provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUser'
type MockSubmissionRepository_CountByUser_Call struct {
	*mock.Call
}

// CountByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountByUser(ctx interface{}, userID interface{}) *MockSubmissionRepository_CountByUser_Call {
	return &MockSubmissionRepository_CountByUser_Call{Call: _e.mock.On("CountByUser", ctx, userID)}
}

func (_c *MockSubmissionRepository_CountByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSubmissionRepository_CountByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByUser_Call) Return(n int64, err error) *MockSubmissionRepository_CountByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountByUser_Call {
	_c.Call.Return(run)
	return _c
}

// CountByUserFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountByUserFrozen(ctx context.Context, userID uuid.UUID, freezeTime time.Time) (int64, error) {
	ret := _mock.Called(ctx, userID, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserFrozen")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int64, error)); ok {
		return returnFunc(ctx, userID, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int64); ok {
		r0 = returnFunc(ctx, userID, freezeTime)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountByUserFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserFrozen'
type MockSubmissionRepository_CountByUserFrozen_Call struct {
	*mock.Call
}

// CountByUserFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - freezeTime time.Time
func (_e *MockSubmissionRepository_Expecter) CountByUserFrozen(ctx interface{}, userID interface{}, freezeTime interface{}) *MockSubmissionRepository_CountByUserFrozen_Call {
	return &MockSubmissionRepository_CountByUserFrozen_Call{Call: _e.mock.On("CountByUserFrozen", ctx, userID, freezeTime)}
}

func (_c *MockSubmissionRepository_CountByUserFrozen_Call) Run(run func(ctx context.Context, userID uuid.UUID, freezeTime time.Time)) *MockSubmissionRepository_CountByUserFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountByUserFrozen_Call) Return(n int64, err error) *MockSubmissionRepository_CountByUserFrozen_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountByUserFrozen_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, freezeTime time.Time) (int64, error)) *MockSubmissionRepository_CountByUserFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// CountFailedByIP provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountFailedByIP(ctx context.Context, ip string, since time.Time) (int64, error) {
	ret := _mock.Called(ctx, ip, since)

	if len(ret) == 0 {
		panic("no return value specified for CountFailedByIP")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (int64, error)); ok {
		return returnFunc(ctx, ip, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) int64); ok {
		r0 = returnFunc(ctx, ip, since)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, ip, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountFailedByIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFailedByIP'
type MockSubmissionRepository_CountFailedByIP_Call struct {
	*mock.Call
}

// CountFailedByIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - since time.Time
func (_e *MockSubmissionRepository_Expecter) CountFailedByIP(ctx interface{}, ip interface{}, since interface{}) *MockSubmissionRepository_CountFailedByIP_Call {
	return &MockSubmissionRepository_CountFailedByIP_Call{Call: _e.mock.On("CountFailedByIP", ctx, ip, since)}
}

func (_c *MockSubmissionRepository_CountFailedByIP_Call) Run(run func(ctx context.Context, ip string, since time.Time)) *MockSubmissionRepository_CountFailedByIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountFailedByIP_Call) Return(n int64, err error) *MockSubmissionRepository_CountFailedByIP_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountFailedByIP_Call) RunAndReturn(run func(ctx context.Context, ip string, since time.Time) (int64, error)) *MockSubmissionRepository_CountFailedByIP_Call {
	_c.Call.Return(run)
	return _c
}

// CountFailsByTeam provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountFailsByTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountFailsByTeam")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountFailsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFailsByTeam'
type MockSubmissionRepository_CountFailsByTeam_Call struct {
	*mock.Call
}

// CountFailsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountFailsByTeam(ctx interface{}, teamID interface{}) *MockSubmissionRepository_CountFailsByTeam_Call {
	return &MockSubmissionRepository_CountFailsByTeam_Call{Call: _e.mock.On("CountFailsByTeam", ctx, teamID)}
}

func (_c *MockSubmissionRepository_CountFailsByTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSubmissionRepository_CountFailsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountFailsByTeam_Call) Return(n int64, err error) *MockSubmissionRepository_CountFailsByTeam_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountFailsByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountFailsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// CountFailsByUser provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountFailsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountFailsByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountFailsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFailsByUser'
type MockSubmissionRepository_CountFailsByUser_Call struct {
	*mock.Call
}

// CountFailsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountFailsByUser(ctx interface{}, userID interface{}) *MockSubmissionRepository_CountFailsByUser_Call {
	return &MockSubmissionRepository_CountFailsByUser_Call{Call: _e.mock.On("CountFailsByUser", ctx, userID)}
}

func (_c *MockSubmissionRepository_CountFailsByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSubmissionRepository_CountFailsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountFailsByUser_Call) Return(n int64, err error) *MockSubmissionRepository_CountFailsByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountFailsByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountFailsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// CountSubmissionsByTeamAndChallenge provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CountSubmissionsByTeamAndChallenge(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, teamID, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for CountSubmissionsByTeamAndChallenge")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, teamID, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, teamID, challengeID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, teamID, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSubmissionsByTeamAndChallenge'
type MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call struct {
	*mock.Call
}

// CountSubmissionsByTeamAndChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - challengeID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) CountSubmissionsByTeamAndChallenge(ctx interface{}, teamID interface{}, challengeID interface{}) *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call {
	return &MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call{Call: _e.mock.On("CountSubmissionsByTeamAndChallenge", ctx, teamID, challengeID)}
}

func (_c *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call) Run(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID)) *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call) Return(n int64, err error) *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, challengeID uuid.UUID) (int64, error)) *MockSubmissionRepository_CountSubmissionsByTeamAndChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) Create(ctx context.Context, sub *domain.Submission) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Submission) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubmissionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *domain.Submission
func (_e *MockSubmissionRepository_Expecter) Create(ctx interface{}, sub interface{}) *MockSubmissionRepository_Create_Call {
	return &MockSubmissionRepository_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockSubmissionRepository_Create_Call) Run(run func(ctx context.Context, sub *domain.Submission)) *MockSubmissionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Submission
		if args[1] != nil {
			arg1 = args[1].(*domain.Submission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_Create_Call) Return(err error) *MockSubmissionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, sub *domain.Submission) error) *MockSubmissionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) CreateBatch(ctx context.Context, subs []*domain.Submission) error {
	ret := _mock.Called(ctx, subs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*domain.Submission) error); ok {
		r0 = returnFunc(ctx, subs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockSubmissionRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - subs []*domain.Submission
func (_e *MockSubmissionRepository_Expecter) CreateBatch(ctx interface{}, subs interface{}) *MockSubmissionRepository_CreateBatch_Call {
	return &MockSubmissionRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, subs)}
}

func (_c *MockSubmissionRepository_CreateBatch_Call) Run(run func(ctx context.Context, subs []*domain.Submission)) *MockSubmissionRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*domain.Submission
		if args[1] != nil {
			arg1 = args[1].([]*domain.Submission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_CreateBatch_Call) Return(err error) *MockSubmissionRepository_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, subs []*domain.Submission) error) *MockSubmissionRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubmissionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockSubmissionRepository_Delete_Call {
	return &MockSubmissionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockSubmissionRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockSubmissionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_Delete_Call) Return(err error) *MockSubmissionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockSubmissionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTeamID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) DeleteByTeamID(ctx context.Context, teamID uuid.UUID) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTeamID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_DeleteByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTeamID'
type MockSubmissionRepository_DeleteByTeamID_Call struct {
	*mock.Call
}

// DeleteByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) DeleteByTeamID(ctx interface{}, teamID interface{}) *MockSubmissionRepository_DeleteByTeamID_Call {
	return &MockSubmissionRepository_DeleteByTeamID_Call{Call: _e.mock.On("DeleteByTeamID", ctx, teamID)}
}

func (_c *MockSubmissionRepository_DeleteByTeamID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSubmissionRepository_DeleteByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_DeleteByTeamID_Call) Return(err error) *MockSubmissionRepository_DeleteByTeamID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_DeleteByTeamID_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) error) *MockSubmissionRepository_DeleteByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetAll(ctx context.Context, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSubmissionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetAll(ctx interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetAll_Call {
	return &MockSubmissionRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, limit, offset)}
}

func (_c *MockSubmissionRepository_GetAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockSubmissionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetAll_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetAll_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetAllFrozen(ctx context.Context, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, freezeTime, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFrozen")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, freezeTime, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, freezeTime, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, freezeTime, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetAllFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFrozen'
type MockSubmissionRepository_GetAllFrozen_Call struct {
	*mock.Call
}

// GetAllFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - freezeTime time.Time
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetAllFrozen(ctx interface{}, freezeTime interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetAllFrozen_Call {
	return &MockSubmissionRepository_GetAllFrozen_Call{Call: _e.mock.On("GetAllFrozen", ctx, freezeTime, limit, offset)}
}

func (_c *MockSubmissionRepository_GetAllFrozen_Call) Run(run func(ctx context.Context, freezeTime time.Time, limit int, offset int)) *MockSubmissionRepository_GetAllFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetAllFrozen_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetAllFrozen_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetAllFrozen_Call) RunAndReturn(run func(ctx context.Context, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetAllFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChallenge provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByChallenge(ctx context.Context, challengeID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, challengeID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByChallenge")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, challengeID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, challengeID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, challengeID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChallenge'
type MockSubmissionRepository_GetByChallenge_Call struct {
	*mock.Call
}

// GetByChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByChallenge(ctx interface{}, challengeID interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByChallenge_Call {
	return &MockSubmissionRepository_GetByChallenge_Call{Call: _e.mock.On("GetByChallenge", ctx, challengeID, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByChallenge_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, limit int, offset int)) *MockSubmissionRepository_GetByChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByChallenge_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByChallenge_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByChallenge_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChallengeFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByChallengeFrozen(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, challengeID, freezeTime, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByChallengeFrozen")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, challengeID, freezeTime, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, challengeID, freezeTime, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, challengeID, freezeTime, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByChallengeFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChallengeFrozen'
type MockSubmissionRepository_GetByChallengeFrozen_Call struct {
	*mock.Call
}

// GetByChallengeFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - freezeTime time.Time
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByChallengeFrozen(ctx interface{}, challengeID interface{}, freezeTime interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByChallengeFrozen_Call {
	return &MockSubmissionRepository_GetByChallengeFrozen_Call{Call: _e.mock.On("GetByChallengeFrozen", ctx, challengeID, freezeTime, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByChallengeFrozen_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time, limit int, offset int)) *MockSubmissionRepository_GetByChallengeFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByChallengeFrozen_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByChallengeFrozen_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByChallengeFrozen_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByChallengeFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByID(ctx context.Context, ID uuid.UUID) (*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubmissionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockSubmissionRepository_GetByID_Call {
	return &MockSubmissionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockSubmissionRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockSubmissionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByID_Call) Return(submissionWithDetails *domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByID_Call {
	_c.Call.Return(submissionWithDetails, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUpdate provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByIDForUpdate(ctx context.Context, ID uuid.UUID) (*domain.Submission, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdate")
	}

	var r0 *domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Submission, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Submission); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdate'
type MockSubmissionRepository_GetByIDForUpdate_Call struct {
	*mock.Call
}

// GetByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) GetByIDForUpdate(ctx interface{}, ID interface{}) *MockSubmissionRepository_GetByIDForUpdate_Call {
	return &MockSubmissionRepository_GetByIDForUpdate_Call{Call: _e.mock.On("GetByIDForUpdate", ctx, ID)}
}

func (_c *MockSubmissionRepository_GetByIDForUpdate_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockSubmissionRepository_GetByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByIDForUpdate_Call) Return(submission *domain.Submission, err error) *MockSubmissionRepository_GetByIDForUpdate_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*domain.Submission, error)) *MockSubmissionRepository_GetByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeam provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByTeam(ctx context.Context, teamID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeam")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, teamID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeam'
type MockSubmissionRepository_GetByTeam_Call struct {
	*mock.Call
}

// GetByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByTeam(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByTeam_Call {
	return &MockSubmissionRepository_GetByTeam_Call{Call: _e.mock.On("GetByTeam", ctx, teamID, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID, limit int, offset int)) *MockSubmissionRepository_GetByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByTeam_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByTeam_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeamFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByTeamFrozen(ctx context.Context, teamID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, teamID, freezeTime, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamFrozen")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, teamID, freezeTime, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, teamID, freezeTime, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, teamID, freezeTime, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByTeamFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamFrozen'
type MockSubmissionRepository_GetByTeamFrozen_Call struct {
	*mock.Call
}

// GetByTeamFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - freezeTime time.Time
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByTeamFrozen(ctx interface{}, teamID interface{}, freezeTime interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByTeamFrozen_Call {
	return &MockSubmissionRepository_GetByTeamFrozen_Call{Call: _e.mock.On("GetByTeamFrozen", ctx, teamID, freezeTime, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByTeamFrozen_Call) Run(run func(ctx context.Context, teamID uuid.UUID, freezeTime time.Time, limit int, offset int)) *MockSubmissionRepository_GetByTeamFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByTeamFrozen_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByTeamFrozen_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByTeamFrozen_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByTeamFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByUser(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockSubmissionRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByUser_Call {
	return &MockSubmissionRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockSubmissionRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByUser_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByUser_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetByUserFrozen(ctx context.Context, userID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, userID, freezeTime, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserFrozen")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, userID, freezeTime, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, userID, freezeTime, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, userID, freezeTime, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetByUserFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserFrozen'
type MockSubmissionRepository_GetByUserFrozen_Call struct {
	*mock.Call
}

// GetByUserFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - freezeTime time.Time
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetByUserFrozen(ctx interface{}, userID interface{}, freezeTime interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetByUserFrozen_Call {
	return &MockSubmissionRepository_GetByUserFrozen_Call{Call: _e.mock.On("GetByUserFrozen", ctx, userID, freezeTime, limit, offset)}
}

func (_c *MockSubmissionRepository_GetByUserFrozen_Call) Run(run func(ctx context.Context, userID uuid.UUID, freezeTime time.Time, limit int, offset int)) *MockSubmissionRepository_GetByUserFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetByUserFrozen_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetByUserFrozen_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetByUserFrozen_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, freezeTime time.Time, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetByUserFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// GetFailsByTeam provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetFailsByTeam(ctx context.Context, teamID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFailsByTeam")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, teamID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetFailsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFailsByTeam'
type MockSubmissionRepository_GetFailsByTeam_Call struct {
	*mock.Call
}

// GetFailsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetFailsByTeam(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetFailsByTeam_Call {
	return &MockSubmissionRepository_GetFailsByTeam_Call{Call: _e.mock.On("GetFailsByTeam", ctx, teamID, limit, offset)}
}

func (_c *MockSubmissionRepository_GetFailsByTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID, limit int, offset int)) *MockSubmissionRepository_GetFailsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetFailsByTeam_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetFailsByTeam_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetFailsByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetFailsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetFailsByUser provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetFailsByUser(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFailsByUser")
	}

	var r0 []*domain.SubmissionWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.SubmissionWithDetails, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.SubmissionWithDetails); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SubmissionWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetFailsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFailsByUser'
type MockSubmissionRepository_GetFailsByUser_Call struct {
	*mock.Call
}

// GetFailsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionRepository_Expecter) GetFailsByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockSubmissionRepository_GetFailsByUser_Call {
	return &MockSubmissionRepository_GetFailsByUser_Call{Call: _e.mock.On("GetFailsByUser", ctx, userID, limit, offset)}
}

func (_c *MockSubmissionRepository_GetFailsByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockSubmissionRepository_GetFailsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetFailsByUser_Call) Return(submissionWithDetailss []*domain.SubmissionWithDetails, err error) *MockSubmissionRepository_GetFailsByUser_Call {
	_c.Call.Return(submissionWithDetailss, err)
	return _c
}

func (_c *MockSubmissionRepository_GetFailsByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.SubmissionWithDetails, error)) *MockSubmissionRepository_GetFailsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetStats(ctx context.Context, challengeID uuid.UUID) (*domain.SubmissionStats, error) {
	ret := _mock.Called(ctx, challengeID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.SubmissionStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.SubmissionStats, error)); ok {
		return returnFunc(ctx, challengeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.SubmissionStats); ok {
		r0 = returnFunc(ctx, challengeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SubmissionStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, challengeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockSubmissionRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) GetStats(ctx interface{}, challengeID interface{}) *MockSubmissionRepository_GetStats_Call {
	return &MockSubmissionRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, challengeID)}
}

func (_c *MockSubmissionRepository_GetStats_Call) Run(run func(ctx context.Context, challengeID uuid.UUID)) *MockSubmissionRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetStats_Call) Return(submissionStats *domain.SubmissionStats, err error) *MockSubmissionRepository_GetStats_Call {
	_c.Call.Return(submissionStats, err)
	return _c
}

func (_c *MockSubmissionRepository_GetStats_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID) (*domain.SubmissionStats, error)) *MockSubmissionRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsFrozen provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) GetStatsFrozen(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time) (*domain.SubmissionStats, error) {
	ret := _mock.Called(ctx, challengeID, freezeTime)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsFrozen")
	}

	var r0 *domain.SubmissionStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*domain.SubmissionStats, error)); ok {
		return returnFunc(ctx, challengeID, freezeTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *domain.SubmissionStats); ok {
		r0 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SubmissionStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, challengeID, freezeTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionRepository_GetStatsFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsFrozen'
type MockSubmissionRepository_GetStatsFrozen_Call struct {
	*mock.Call
}

// GetStatsFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeID uuid.UUID
//   - freezeTime time.Time
func (_e *MockSubmissionRepository_Expecter) GetStatsFrozen(ctx interface{}, challengeID interface{}, freezeTime interface{}) *MockSubmissionRepository_GetStatsFrozen_Call {
	return &MockSubmissionRepository_GetStatsFrozen_Call{Call: _e.mock.On("GetStatsFrozen", ctx, challengeID, freezeTime)}
}

func (_c *MockSubmissionRepository_GetStatsFrozen_Call) Run(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time)) *MockSubmissionRepository_GetStatsFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_GetStatsFrozen_Call) Return(submissionStats *domain.SubmissionStats, err error) *MockSubmissionRepository_GetStatsFrozen_Call {
	_c.Call.Return(submissionStats, err)
	return _c
}

func (_c *MockSubmissionRepository_GetStatsFrozen_Call) RunAndReturn(run func(ctx context.Context, challengeID uuid.UUID, freezeTime time.Time) (*domain.SubmissionStats, error)) *MockSubmissionRepository_GetStatsFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByBannedTeamID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) RestoreByBannedTeamID(ctx context.Context, teamID uuid.UUID) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByBannedTeamID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_RestoreByBannedTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByBannedTeamID'
type MockSubmissionRepository_RestoreByBannedTeamID_Call struct {
	*mock.Call
}

// RestoreByBannedTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) RestoreByBannedTeamID(ctx interface{}, teamID interface{}) *MockSubmissionRepository_RestoreByBannedTeamID_Call {
	return &MockSubmissionRepository_RestoreByBannedTeamID_Call{Call: _e.mock.On("RestoreByBannedTeamID", ctx, teamID)}
}

func (_c *MockSubmissionRepository_RestoreByBannedTeamID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSubmissionRepository_RestoreByBannedTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_RestoreByBannedTeamID_Call) Return(err error) *MockSubmissionRepository_RestoreByBannedTeamID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_RestoreByBannedTeamID_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) error) *MockSubmissionRepository_RestoreByBannedTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByBannedUserID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) RestoreByBannedUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByBannedUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_RestoreByBannedUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByBannedUserID'
type MockSubmissionRepository_RestoreByBannedUserID_Call struct {
	*mock.Call
}

// RestoreByBannedUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) RestoreByBannedUserID(ctx interface{}, userID interface{}) *MockSubmissionRepository_RestoreByBannedUserID_Call {
	return &MockSubmissionRepository_RestoreByBannedUserID_Call{Call: _e.mock.On("RestoreByBannedUserID", ctx, userID)}
}

func (_c *MockSubmissionRepository_RestoreByBannedUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSubmissionRepository_RestoreByBannedUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_RestoreByBannedUserID_Call) Return(err error) *MockSubmissionRepository_RestoreByBannedUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_RestoreByBannedUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSubmissionRepository_RestoreByBannedUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftBanByTeamID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) SoftBanByTeamID(ctx context.Context, teamID uuid.UUID) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for SoftBanByTeamID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_SoftBanByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftBanByTeamID'
type MockSubmissionRepository_SoftBanByTeamID_Call struct {
	*mock.Call
}

// SoftBanByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) SoftBanByTeamID(ctx interface{}, teamID interface{}) *MockSubmissionRepository_SoftBanByTeamID_Call {
	return &MockSubmissionRepository_SoftBanByTeamID_Call{Call: _e.mock.On("SoftBanByTeamID", ctx, teamID)}
}

func (_c *MockSubmissionRepository_SoftBanByTeamID_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockSubmissionRepository_SoftBanByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_SoftBanByTeamID_Call) Return(err error) *MockSubmissionRepository_SoftBanByTeamID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_SoftBanByTeamID_Call) RunAndReturn(run func(ctx context.Context, teamID uuid.UUID) error) *MockSubmissionRepository_SoftBanByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftBanByUserID provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) SoftBanByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftBanByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_SoftBanByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftBanByUserID'
type MockSubmissionRepository_SoftBanByUserID_Call struct {
	*mock.Call
}

// SoftBanByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSubmissionRepository_Expecter) SoftBanByUserID(ctx interface{}, userID interface{}) *MockSubmissionRepository_SoftBanByUserID_Call {
	return &MockSubmissionRepository_SoftBanByUserID_Call{Call: _e.mock.On("SoftBanByUserID", ctx, userID)}
}

func (_c *MockSubmissionRepository_SoftBanByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSubmissionRepository_SoftBanByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_SoftBanByUserID_Call) Return(err error) *MockSubmissionRepository_SoftBanByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_SoftBanByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSubmissionRepository_SoftBanByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubmissionRepository
func (_mock *MockSubmissionRepository) Update(ctx context.Context, ID uuid.UUID, isCorrect bool) error {
	ret := _mock.Called(ctx, ID, isCorrect)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, ID, isCorrect)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmissionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubmissionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - isCorrect bool
func (_e *MockSubmissionRepository_Expecter) Update(ctx interface{}, ID interface{}, isCorrect interface{}) *MockSubmissionRepository_Update_Call {
	return &MockSubmissionRepository_Update_Call{Call: _e.mock.On("Update", ctx, ID, isCorrect)}
}

func (_c *MockSubmissionRepository_Update_Call) Run(run func(ctx context.Context, ID uuid.UUID, isCorrect bool)) *MockSubmissionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubmissionRepository_Update_Call) Return(err error) *MockSubmissionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmissionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, isCorrect bool) error) *MockSubmissionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
